### ISSUE TITLE
1.9-Can't craft digit 2 dimlet

### ISSUE THREAD

**Issue by RealGrep** [McJty/RFToolsDimensions#10]
Though JEI seems to show the recipe just fine, being a digit 1 dimlet in the center of the crafting grid, I can't seem to make the digit 2 dimlet. I can make the digit 1 with a digit 0, but I can't go further. It just gives me a digit 1 dimlet again. Tried in three different crafting tables, including the vanilla one.

This is with rftoolsdim-1.9.0-4.23beta37.jar and Forge version 1867 (EDIT: Upgraded to 1882 with no change).

No errors or other info appear in the client or server logs. Let me know if there's any information I can provide to help.

**Comment by McJty** [comment]
That was fixed some time ago
