### ISSUE TITLE
Duplicate bug - confirmed in ssp and mp

### ISSUE THREAD

**Issue by Benedictum** [McJty/RFToolsDimensions#100]
rftools-1.1x-6.00.jar
rftoolsdim-1.1x-4.55.jar

When placing just a single dimlet part in the dimlet workbench and then double clicking on a recipe on the right side, the dimlet part is duplicated exactly in the workbenches inventory. For instance if you put 10 rarity 4 dimlets in the bottom left, then double click any recipe, 10 rarity 4 dimlets will appear in the upper left inventory equaling 20 in total, 10 in the crafting area and 10 in the inventory.

confirmed with all dimlet parts including absorbers

**Comment by McJty** [comment]
I cannot reproduce this. What version of MC and how exactly did you reproduce it?
