### ISSUE TITLE
Dimension material uses Chisel variant

### ISSUE THREAD

**Issue by Viper007Bond** [McJty/RFToolsDimensions#101]
I tried to create a flat Glowstone world but it ended up generating with a Chisel variant instead. I created a second world via a digit dimlet and the same variant was used.

This is the same issue as https://github.com/McJty/RFTools/issues/1040 but I'm making an issue here for better tracking.

RFTools Dimensions v1.1x-4.55
RFTools v1.1x-5.88
(Direwolf v1.8.1 Pack)

**Comment by McJty** [comment]
I can reproduce this. Will try to fix it

**Comment by McJty** [comment]
Fixed next release
