### ISSUE TITLE
Dimension builder return too many dimensions

### ISSUE THREAD

**Issue by barronies33** [McJty/RFToolsDimensions#103]
I'm quiete a beguinner in that mod.
I'm playing "restart" modpack (Minecraft 1.10), found on Twich platform (called Curse before),  on a single world.
I created 5 random worlds, using digit controllers, and on the 6th one, the dimension builder returns "too many dimensions".
Impossible to charge the world, and from this, I'm getting the same message "too many dimensions" even with previous worlds,
I googled this issue but couldn't find anything about it. That's why I'm posting a new issue.

**Comment by barronies33** [comment]
I figured out where was the problem.
In [modpack]\config\rftools\dimension.cfg
I found the parameter maxDimensionsPerPlayer which was set to 5.
If other users encounter the problem, just set it on -1 for unlimited world generations.
Regards

**Comment by McJty** [comment]
The default is actually -1

**Comment by barronies33** [comment]
Well in that particuliary modpack, 5 is the default value.
