### ISSUE TITLE
/time command not advancing sun position in dimensions.

### ISSUE THREAD

**Issue by DonBruce64** [McJty/RFToolsDimensions#104]
Currently run a server with players who regularly play in RFTools dimensions.  They've recently complained to me that you cannot sleep in RFT dims, so I thought I'd set up a command block system to set the time to day if all of them were near their beds.  However, the /time command has no effect in RFTools dims.  Is there any reason for this?  A conflicting mod maybe?  I have Mystcraft installed alongside RFTools, and that works just fine for /time commands.  Currently running MC 1.7.10, Forge 1558, and RFTools rftools-4.23.

**Comment by McJty** [comment]
RFTools dimensions have their own time control and the /time command from vanilla does not know about that

**Comment by DonBruce64** [comment]
Fair enough.  So is there no way to make night pass like in a Vanilla world?  I could care less about the /time command.  Maybe have it so if all the players right-click a bed within a set period of time RFTools sets the dim time to morning?

**Comment by McJty** [comment]
It may be possible but I haven't looked at it yet. It is also a bit complicated by the fact that rftools dimensions sometimes have different time schedules. Like faster time, or constant night

**Comment by DonBruce64** [comment]
I'm assuming the position of the celestial bodies is based on the internal time, yes?  In that case, would it be possible to reference the position of the primary celestial body and figure out the required time advancement from that?  Like, if the main celestial body moves 1 degree every 3 seconds, and has daytime at 45 degrees, then if the main body is at 235 degrees you'd increment the time by 510 seconds if it needs to be set to day?  I'm just throwing things out here; I have yet to mess with the sky during my modding endeavors.  But I would assume there's some variable in the code that's responsible for the position of the sun, and that could just be advanced to simulate the passage of time.

**Comment by josephcsible** [comment]
This seems to work fine for me, if you take into account the time dimlets that are used. Basically:
* If your dimension is set to morning, noon, evening, or midnight, it will always be that no matter what time you set
* If your dimension is set to normal, /time will work just like in the overworld
* If your dimension is set to fast, all of the /time set values are half of usual (so 3000 is noon and 9000 is midnight)
* If your dimension is set to slow, all of the /time set values are double usual (so 12000 is noon and 36000 is midnight)
