### ISSUE TITLE
dialer can't reconized dimension with lost cities dimlet

### ISSUE THREAD

**Issue by ARatfat** [McJty/RFToolsDimensions#106]
hi, 

use forge : 13.20.0.2311
MC : 1.11.2
RFtool : 6.01
Mcjty Lib : 2.3.11
compact layer : 0.2.9
RFTool dimension : 5.0

I want to try new dimlet (lostcities) with this setup https://puu.sh/w8xLR/e0fdfbafc4.png, I create the dimension https://puu.sh/w8xVl/705902c633.png but isn't show in dialing device https://puu.sh/w8xWP/ade110a7e4.png 

Basically a dimension with lost cities dimlet isn't show in dialing device.

Best Regards

**Comment by McJty** [comment]
Can you try again with another dimension? It worked fine for me

**Comment by McJty** [comment]
Also logs would help

**Comment by ARatfat** [comment]
I try again same issue 
I don't use foamfix or optifine. & this is log (sorry for spami log) https://pastebin.com/qDdBqGfi

**Comment by McJty** [comment]
[14:36:21] [Server thread/ERROR] [mcjty.lib.varia.Logging/]: Something went wrong during creation of the dimension!

I need to see the server side log (the big log)

**Comment by ARatfat** [comment]
ok this is it https://puu.sh/w8Cpm/3b48bcee68.log

**Comment by McJty** [comment]
Hmm strange. I'll try to make a few worlds to see if I can reproduce it but there is no actual crash in your log. Is this the log from when you were trying to create the dimension? Because that's the log that I actually need

**Comment by ARatfat** [comment]
I'm truly sorry but I send you all my logs https://puu.sh/w8CP7/a1d796bfd9.zip

**Comment by McJty** [comment]
Ok, this was useful. I found the issue

**Comment by McJty** [comment]
I'll have to fix this but in a few hours from now. Can't do it right now

**Comment by McJty** [comment]
Well I could fix it. When 5.01 is approved it should work (you'll have to make new dimensions though)
