### ISSUE TITLE
Crash generating LostCities Dimension.

### ISSUE THREAD

**Issue by shadow306k** [McJty/RFToolsDimensions#107]
Hey there, just updated RFTools, and generated a dimension using ONLY the LostCities dimlet, and it crashes upon loading.

(Yes I'm pretty dumb at modded stuff, but I at least included the crash report)
[crash-2017-06-02_15.55.34-server.txt](https://github.com/McJty/RFToolsDimensions/files/1048054/crash-2017-06-02_15.55.34-server.txt)

**Comment by McJty** [comment]
Should be fixed in 5.01

**Comment by shadow306k** [comment]
Updated to 5.01 manually from curseforge site, and it worked for a few seconds, then instantly crashed again :\
[crash-2017-06-02_16.25.47-server.txt](https://github.com/McJty/RFToolsDimensions/files/1048113/crash-2017-06-02_16.25.47-server.txt)
[crash-2017-06-02_16.36.28-server.txt](https://github.com/McJty/RFToolsDimensions/files/1048136/crash-2017-06-02_16.36.28-server.txt)

(Woah I didn't know github updated without needing to refresh)

**Comment by McJty** [comment]
Actually this is something else

**Comment by McJty** [comment]
Fixed in 5.02 I hope
