### ISSUE TITLE
Material Absorber Crash w/Deep Resonance

### ISSUE THREAD

**Issue by Thiana** [McJty/RFToolsDimensions#11]
Screen Rendering crash when mousing over a material absorber (Resonating Ore) in inventory.

Reproduce:
(1) Absorb 2 stacks of Resonating Ore into a Material Absorber.
(2) Break absorber when it no longer eats Resonating Ore
(3) Open inventory and mouse over absorber
(4) Crash.

The absorber worked without issue with other blocks I tried, so not sure if this is a DR or RFTools
 crash but since they're both yours... ;) The crash log is available at http://www.curseforge.com/paste/e3a72aba

Thanks.

Versions:
Forge 1868
ElecCore-1.9-1.4.270
deepresonance-1.9.0-1.1.4beta30
MCMultiPart-1.1.1
rftools-1.9.0-4.46
rftoolsdim-1.9.0-4.23beta37

**Comment by shanesova** [comment]
I also discovered the same bug with Resonating Ore, Dimensional Shard Ore and Redstone Ore
I noticed that Waila says <ERROR> when looking at the Absorber when it happens
Diamond Ore, Emerald Ore and I think it was Gold Blocks all seemed to work fine
I ended up just just cheating in the dimlet by doing "/rftdb createdimlet Material rftools:dimensional_shard_ore@0" and then deleting the materials i would have used to create it.

Also I noticed that the Absorber only picks up lit redstone ore or non lit redstone ore but not both at the same time, that was the only ore that was a minecraft ore that i noticed the problem happen with.

**Comment by McJty** [comment]
I can reproduce. Will fix soon

**Comment by McJty** [comment]
Fixed in next release
