### ISSUE TITLE
[1.10.2][Ver 5.02] Fatal Error When Connecting to LAN World - Undefined message for discriminator 82 in channel rftoolsdim

### ISSUE THREAD

**Issue by RFShahrear** [McJty/RFToolsDimensions#110]
Whenever I try to connect to server (LAN) with rftoolsdim, this failure occurs. Neither the server nor the client suffers any crash. Singleplayer world works fine.

Here's the client side log. Server side log shows no error.
[fml-client-latest.txt](https://github.com/McJty/RFToolsDimensions/files/1071132/fml-client-latest.txt)
First error is caught at 45675, non-rftoolsdim error.
First RFTools error is at 45950.

Things I've tried - 
1. Removing RFToolsdim - success. No Error.
2. Removing all other mods - fail.
3. Updating/Downgrading Forge - fail.

I am yet to try downgrading RFToolsDim, since I really want to go to the lost cities.
I'm using the latest version of McJtyLib, CompatLayer, RFTools.
Possible repeat of #93 . But redownloading didn't help.

**Comment by McJty** [comment]
I believe that turretmod is causing this. The first crash is a networking crash caused by that mod and that may corrupt the networking state enough for rftoolsdimensions to have issues after that. I would recommend reporting to them

**Comment by RFShahrear** [comment]
Confirmed. Removing Turretmod from both server and client removed the issue.
**EDIT**
A little update. I did a few more tests and it turns out no mod (including turretmod) was responsible for the error. From what I can tell it was the absence of RFTools control that caused the fatal error, as adding that to the server fixed the issue.
