### ISSUE TITLE
Crash on generating new Scattered Orbs world

### ISSUE THREAD

**Issue by cravl-dev** [McJty/RFToolsDimensions#111]
I was trying to create a new dimension that had scattered orbs in it when my game crashed. I tried to relog but it crashed again. Both stack traces mention Pam's Harvestcraft and the first also mentions a couple other mods. I'm not sure if that's relevant or not, so I've included their version numbers just in case. I had to zip up the dimension's folder and use an NBT editor to put myself back into the overworld to get the world to load.

Here are the dimlets used in order:
[Material: Glass][Terrain: Cavern][Feature: OresAPlenty][Feature: Scattered Orbs][Special: Efficiency]

rftoolsdim-1.1x-5.02
rftools-1.1x-6.01
mcjtylib-1.1x-2.3.11

Pam's HarvestCraft 1.10.2j
taiga-1.10.2-1.2.6
SuperCircuitMaker-1.0.4

[crash-2017-06-14_13.41.41-server.txt](https://github.com/McJty/RFToolsDimensions/files/1075622/crash-2017-06-14_13.41.41-server.txt)
[crash-2017-06-14_13.16.19-server.txt](https://github.com/McJty/RFToolsDimensions/files/1075621/crash-2017-06-14_13.16.19-server.txt)

**Comment by defsil** [comment]
Confirming; just had the same issue right now. Oh man, I was having such a high hopes for this dimension and now it doesn't even start. ._.

Here are the dimlets used in order:
[Material: Block of Emerald][Feature: ScatteredOrbs][Material: Diamond Ore][Feature: ScatteredOrbs][Material: Glowstone][Feature: HugeOrbs][Material: Block of Coal][Feature: Tendrils][Effect: None][Effect: NoGravity][Effect: DigSlowDown3][Terrain: Void][Biome: The Void][Sky: Purple clouds][Sky: Black][Sky: Purple fog][Sky: Stars1]

RFTools 1.12-6.13
RFTools Control 1.12-1.6.8
RFTools Dimensions 1.12-5.04
mcjtylib-1.12-2.4.4
Forge 14.21.1.2443

[crash.2017-09-09.rfdim.txt](https://github.com/McJty/RFToolsDimensions/files/1289702/crash.2017-09-09.rfdim.txt)

Just after reading the logs I've realized I had only 1 GB of memory allocated (how it ran before anyway?..), switched it to 6 GB, but the crashing still persisted.

Will be patiently waiting for the bugfix. In the meantime, I'm going to try and create a similar dimension using other kinds of orbs, although the time spent on realizing this monstrousity means another few days AFK. Oh well. These are wonderful mods by the way, thank you so very much.

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
Fixed next release
