### ISSUE TITLE
issue with opening manual trough dimensional inscriber.

### ISSUE THREAD

**Issue by CenTdemeern1** [McJty/RFToolsDimensions#118]
I'll tell the story quickly:

I wanted more information about how the dimensional inscriber did things with dimlets (how it uses them).
So I opened the dimensional inscriber; clicked the button at the right hand side.

\>**CHRASH!**<

It closed the world. IT EVEN SAID "**SHUTTING DOWN INTERNAL SERVER**".
I got freaked out!
I have just restarted my game. No more problems at all.

**NOTE:** After restarting game I tried it again, again a chrash...

Try it youself if you want. Nothing bad happens, just a chash. I just wanted to report this.

That was about it. help getting it fixed!!

P.S. I play FTB Presents SF3 (Feed The Beast Presents Sky Factory 3). That can have to deal with it too...

**Comment by McJty** [comment]
What version of RFTools dimensions? Also I need a crashlog

**Comment by nosfiratys** [comment]
I think I have same problem.
Game version 1.10.2
Description of problem:
When I try to open ingame "dimension manual book" (by right click on book or click on button in any of RFToolsDimension Machine) then i get message about shutting down server (not sure how it named in english - i get it in russian). Then game has crashed without any messages
rftoolsdim-1.1x-5.02
rftoolsctrl-1.1x-1.6.8
rftools-1.1x-6.01
mcjtylib-1.10-2.3.11

Where I can find log you needed?

**Comment by CenTdemeern1** [comment]
wait, I'm booting up SF3. (a thought came up: I am booting it up to crash it :) )

EDIT: I found the old log.

**Comment by CenTdemeern1** [comment]
I know where to find that log

**Comment by CenTdemeern1** [comment]
oh

**Comment by CenTdemeern1** [comment]
whoops

**Comment by CenTdemeern1** [comment]
[2017-07-18-1.zip](https://github.com/McJty/RFToolsDimensions/files/1231146/2017-07-18-1.zip)

**Comment by McJty** [comment]
I think I fixed an issue with this for next release
