### ISSUE TITLE
crash when leaving a rf tools dim(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [McJty/RFToolsDimensions#121]
Forge:1.12-2410
RF dim: rftoolsdim-1.12-5.02
RF tools: rftools-1.12-6.10beta4

Crash report:
[crash-2017-07-14_20.16.39-server.txt](https://github.com/McJty/RFToolsDimensions/files/1148542/crash-2017-07-14_20.16.39-server.txt)

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Oh, but this is already fixed in latest version
