### ISSUE TITLE
[1.12.2] Ticking block entity server crash when attempting to create a specific dimension

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsDimensions#122]
https://pastebin.com/BdSfbciR

Effect None, Feature None, Weather Default, Time Noon, Material Glass, Liquid Water, Terrain Flat, Mob Default, Structure None, Biome Forest, Controller Single.

I tried making this dimension and I got the above crash, twice. When I got back into the game, the dimension tab said 'dimension info missing' in red. I removed Biome Forest and Controller Single and the dimension was made successfully.

**Comment by McJty** [comment]
I will fix this

**Comment by ghost** [comment]
Love your mods. I just don't know if this particular crash is an artifact of a specific server config or if it's repeatable with just rftools.

**Comment by McJty** [comment]
Nah, I'm guessing you are on a server?

**Comment by ghost** [comment]
Yes, the GrimDarker pack on curse.

**Comment by McJty** [comment]
This is a case of something working fine singleplayer but not on a server. I'm already fixing it right now

**Comment by McJty** [comment]
Fixed in 5.03 which will be released shortly

**Comment by ghost** [comment]
You are amazing.
