### ISSUE TITLE
Dimensions don't load on server startup?

### ISSUE THREAD

**Issue by thiakil** [McJty/RFToolsDimensions#126]
When testing Chunkloading issues on 1.11 I noticed that when an RFTools dimension is chunkloaded, it won't work after server startup until someone goes to that dimension.

Do you call `net.minecraftforge.common.DimensionManager.initDimension` anywhere? This might solve it (causing it to load at least once so that the ForcedChunks event/handling can fire, and leaving it to unload shortly after)

**Comment by McJty** [comment]
I don't think it is up to rftools dimensions to call that. That method should be called the first time a dimension needs to be loaded. The chunkloader should do that

**Comment by thiakil** [comment]
The chunkloader is not loaded until the dimension is loaded, neither are the Forge forced chunks

**Comment by McJty** [comment]
That's true for chunkloaders that are in chunks that are unloaded at startup (i.e. far away from where the player is when he loads the world). Chunkloaders should not depend on chunks/worlds being loaded to work. They should keep that information independent from their TE

**Comment by thiakil** [comment]
They do store it separately, that's half the point of the Forced Chunks system. The issue is that *Forge does not load the forced list (for that world) until the world is loaded*

**Comment by McJty** [comment]
Well it should not be stored per world but globally. In a SaveData structure that is not associated to a particular world. I do that a lot in many of my mods

**Comment by thiakil** [comment]
You would need to suggest that to Lex, I'd imagine. Otherwise you're essentially saying modders should add *a separate system of their own*, just to get the Forge chunkloading to work in your dimensions.

**Comment by McJty** [comment]
What forge system are you talking about exactly?

**Comment by thiakil** [comment]
`net.minecraftforge.common.ForgeChunkManager`

**Comment by McJty** [comment]
Yes, seems that way then. RFTools Dimensions is not the place for it at least. It is a chunk loading issue which means it has to go to the chunk loading mod

**Comment by thiakil** [comment]
It's only an issue because you don't load your dimensions on startup like the vanilla ones do

**Comment by thiakil** [comment]
> RFTools Dimensions is not the place for it at least

Could you at least explain why you think that?

**Comment by McJty** [comment]
Well if chunk loaders have a problem it should be solved on their side. This mod is not about chunk loading

**Comment by thiakil** [comment]
Chunkloaders load chunks, not dimensions too.

You do realise specifically loading a dimension is not required for vanilla dimensions' chunkloading, right?

**Comment by thiakil** [comment]
Looking further into it, MC/Forge appears to load all registered dimensions during server load. Your dimensions however don't because you need to wait for the overworld to load to get your data and only register them after the server has started.

So, chunkloading on start doesn't work because you register them too late for normal paths to load it.

See `net.minecraft.server.MinecraftServer#loadAllWorlds`

Please discuss with Forge if you still believe someone else should make your mod work with a standard Forge feature.

**Comment by McJty** [comment]
I don't know. I'm a bit worried about just calling that function for my dimensions as I'm not sure what other consequences it has and I still feel that this is better solved on the side of the thing that actually needs it (chunk loader). RFTools Dimensions doesn't need that init call as it is done (as it should) the first time the dimension is needed. Calling these for all rftools dimensions at startup might also slightly increase startup time

**Comment by thiakil** [comment]
So I just found this in 1.12 code (`ForgeChunkManager`). So yeah its your problem.

```
/**
     * Allows dynamically loading world mods to test if there are chunk tickets in the world
     * Mods that add dynamically generated worlds (like Mystcraft) should call this method
     * to determine if the world should be loaded during server starting.
     *
     * @param chunkDir The chunk directory to test: should be equivalent to {@link WorldServer#getChunkSaveLocation()}
     * @return if there are tickets outstanding for this world or not
     */
    public static boolean savedWorldHasForcedChunkTickets(File chunkDir)
```

**Comment by McJty** [comment]
Ok .I was not aware of this. I'll check it out

**Comment by McJty** [comment]
Hmm not sure when to test for this and how to actually load the dimension then?

**Comment by thiakil** [comment]
I've done it this way in one of my mods (in a `FMLServerStartedEvent` event handler)

```
File worldFolder = DimensionManager.getCurrentSaveRootDirectory();
for( final Integer storageCellDimID : this.storageCellDimensionIDs )
{
	if ( ForgeChunkManager.savedWorldHasForcedChunkTickets( new File(worldFolder, DimensionManager.createProviderFor( storageCellDimID ).getSaveFolder()) )){
		DimensionManager.initDimension( storageCellDimID );
	}
}
```

**Comment by josephcsible** [comment]
It looks like ChickenChunks takes care of this itself:
```
Thread [Server thread] (Suspended (breakpoint at line 194 in DimensionManager))	
	DimensionManager.setWorld(int, WorldServer, MinecraftServer) line: 194	
	WorldServerMulti(WorldServer).<init>(MinecraftServer, ISaveHandler, WorldInfo, int, Profiler) line: 130	
	WorldServerMulti.<init>(MinecraftServer, ISaveHandler, int, WorldServer, Profiler) line: 18	
	DimensionManager.initDimension(int) line: 244	
	DedicatedServer(MinecraftServer).getWorld(int) line: 914	
	ChunkLoaderManager.getWorld(int, boolean) line: 505	
	ChunkLoaderManager$PlayerOrganiser(ChunkLoaderManager$ChunkLoaderOrganiser).revive() line: 326	
	ChunkLoaderManager$PlayerOrganiser.revive() line: 390	
	ChunkLoaderManager.processLoaderStates() line: 693	
	ChunkLoaderManager.onTickEnd(WorldServer) line: 670	
	ChunkLoaderEventHandler.worldTick(TickEvent$WorldTickEvent) line: 32	
	ASMEventHandler_58_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(Event) line: not available	
	ASMEventHandler.invoke(Event) line: 90	
	EventBus.post(Event) line: 179	
	FMLCommonHandler.onPostWorldTick(World) line: 272	
	DedicatedServer(MinecraftServer).updateTimeLightAndEntities() line: 849	
	DedicatedServer.updateTimeLightAndEntities() line: 414	
	DedicatedServer(MinecraftServer).tick() line: 741	
	DedicatedServer(MinecraftServer).run() line: 590	
	Thread.run() line: 748	
```
@thiakil Is this still something that we need to add, or should other chunk loaders just do what it's doing?

**Comment by thiakil** [comment]
The point is that it *should not need to tick* to do this. The only reason it should need to tick is if it requires fuel to work.

Also ChickenChunks has a reputation amongst developers as being kinda dodgy, so I'm immediately sceptical anyway

**Comment by josephcsible** [comment]
Fair enough. I tested The Weirding Gadget, which doesn't do this, and it did need the fix.
