### ISSUE TITLE
1.12 Hitting the Ender Dragon with the Syringe crashes your game

### ISSUE THREAD

**Issue by RainerReinfall** [McJty/RFToolsDimensions#127]

**Comment by McJty** [comment]
Crashlog please

**Comment by RainerReinfall** [comment]
http://paste.feed-the-beast.com/view/9a821a0c

**Comment by RainerReinfall** [comment]
http://paste.feed-the-beast.com/view/9a821a0c


Von: McJty
Gesendet: Montag, 7. August 2017 19:11
An: McJty/RFToolsDimensions
Cc: RainerReinfall; Author
Betreff: Re: [McJty/RFToolsDimensions] 1.12 Hitting the Ender Dragon with theSyringe crashes your game (#127)

Crashlog please

**Comment by McJty** [comment]
This has been fixed some time ago in rftools
