### ISSUE TITLE
Can't Dial?

### ISSUE THREAD

**Issue by glazedginger** [McJty/RFToolsDimensions#128]
I Made a random dimension, my first one, and it's all fine. It has nothing useful, so I make another tab, enscribe it (random) and put it in the builder. The builder is instantaneously at 100 percent for some reason. I noticed that it already had as much power as was in the first one, and the Dialer would not recognize the dimension.

**Comment by McJty** [comment]
If you use the same dimlets ( that includes no dimlets) you get the same dimension.  Use digit dimlets
