### ISSUE TITLE
CmdSetOwner using wrong method for player name

### ISSUE THREAD

**Issue by bloodmc** [McJty/RFToolsDimensions#129]
https://github.com/McJty/RFToolsDimensions/blob/1.12/src/main/java/mcjty/rftoolsdim/commands/CmdSetOwner.java#L72

This should be getName. However, it is more efficient to check the UUID since names can change. You can simply check if sender is a player then check for a matching UUID in the player list.

**Comment by McJty** [comment]
I will change it to GetName() but I cannot use UUID because it is a command parameter. It is annoying for the admin to have to use a UUID instead of a name
