### ISSUE TITLE
[1.9] Server crash entering RF dimensions

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFToolsDimensions#13]
Crash Report: http://pastebin.com/raw/aR2uN0E5

Forge: 1907
Mods: rftools-1.9.0-4.48.jar
rftoolsdim-1.9.0-4.23beta38.jar

Server crashed when use entered an RF-powered dimension

**Comment by RealGrep** [comment]
Still present in 1.9.4, in some form, I think. As soon as I teleported to a new dimension, poof, server crashed.

http://pastebin.com/ttjXTDmA

With rftoolsdim-1.9.4-4.23beta41.jar, rftools-1.9.4-4.51.jar, mcjtylib-1.9.4-1.8.7.jar, ElecCore-1.9.4-1.5.292.jar, forge-1.9.4-12.17.0.1957-universal.jar on MC 1.9.4.

**Comment by McJty** [comment]
Might be fixed next release. It is a blind fix though as I can't really reproduce it
