### ISSUE TITLE
RFTools dimension + Thermal foundation crash

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsDimensions#131]
My game crashes  if i run, fall or aim too fast at a connector on a Hardened Fluiduct. If im not careful with a wrench and hardened Fluiduct i can crash my game. Its really annoying because im doing a project with a LOT of them, and it gets really tedious crashing over and over. This only happens in my void dimension i made, not the overworld at all (I tried to crash it in the OW the best i could lol)

tl;dr help

**Comment by ghost** [comment]
Heres the crash report: https://pastebin.com/R8RPkrLv
and
Heres the forge log: http://www.filedropper.com/latest
(Too much text for pastebin, so i put the txt in filedropper)

**Comment by McJty** [comment]
Report to the COFH team. Seems to be on their side
