### ISSUE TITLE
Ender Dragon RFToolsDimensions problem.

### ISSUE THREAD

**Issue by JarlWolfe** [McJty/RFToolsDimensions#133]
Trying to create a mob dimlet for an Ender Dragon dimension. I have all the necessary components (base part, rarity 6 control circuit, advanced energy module, advanced memory unit, mob type controller, Syringe of 100% Ender Dragon essence) but nothing appears in the output box of the workbench. I am concerned it's something to do with the syringe of essence.. but I can't be certain.

**Comment by mrdeadlocked** [comment]
I'm having this same issue.

![image](https://user-images.githubusercontent.com/461352/31363692-1e8b54f6-ad2e-11e7-91a4-b78112f89e6b.png)

![image](https://user-images.githubusercontent.com/461352/31363699-2bdf1548-ad2e-11e7-91a7-60aa2b882c5c.png)

**Comment by McJty** [comment]
Versions?

**Comment by mrdeadlocked** [comment]
rftools-1.12-7.00alpha1.jar
rftoolsctrl-1.12-1.6.8.jar
rftoolsdim-1.12-5.05.jar

Sorry about that. I wasnt thinking. :-) Its the ALL THE MODS 3 4.1 modpack.

**Comment by McJty** [comment]
What? Is all the mods using the alpha of rftools? Now that's a bad idea...

**Comment by tluc0411** [comment]
any fix to this

**Comment by scotty9090** [comment]
I have this same issue in All The Mods 3 (1.12.2).  RFTools versions:

RFTools: 1.12-7.23
RFTDim: 1.12-5.50
McJtyLib: 1.12-2.6.2

**Comment by josephcsible** [comment]
@scotty9090 I can't reproduce this in a clean instance with those versions. (I tried with Forge 2587, which I assume is what you're on.) Can you see if you can do so? If not, can you try to identify what other mod in the pack is triggering this bug?

@JarlWolfe @mrdeadlocked @tluc0411 Can any of you do the same?

**Comment by josephcsible** [comment]
Update: I discovered that this is ATM3's fault: AllTheMods/ATM-3#319. I assume that all of you having this problem are on ATM3. If it happens to you in a different pack, please open a new issue about it.

**Comment by josephcsible** [comment]
If you are on ATM3, as a workaround, change `I:maxMobInjections` from 64 to 10 in `config/rftools/dimensions.cfg`.
