### ISSUE TITLE
Material Absorber - Block of Enderpearl

### ISSUE THREAD

**Issue by ZeroInputCtrl** [McJty/RFToolsDimensions#134]
MC 1.12.1
RFT Dimensions 5.05
Actually Additions r119

The material absorber is not absorbing the block of enderpearl from the Actually Additions mod.

**Comment by McJty** [comment]
That's normal. Materials/blocks have to be specifically enabled in the rftools dimensions config before you can use them as a dimlet. See https://wiki.mcjty.eu/mods/index.php/RFTools_Dimensions for more info

**Comment by ZeroInputCtrl** [comment]
ic, i'll mess with that, thanks
