### ISSUE TITLE
Machines that would effect time and weather break in rftools dimens.

### ISSUE THREAD

**Issue by tyler489** [McJty/RFToolsDimensions#136]
So the server im playing on has everyone in there own empty void world so they can be force unloaded of they cause lag. Anway using draconic evos celestial manipulartor to change time or weather results in the time snaping back to where it was same with weather. Thinking this was an issue with draconic evo i tried using forestry to stop rain and that didnt work either.  I also tried evilcrafts weather manipulator and it also has no effect. The dimention is a normal dimention. In 1.12 void terrain normal weather and daylight cycles.

**Comment by tyler489** [comment]
Simular to #104  but also with weather

**Comment by McJty** [comment]
RFTools Dimensions can use their own weather plus time control (when they differ from the overworld). Other machines cannot affect that.
