### ISSUE TITLE
Chunk loading fails after the game restarts

### ISSUE THREAD

**Issue by paul-soporan** [McJty/RFToolsDimensions#137]
Note: This is more of a request than an issue.
Sorry for my bad english. I am Romanian.
Hi MCJty! Today I had a problem in my world. I recently moved my base into another dimension created by rft dimensions. I moved there my huge refined storage system too. Every time I close my game when I am in the overworld and I relog back , my network receiver from the overworld is offline. If I go to that dim. and come back into the overworld the storage system goes online. By the way, that dimension is chunkloaded with ftb utils and extra utils 2. With my vanilla knowledge I believe that this is happening because when the game restarts it only loads the spawn chunks from the overworld for about 1 minute. Other dimensions like the nether aren't loaded by the game so even if u chunkload them you need to visit them once for them to be loaded. In vanilla I used to solve this problem by shooting an item into a portal every 14 seconds so they don't unload without a player. The problem is that I don't think I can do this in rftools dimensions. So when u have time please look into the code and tell me if I am right. If I am, I would like to see that u implement a command that can select a dimension to be ticked by the game after every restart for a brief second(enough to get the chunkloading working). The syntax would be something like this:"/tick **"dimension id"** **"number of ticks"**". I would like to have this on 1.10.2. Thanks for reading this.
Hope you will find a good solution! There are chances that I am wrong.
Have a good day!
Paul Soporan

**Comment by paul-soporan** [comment]
I had this issue again a few days ago. I created a flat quartz dimension and teleported to it. When i tried to get my fortune drill(from actually additions) from my diamond backpack(from iron backpacks) to mine the quartz, my game crashed. I lost the crash report, but that doesn't matter. When i restarted the game the dimension collapsed because the dimension where i have the dim builder and the power storage didn't load. I was lucky because i had draconic armor and a teleporter in my hand. Like I said before the dimension where my base is is chunk-loaded with ftb-utils and extra utils.
Please try to solve this issue.
Have a good day!
Paul Soporan

**Comment by McJty** [comment]
That's a bug in ftb utils and not Rftools dimensions
