### ISSUE TITLE
Dimlet Config completly regenerated each start, removing user dimlets.

### ISSUE THREAD

**Issue by brisingraerowing** [McJty/RFToolsDimensions#139]
I placed two user dimlet configs to the dimlets.json file as specified on the [wiki](https://wiki.mcjty.eu/mods/index.php/RFTools_Dimensions), but those were removed on the next start of MC.

This is in 1.12.2.
RFT DIm 5.05

**Comment by McJty** [comment]
Then you did something wrong with:
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

Can you show me the config how you modified it?

**Comment by brisingraerowing** [comment]
Here's a quick example of what I did.

```json
[
  {
    "filter": {
      "mod":"bigreactors",
      "name":"bigreactors:brore",
      "type":"material"
    },
    "settings":{
      "rarity": 1,
      "create": 10,
      "maintain": 1,
      "ticks": 20,
      "worldgen": true,
      "dimlet": true
    }
  },
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
  {
    "filter": {
      "name": "owner",
      "type": "special"
    },
    "settings": {
      "rarity": 0,
      "create": 0,
      "maintain": 0,
      "ticks": 0,
      "worldgen": false,
      "dimlet": true
    }
  },
...
]
```

**Comment by McJty** [comment]
Hmm are you really sure it is exactly like that when it was removed? Can you try again?

**Comment by brisingraerowing** [comment]
That's how I did it. I'm loading MC again, so we'll see what happens.

I have a big modlist so it takes forever.

**Comment by brisingraerowing** [comment]
It wasn't removed this time. Might have been a one-off quirk.

The dimlet still doesn't show up in the Dimlet Workbench, though.

**Comment by McJty** [comment]
Is this correct? bigreactors:brore
I never heard of that material. What it is supposed to be?

**Comment by McJty** [comment]
nm. It is the ore

**Comment by McJty** [comment]
You changed that both server and client side (if there is a server involved)?
For what are you looking exactly in the workbench?

**Comment by brisingraerowing** [comment]
I'm in singleplayer. I have tried tying the first few letters (Yellor), but the only thing that comes up with that is a yellorium fluid dimlet (that is bizarrely unlocalized). Typing bigreact gives two unlocalized fluid dimlets (Yellorium and Cyanite). I tried using material as the search and looking through, but found nothing.

**Comment by brisingraerowing** [comment]
I managed to figure this out. Including the mod ID in the name field breaks the entry. Removing it causes the dimlet to appear.
