### ISSUE TITLE
[1.9.4] rftoolsdimensions dimlet workbench and liquid absorber issue

### ISSUE THREAD

**Issue by unknownname** [McJty/RFToolsDimensions#14]
When I am trying to create the spefic liquid dimlet such as lava. Workbench does not seems combine the basic dimlets to lava liquid dimlet. It issue happens with all the costume liquid dimlets.
Eample: To create a lava dimelet : The following base dimlet required: base dimlet part, circuit rarity 5,advanced energy module, advanced memory unit, liquid controller and liquid absorber with lava. Once we provdided all the basic parts we shall be getting the "lava liquid dimlet". Attaching the screenshot.

2nd issue:Liquid absorber: This is only teseted with Rocket fuel from Ender IO
When we place the rocket fuel beside the liquid absorber, it get absorbe but NBT data infuse stuck at value 0 and absorbering is stuck at value 1. You can place as many bukets of rocket fuel but NBT values does not change. I am not this is caused by Forge code or  RFdimension code.

Adding: NBT value in absorber of infuse liquid is stuck at 0. The value is not chaning. 

Forge Version: 12.17.0.1954
Rf tools: 1.9.4-4.50
RF dimesions:1.9.4-4.23beta40

![rftools](https://cloud.githubusercontent.com/assets/3933039/15980851/a23a1d58-2f3c-11e6-885b-5cc1bdbb5c43.jpg)

**Comment by McJty** [comment]
Was the lava liquid absorber filled to 100%? i.e. how much lava did you give it?

Note that the liquid has to go below the absorber

**Comment by unknownname** [comment]
Yes liquid absorber was filled to 100%. As per the config it is 128 buket:

Made a vidoe of absorbing the lava and rocket fuel. Lava get absorb properly to 100 as per tool tip but after the mining the liquid absorber block, it changes its tool tip.
For rocket fuel, fuel block get absorb but tool tip is not updating. after mining rocket fuel liquid absorber, it changes it nbt data to air. Then liquid absorber does not absorb any rocket fuel more. 

Youtube video link:https://www.youtube.com/watch?v=vi3C6_G16AI

**Comment by McJty** [comment]
I cannot reproduce this... Weird

**Comment by unknownname** [comment]
I will see if i can reproduce this bug in brand new world again. May be this issue occurred because of porting the saved world from 1.8 to 19.4. I will keep you posted. Sorry for late response

**Comment by McJty** [comment]
Fixed next release
