### ISSUE TITLE
[1.10.2] Many common ores from different mods not available/craftable as dimlets

### ISSUE THREAD

**Issue by Jadziyah** [McJty/RFToolsDimensions#141]
An odd problem has arisen- we're trying to make an ore materials dimlet. Nickel, to be exact. But the workbench seems to only offer ores of certain mods: Vanilla, BoP, Tinkers, AE. For some reason the ores in Immersive Engineering, Mekanism, Forestry, Railcraft, and Thermal Foundation simply don't show up as options to build in the Workbench. Why might this be happening? Is this a CoFH issue? Here is a screenshot looking for nickel: https://gyazo.com/e49fba9b1b85b00e84a689494d0dd31c Even though they're not in there I tried putting an Absorber over the ores but it didn't collect them. Here's a ss with the versions of the mods we're running: https://gyazo.com/03e453e4d2add3d40b7e92f1a2d13032 This is on 1.10.2. Nickel is just an example, none of the ores from the previously mentioned mods are available. Neither are the liquids in those mods, as a matter of fact

We also tested this in single player, with just RFDims and Thermal Foundation, and found the ores to still be not available. Any ideas?

**Comment by McJty** [comment]
RFTools Dimensions does not by default add all materials (like it used to in 1.7.10). Materials have to be specifically added to the config:

https://wiki.mcjty.eu/mods/index.php/RFTools_Dimensions

**Comment by Jadziyah** [comment]
Thanks. I've read through the page. We have not previously done any custom modifications to this config. Would these commands be correct? - 

To add all of the above ores/liquids of the previously mentioned mods in one sweep, instead of doing a line for each item... : 

`{
    "filter": {
      "mod": "forestry",
      "type": "material"
    },
    "settings": {
      "worldgen": true,
      "dimlet": true
    }
  },
{
    "filter": {
      "mod": "thermalfoundation",
      "type": "liquid"
    },
    "settings": {
      "worldgen": true,
      "dimlet": true
    }
  },
`
etc? All above the marker line, of course

**Comment by insectdude1258** [comment]
McJty, your linked page about the mod is no longer available.  Is this information still available somewhere?

**Comment by McJty** [comment]
https://wiki.mcjty.eu/mods/index.php?title=RFTools_Dimensions

**Comment by insectdude1258** [comment]
Thank you for the fast response McJty.  Much appreciated.  Keep up the good work.  Have a great xmas.

**Comment by josephcsible** [comment]
@Jadziyah Do those instructions solve this?
