### ISSUE TITLE
Server Crash - Sponge - 1.9.4-4.30beta43

### ISSUE THREAD

**Issue by yepidoodles** [McJty/RFToolsDimensions#15]
Just going to leave this here....

http://www.codesend.com/view/00ba9f787230a18a3a748f6e25e9ec5d/
- Alice
  DragonTechMC

**Comment by tenten8401** [comment]
This is completely unrelated, but if you used something like http://hastebin.com, it would be 100% easier to read.

**Comment by McJty** [comment]
Don't use 1.9.4. It is very easy to migrate to 1.10.2
