### ISSUE TITLE
1.12: Activity Probe not working when dimension has loaded chunks

### ISSUE THREAD

**Issue by ctembreull** [McJty/RFToolsDimensions#154]
Pack: Direwolf20 v1.4.0
FTB Utilities: v4.2.4
RFTools Dimensions: v1.12-5.05

I created a dimension with liquid uranium, which carries a high power cost. I constructed the dimension, powered it, and placed an Activity Probe in it. At this point, the dimension correctly did not draw power when I was not in it.

I then created a Builder setup to pump the uranium, and chunkloaded it so that it would run remotely. The dimension now consumes power, despite the Activity Probe and despite the fact that I am not in it.

Pretty sure this is a bug, but it may be more the fault of the FTB Utilities chunkloader, which has had significant issues recently.

I can provide more information as requested.

**Comment by McJty** [comment]
Well if it is chunkloaded then it will consume power. That's the point. Even if you are not in it. As long as the dimension is in use (player or chunkloader) then it will consume power

**Comment by ctembreull** [comment]
It's cool if that's the design, but I'm pretty sure that that's a change from previous versions, based on your documentation:

https://github.com/McJty/RFTools/wiki/RFTools-Activity-Probe

> This device is passive. It doesn't use any power and it has no user interface either. You simply place it in an RFTools dimension (it has no effect in any other dimension). While it is present in a dimension it monitors activity in that dimension and it will shut down power consumption from that dimension when nobody is in the dimension (including chunk loaders). So this block is an effective way to make sure your dimension isn't using power needlessly.

Is this behavior configurable?

**Comment by McJty** [comment]
It has always worked like that and the documentation you just pasted talks about chunk loaders too. And no this is not configurable. Both chunk loaders and players have the effect that the dimension has to be loaded and it is the fact that the dimension is loaded that causes the power consumption.
