### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by josephcsible** [McJty/RFToolsDimensions#158]
When in a Lost Cities dimension, you get tons of messages like these:
`[17:09:03] [Server thread/WARN] [FML]: RFTools Dimensions loaded a new chunk (-12, 10  Dimension: 3) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`

For reference: [Investigating extreme Worldgen lag](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/)

**Comment by McJty** [comment]
Note that this is not always caused by mods. Vanilla itself has cascading worldgen lag in (for example) emerald ore generation

**Comment by McJty** [comment]
The only way to know is to set a breakpoint in forge where that warning is given and checking what generator is doing it

**Comment by josephcsible** [comment]
It looks like it's mainly coming from createVineStrip and createRandomFeature. The problem is that you're causing block updates, and you're setting blocks that are right on the chunk border, so it has to load neighboring chunks to do the updates. I'm going to try making that generation not do block updates to see if it fixes it.

**Comment by josephcsible** [comment]
Okay, that seems to take care of the common ones, but I got one that doesn't seem as straightforward:
```
Thread [Server thread] (Suspended (breakpoint at line 1636 in Chunk))	
	Chunk.logCascadingWorldGeneration() line: 1636	
	Chunk.populate(IChunkGenerator) line: 1078	
	Chunk.populate(IChunkProvider, IChunkGenerator) line: 1052	
	ChunkProviderServer.provideChunk(int, int) line: 169	
	WorldServerMulti(World).getChunkFromChunkCoords(int, int) line: 361	
	WorldServerMulti(World).getChunkFromBlockCoords(BlockPos) line: 353	
	WorldServerMulti(World).getBlockState(BlockPos) line: 994	
	WorldServerMulti(World).updateComparatorOutputLevel(BlockPos, Block) line: 4164	
	ModularStorageTileEntity(TileEntity).markDirty() line: 178	
	InventoryHelper.setInventorySlotContents(int, int, ItemStack) line: 482	
	ModularStorageTileEntity.setInventorySlotContentsHelper(int, int, ItemStack) line: 404	
	ModularStorageTileEntity.setInventorySlotContents(int, ItemStack) line: 424	
	GenericWorldGenerator.createModularStorage(Random, World, BlockPos) line: 320	
	GenericWorldGenerator.createRandomFeature(Random, World, BlockPos) line: 295	
	GenericWorldGenerator.generateLootSpawners(Random, int, int, World) line: 215	
	GenericWorldGenerator.generate(Random, int, int, World, IChunkGenerator, IChunkProvider) line: 107	
	GameRegistry.generateWorld(int, int, World, IChunkGenerator, IChunkProvider) line: 167	
	Chunk.populate(IChunkGenerator) line: 1091	
	Chunk.populate(IChunkProvider, IChunkGenerator) line: 1052	
	ChunkProviderServer.provideChunk(int, int) line: 169	
	PlayerChunkMapEntry.providePlayerChunk(boolean) line: 130	
	PlayerChunkMap.tick() line: 183	
	WorldServerMulti(WorldServer).tick() line: 236	
	IntegratedServer(MinecraftServer).updateTimeLightAndEntities() line: 829	
	IntegratedServer(MinecraftServer).tick() line: 741	
	IntegratedServer.tick() line: 192	
	IntegratedServer(MinecraftServer).run() line: 590	
	Thread.run() line: 748	
```
Would it be feasible to change Lost Cities generation to generate things offset by 8 blocks, rather than in entire chunks? That seems like a better option than this cat-and-mouse game.

**Comment by McJty** [comment]
As far as I know Lost Cities already does that. I have gone through all of this in Lost Cities and it has a complete system for this. Or do you mean the Lost Cities dimension type that is in RFTools Dimensions?

**Comment by josephcsible** [comment]
I do mean the Lost Cities dimension type that is in RFTools Dimensions. By the way, why does RFTools Dimensions even still implement that itself? Why not just make the Lost Cities mod a requirement for Lost Cities world, and piggyback off of its generation rather than maintaining the code in two places?

**Comment by McJty** [comment]
Well I no longer maintain the rftools dimension version and it is there mostly for compatibility for people that are already using such a world. The rftools dimension version is HUGELY different now from the standalone version
