### ISSUE TITLE
[1.10][4.30b44]Dimlets.json appears to revert itself on server restart

### ISSUE THREAD

**Issue by Rosethorns** [McJty/RFToolsDimensions#16]
The Dimlets.json appears to regenerate default every time the server instance is restarted, any changes introduced are wiped.

**Comment by McJty** [comment]
You have to put your own configs before the line:
Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that

**Comment by rishenko** [comment]
Hello and apologies for necrothreading. I am encountering this same issue, both on the server, and on my local instance. I have tried both adding my changes before the line, and removing that line and adding my changes in its place. In both cases, the file reverts back to its default settings.

RFTools: 1.1x-5.84
RFTools Dimensions: 1.1x-4.54
