### ISSUE TITLE
RfToolsDimensionManager shouldn't be shared

### ISSUE THREAD

**Issue by josephcsible** [McJty/RFToolsDimensions#165]
The fact that the same instance of RfToolsDimensionManager is used by both client and server threads causes all sorts of weird bugs. This should be changed.

**Comment by McJty** [comment]
How so? What kind of bugs?

**Comment by josephcsible** [comment]
#159 working the first time in single player is one. Another is that the same thing happens with mob dimlets, except it works right all the time with a dedicated server.
