### ISSUE TITLE
[1.9.4-4.30beta44] "Invalid Transmitter!!"

### ISSUE THREAD

**Issue by Tailsdeveraux** [McJty/RFToolsDimensions#17]
When generating a dimension, and attempting to leave via the typical dialer+matter transmitter+matter receiver combination, the matter transmitter, after placed in the new dimension, cannot dial out. The dialer simply replies with "Invalid Transmitter!!"

RFTools 1.9.4-4.67
RFTools Dimensions 1.9.4-4.30beta44
Forge 1976, running SMP

This is what it looks like dialing from the overworld. Everything's nice and peachy.
![overworld dialing](https://cloud.githubusercontent.com/assets/20362953/16702699/c7d32a8c-4535-11e6-9352-041bfb77dc38.png)

And this is what it looks like if you try to get back...
![invalid transmitter](https://cloud.githubusercontent.com/assets/20362953/16702728/0173c030-4536-11e6-8bbe-4e2bacaa3438.png)

**Comment by McJty** [comment]
Please upgrade to 1.10.2. I'm not supporting 1.9.4 anymore since upgrading to 1.10.2 is so very easy
