### ISSUE TITLE
Game crashes on start up

### ISSUE THREAD

**Issue by Zilvynrae** [McJty/RFToolsDimensions#178]
[crash-2018-01-03_15.43.58-client.txt](https://github.com/McJty/RFToolsDimensions/files/1601933/crash-2018-01-03_15.43.58-client.txt)
[crash-2018-01-03_15.37.23-client.txt](https://github.com/McJty/RFToolsDimensions/files/1601934/crash-2018-01-03_15.37.23-client.txt)
[crash-2018-01-03_15.30.28-client.txt](https://github.com/McJty/RFToolsDimensions/files/1601935/crash-2018-01-03_15.30.28-client.txt)
[crash-2018-01-02_23.05.23-client.txt](https://github.com/McJty/RFToolsDimensions/files/1601936/crash-2018-01-02_23.05.23-client.txt)

Gmae crashes on launch, noticed this yesterday after updating your mods and a few others. I tried downgrading RFTools dimensions to the previous version that i already had installed but still crashes on startup. I also updated the thermal mods
natura
Immersive engineering, ae2, and extra cells 2. though the game still crashes after disabling those so i can't narrow down what is causing the conflict. 
[full mod list.txt](https://github.com/McJty/RFToolsDimensions/files/1601964/full.mod.list.txt)

**Comment by josephcsible** [comment]
Update RFTools Dimensions. You're using a too new version of McJtyLib for the one you have now.

**Comment by Zilvynrae** [comment]
I thought I had already tried that but i downloaded the most recent one and tried again and it didn't crash. Thanks
