### ISSUE TITLE
MC 1.10, 4.30-beta45 Dimlet parcels stop giving rewards

### ISSUE THREAD

**Issue by NolanSyKinsley** [McJty/RFToolsDimensions#18]
I have encountered dimlet parcels stop giving rewards after opening about 4-6 of them, after a while I can open one more and get another reward, but after that opening multiple parcels gives no reward.

I am running ftb unstable and added the rftools dimensions addon, all configs are default except for disabling flat colored blocks worldgenning dimlets.

**Comment by McJty** [comment]
I can reproduce. Will fix today

**Comment by McJty** [comment]
Fixed for next release
