### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by Shahelion** [McJty/RFToolsDimensions#181]
https://hastebin.com/kabinuzuvu.sql

**Comment by josephcsible** [comment]
It looks like one of your other mods is adding a biome wrongly. Try ~~this debug build~~ and post the crash log that it gives you.

**Comment by Shahelion** [comment]
Oh hey, I think I might know where the problem is. https://hastebin.com/ayuzuniciy.sql

**Comment by josephcsible** [comment]
Indeed.
