### ISSUE TITLE
Can't craft eficciency dimlet part

### ISSUE THREAD

**Issue by luigge** [McJty/RFToolsDimensions#183]
Hello I'm playing rftoolsdim minecraft 1.10 but using the 1.11 version and I can't craft the part of the efficiency dimlet that you create with the eficciency 3 diamond pickaxe

**Comment by McJty** [comment]
Why not? More details please.  Also version number

**Comment by luigge** [comment]
the version is rftoolsdim-1.1x-5.05 (lastest 1.11 version) and the problem is, I try to create this dimlet part (don't know the name) that you create with the diamond pickaxe and the nether star, I put the items on the crafting table but the output item doesn't show. don't know if I explained right. either applied energistics crafting terminal, either tconstruct crafting table, either normal crafting table.

**Comment by McJty** [comment]
Show me the grid. Also is the pickaxe properly enchanted?

**Comment by luigge** [comment]
![normal crafting table](https://user-images.githubusercontent.com/35157185/34907739-3d919b62-f86a-11e7-9924-d96ba47af20b.png)
![tconstruct workbench](https://user-images.githubusercontent.com/35157185/34907740-3da92048-f86a-11e7-8ce0-8d4f291e4499.png)
![ae2 crafting terminal](https://user-images.githubusercontent.com/35157185/34907741-3dbedeb0-f86a-11e7-93d3-9b3d7ea3c624.png)
![efficience 3 diamond pickaxe](https://user-images.githubusercontent.com/35157185/34907742-3dd53ed0-f86a-11e7-91ba-446afb8ba5e8.png)

**Comment by luigge** [comment]
enchanted with efficience 3. has to be efficience 3 or higher? the not enought items show it has to be efficience 3

1: normal crafting table
2: TConstruct table
3: AE2 crafting terminal
4: showing the enchantment of the pickaxe

**Comment by McJty** [comment]
I will check it out

**Comment by luigge** [comment]
didn't tried the mediocre essence though

**Comment by luigge** [comment]
![image](https://user-images.githubusercontent.com/35157185/34907788-080299c8-f86b-11e7-8f87-daaa3a62fc44.png)
Don't work too

**Comment by luigge** [comment]
just to mention that I enchanted with the enchanting table from the mod enchanting plus. Don't know if has something to do with this mod??

**Comment by josephcsible** [comment]
The enchantment needs to be just Efficiency III. Higher levels won't work, and it can't have other enchantments. That said, the pickaxe in your screenshot looks fine. What version of Forge, CompatLayer, McJtyLib, RFTools, and EnchantingPlus? Can you try enchanting one with a regular enchanted book on an anvil, or via "/enchant @p 32 3" while holding the pickaxe? Can you try disabling all mods except for those ones?
