### ISSUE TITLE
Filtered dimlet don't work as expected

### ISSUE THREAD

**Issue by luigge** [McJty/RFToolsDimensions#184]
Hello this is another bug I found. the filtered dimlet don't work as expected, tried creating a flat world with the mesa biome and their variations (mesa plateu, mesa bryce etc) and the filtered dimlet but keeps creating a world with normal biomes like swampland, river, desert, roofed forest. 

mod version rftoolsdim-1.1x-5.05.jar
mine version 1.10.2

**Comment by josephcsible** [comment]
Already fixed in dev; the next release will contain the fix. Duplicate of McJty/RFTools#916
