### ISSUE TITLE
NPE in getDimensionManager. on singleplayer wold join

### ISSUE THREAD

**Issue by Keridos** [McJty/RFToolsDimensions#19]
https://paste.ee/p/da6LW

version 4.3.0_beta46
Forge: 12.18.1.2011 (1.10.2)

**Comment by mrandu** [comment]
Same here (exact same NPE)

happens on client and server,l both existing or new world

[crash-2016-07-31_00.52.21-server.txt](https://github.com/McJty/RFToolsDimensions/files/392112/crash-2016-07-31_00.52.21-server.txt)

version 4.3.0_beta46
Forge 12.18.1.2043 (1.10.2)

**Comment by mrandu** [comment]
found fix by @DoughnutDev from here: https://github.com/McJty/RFTools/issues/656
downgrade router reborn for now, 14b works

**Comment by McJty** [comment]
Has this been reported to router reborn? Not sure which mod is to blame but I can't see nothing wrong with what I'm doing there

**Comment by Keridos** [comment]
Reported it over there.

**Comment by tomevoll** [comment]
my fault, i had some leftover code for a test dimention, how that caused the crash im unsure, but thats the only change regarding worlds in 16b, i released a 17b just now that should fix the problem if the test code is to blame.
