### ISSUE TITLE
Sugestion [Auto Dimlet Extract]

### ISSUE THREAD

**Issue by CTH999** [McJty/RFToolsDimensions#191]
I think it would be cool if you could auto-extract the parts from the dimlet.

That being said, It's just a suggestion. (I just don't like 100,000,000 dimlets, and disassembling the by hand!

Thanks!

**Comment by josephcsible** [comment]
Isn't this already possible? Just check the Extract box and hopper them in from above.

**Comment by CTH999** [comment]
Sorry, Didn't see that. Hate it when that happens.
