### ISSUE TITLE
Redo of issue 39. Commented there, but it didn't reopen. Kind of new to this.

### ISSUE THREAD

**Issue by haddow777** [McJty/RFToolsDimensions#194]
This is a duplicate of the comment I left on [issue #39](https://github.com/McJty/RFToolsDimensions/issues/39)

Okay, so I know this is supposed to be fixed and I even saw the code that is supposed to reset the ender dragons activity phase when spawned, but ...

Mine is not working and is acting just like this issue. I have rebuilt my dimension several times and even got another syringe and rebuilt the dimlet. The only thing I might think is an issue is the workbench selected a rarity 5 card when the config says the enderdragon is a rarity 6. Direwolf20, in his vid ([Lets Play S9 E83](https://www.youtube.com/watch?v=_sgO8b-pD4U&index=83&list=PLaiPn4ewcbkGuWjVS_GS-LzWwOehCjRg6)) used a rarity 5 card without issue, so I'm not thinking it's a problem.

I am using the 1.8.0 of the Direwolf20 1.12.2 pack. It has the 5.51 version, which I'm pretty sure is the latest version of the rftools dimension mod.

Any ideas why this might not be working or more information you might need would great.

![2018-02-11_13 53 55](https://user-images.githubusercontent.com/2130853/36079920-6a4a836e-0f3d-11e8-81db-63a9a6e209f2.png)

**Comment by josephcsible** [comment]
I reopened that one.
