### ISSUE TITLE
Crash to Desktop when trying to use Manual

### ISSUE THREAD

**Issue by norahqueen** [McJty/RFToolsDimensions#199]
When opening the manual from a machine or on it's own it causes a game crash. Was working previously, only mod change since was installing Decocraft. Running FTB Revelations 1.3 with minor additions. 

I'll try and gt a clean crashlog of it tonight,

**Comment by josephcsible** [comment]
There's a known bug in McJtyLib versions older than 2.6.3 where if your game language isn't en-US, opening a manual in a language it hasn't been translated into will crash. If this describes your circumstances, updating McJtyLib will fix it. If not, then go ahead and post the crash log.
