### ISSUE TITLE
{4.30beta46} crashes dedicated Forge 1.10.2 build 2043 on startup

### ISSUE THREAD

**Issue by kreezxil** [McJty/RFToolsDimensions#20]
You said it was already reported here, but I didn't see it in either the open or closed sessions. Also, you don't have an "**issues**" link at CurseForge which is why people are posting the bug reports there. Any ETA on when the patch might be released? My mega pack is on hold for its next update because I have people using your dimensions.

Cheers and keep it up the great work!

P.S., I pledged you something I can afford, hope it helps.

crash report:
https://gist.github.com/2e6be37b134bb96e3fdcd3888bb3a51d

fml server latest:
https://gist.github.com/fd9c19265e0255d464066a640fa4bdfc

**Comment by McJty** [comment]
It is no longer here because the bug is fixed. It was not a bug in RFTools Dimensions but in Router Reborn. The latest version of that mod should fix this

**Comment by McJty** [comment]
Ah yes, and thanks for the pledge!

**Comment by kreezxil** [comment]
oh thank you, i just got that update installed.
