### ISSUE TITLE
Support for Tiny Progressions ores.

### ISSUE THREAD

**Issue by xxMattewxx** [McJty/RFToolsDimensions#203]
Tiny Progressions has an ender ore which doesn't seem to be generating in my dimensions. I've created 30 so far, mined each of them to the ground and still can't find that ore in any of them.
Is it supported so far? Sorry if that is in a FAQ or something.

**Comment by josephcsible** [comment]
Tiny Progressions [hardcodes their ores to only generate in the Overworld and the Nether](https://github.com/Kashdeya/Tiny-Progressions/blob/23c6a173d0df21bb3f498b4a4c334d12764c54e5/src/main/java/com/kashdeya/tinyprogressions/world/WorldGen.java#L20-L28). We can't do anything about it on our end. Open an issue about this on their tracker.
