### ISSUE TITLE
Crash upon generating new world

### ISSUE THREAD

**Issue by syntacticsplenda** [McJty/RFToolsDimensions#204]
Issue description: 
After generating a possibly arbitrary (14) number of dimensions, further dimensions could not be entered or crashed the game upon generation. This occurred using twice, once using Emerald Ore and another time with Diamond Ore dimlets, both times with a Solid Feature dimlet.

Steps to reproduce: 
Create a dimension tab with the Emerald Ore or Diamond Ore and Solid dimlets.
Place dimension tab in Dimension Builder.
Game might crash.

Versions:
* Minecraft: 1.10.2
* Forge: 1.10.2-12.18.3.2488
* CompatLayer (only if on Minecraft 1.10 or 1.11): 1.10-0.2.9
* McJtyLib: 1.1x-2.4.3
* RFTools: 1.1x-7.12
* RFTools Dimensions: 1.1x-5.05

Possibly incompatible mods: 
OptiFine
Relevant logs, if any: 
https://pastebin.com/ujU3wnEu

**Comment by josephcsible** [comment]
Here's the log with MCP names: https://gist.github.com/josephcsible/54fdab0586e5019a6ddfe3945b4f9c26

This looks like it's just a case of runaway cascading chunk generation. Possibly offending mods:
* Super Circuit Maker
* Pam's HarvestCraft
* Dense Ores

Try removing one of them at a time and see if the problem goes away.

**Comment by syntacticsplenda** [comment]
Hey, sorry for the late response. The problem was Dense Ores. I have a feeling the conflict occurs only when generating a dimension that has a dense ore equivalent. Either way removing Dense Ores solved the problem. Thanks!

**Comment by josephcsible** [comment]
You're welcome!
