### ISSUE TITLE
Difficulty moving overworld into RFT Dimension

### ISSUE THREAD

**Issue by UntoldForce** [McJty/RFToolsDimensions#211]
Issue description: I have a highly-developed overworld from a previous FTB 1.10.2 modpack (FTB Infinity Lite) and would like to bring it into a dimension in my FTB Beyond world. I successfully did this in older Minecraft versions with Mystcraft, and followed the directions to create the dimension here. Unfortunately, all of the blocks are replaced by blocks of other types which renders the city useless. As a test, I replaced the newer FTB Beyond overworld with the older FTB Infinity Lite overworld, and no block substitution occurred. Thank you in advance for your help. I would love to get this working again!

Steps to reproduce: 

(prior to starting, I loaded the old FTB Infinity Lite world file into my FTB Beyond world, so it would automatically remove data from old mods)
1. Created a RFTools dimension with all "default" dimlets.
2. Powered the dimension but did not load into it.
3. Stopped the server and replaced the RFTOOLS30 "region" folder with the "region" folder from my old FTB Infinity Lite install.
4. Restarted the server
5. Used the creative dimension probe to teleport into dimension 30
6. Many of the blocks had been replaced with other nonsensical blocks

Versions:
* Minecraft: 1.10.2
* Forge: 12.18.3.2422
* CompatLayer (only if on Minecraft 1.10 or 1.11): 0.2.9
* McJtyLib: 2.4.3
* RFTools: 6.13
* RFTools Dimensions: 5.04

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
Can you upload both the Infinity Lite and Beyond worlds so I can try this myself?

**Comment by UntoldForce** [comment]
The world files are several gigabytes each. What would be the best method to get them to you?

**Comment by josephcsible** [comment]
Google Drive?

**Comment by UntoldForce** [comment]
I have access to a FTP which I will upload them within the next day. There are additional mods besides the standard FTB Beyond pack. If you want a full list I can get that for you.

**Comment by josephcsible** [comment]
I do need the full mod list, including versions.

**Comment by UntoldForce** [comment]
Here's the complete list:

> LibLoader.jar
ActuallyAdditions-1.10.2-r105.jar
Advanced Machines-60.0.4.jar
Advanced Solar Panels-4.0.4.jar
AdvancedRocketry-1.10.2-1.4.0-10.jar
ae2stuff-0.6.0.9-mc1.10.2.jar
agricraft-2.0.0-0.10.0-a19.jar
AkashicTome-1.0-5.jar
AppleSkin-mc1.10.2-1.0.7.jar
appliedenergistics2-rv4-stable-1.jar
Aquaculture-1.10.2-1.4.1.4.jar
Architect-MC1.10.2-1.2.0.34.jar
ArchitectureCraft-1.7.3-mc1.10.2.jar
Aroma1997Core-1.9.4-1.1.1.2.jar
Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar
astralsorcery-1.4.5.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.13.jar
bdlib-1.12.4.24-mc1.10.2.jar
BedBugs-1.10.2-1.1.6.jar
BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
BetterThanBunnies-1.10.2-1.1.0.jar
BiblioCraft[v2.2.5][MC1.10.2].jar
BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar
BloodArsenal-1.10.2-2.1.0-22.jar
BloodMagic-1.10.2-2.1.11-80.jar
Bookshelf-1.10.2-1.4.4.347.jar
Botania r1.9-341.jar
BrandonsCore-1.10.2-2.1.11.127-universal.jar
Ceramics-1.10.2-1.1.6b.jar
Chameleon-1.10.2-2.3.0.jar
ChatFlow-1.2-5.jar
ChestTransporter-1.10.2-2.5.18.jar
Chisel-MC1.10.2-0.0.13.30.jar
chiselsandbits-12.12.jar
Clipboard-1.10.2-1.1.1.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
CoFHCore-1.10.2-4.1.11.16-universal.jar
CompactSolars-1.10.2-5.0.12.336-universal.jar
compatlayer-1.10-0.2.9.jar
Controlling-1.0.5.jar
CookingForBlockheads_1.10.2-4.2.45.jar
CosmeticArmorReworked-1.10.2-v2a.jar
CraftingCraft_1.10.2-4.1.9.jar
CraftingTweaks_1.10.2-6.1.16.jar
CraftTweaker-1.10.2-3.0.26.jar
creeperhost-1.10.2-1.3.2.jar
CTM-MC1.10.2-0.2.2.24.jar
CustomMainMenu-MC1.10.2-2.0.5.jar
DarkUtilities-1.1.8.finalrc2.jar
Decocraft-2.4.2_1.10.2.jar
deepresonance-1.1x-1.4.8.jar
DefaultOptions_1.10.2-6.1.5.jar
Draconic-Evolution-1.10.2-2.1.5.262-universal.jar
DrawersBits-1.10.2-0.36.jar
ElecCore-1.10.2-1.7.431.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
embers-0.104.jar
EnderCompass-1.9.x-1.2.3.2.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.183.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
EnderZoo-1.10-1.2.3.44.jar
EngineersWorkshop-1.3.6-1.10.2.jar
environmentaltech-1.10.2-0.10.6b.jar
etlunar-1.10.2-0.10.6a.jar
Exchangers-1.10.2-1.8.1.jar
ExtraBitManipulation-1.10.2-2.5.1.jar
ExtraCells-1.10.2-2.4.4a15.jar
extrautils2-1.10.2-1.5.2.jar
ExtremeReactors-1.10.2-0.4.5.30.jar
fairylights-2.1.3-1.10.2.jar
FarmingForBlockheads_1.10.2-1.1.16.jar
flatcoloredblocks-mc1.10-v4.4.jar
FluxNetworks-1.10.2-1.2.5.jar
foamfix-0.7.2-anarchy.jar
forestry_1.10.2-5.2.17.385.jar
Forgelin-1.5.1.jar
ForgeMultipart-1.10.2-2.0.0.38-universal.jar
FTBLib-1.1x-3.6.5.jar
FTBUtilities-1.1x-3.6.5.jar
funky-locomotion-1.10.2-alpha-0.0.3.jar
Funnels-1.10.2-1.1.2.jar
gendustry-1.6.5.31-mc1.10.2.jar
gravestone-1.5.13.jar
Gravitation Suite-3.0.1.jar
Guide-API-1.10.2-2.0.3-46.jar
HammerCore-1.10.2-1.9.4.3.jar
HelpFixer-1.10.2-1.4.15.jar
hopperducts-mc1.9.4-1.4.8.1.jar
ImmersiveEngineering-0.10-61.jar
immersivepetroleum-1.10.2-1.1.3.jar
industrialcraft-2-2.6.252-ex110.jar
infinitylib-0.11.0.jar
InGameInfoXML-1.10.2-2.8.1.89-universal.jar
intwheel-1.1x-1.2.6.jar
inventorypets-1.10-1.4.9.9b.jar
InventoryTweaks-1.61-58.jar
IronBackpacks-1.10.2-2.2.31.jar
ironchest-1.10.2-7.0.15.804.jar
jeibees-0.9.0.5-mc1.10.2.jar
jei_1.10.2-3.14.7.419.jar
journeymap-1.10.2-5.4.7.jar
justenoughdimensions-1.10.2-1.5.4.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
KleeSlabs_1.10.2-3.3.5.jar
LaunchGui-1.9.4-2.0.3-23-client.jar
librarianlib-1.10.1.jar
LibVulpes-1.10.2-0.2.8-8-universal.jar
LongFallBoots - Hard Mode.jar
LunatriusCore-1.10.2-1.1.2.38-universal.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
Mantle-1.10.2-1.1.5.jar
mcjtylib-1.1x-2.4.3.jar
MCMultiPart-1.4.0-universal.jar
Mekanism-1.10.2-9.2.4.103.jar
MekanismGenerators-1.10.2-9.2.4.103.jar
MekanismTools-1.10.2-9.2.4.103.jar
Mercurius-1.10.2-1.0.6.jar
MFFS-1.10.2-3.0.1.0_1.10_d9fd06a.jar
MmmMmmMmmMmm-1.10.2-1.13.jar
MobGrindingUtils-0.1.8.22.jar
modnametooltip_1.10.2-1.6.0.jar
ModTweaker2-2.0.13.jar
morebees-1.10.2-1.4.1.1.jar
Morph-o-Tool-1.0-12.jar
Morpheus-1.10.2-3.1.13.jar
MouseTweaks-2.8-mc1.10.2.jar
mpbasic-1.10.2-1.1.5.jar
mputils-1.10.2-1.2.9.jar
MrTJPCore-1.10.2-2.0.1.20-universal.jar
MTLib-1.0.3.jar
multistorage-1.10.0-1.2.18b.jar
natura-1.10.2-4.1.0.77.jar
NaturalPledge-r1.11.jar
NetherPortalFix_1.10.2-3.3.4.jar
NotEnoughItems-1.10.2-2.1.3.220-universal.jar
omlib-1.10.2-3.0.0-137.jar
ompd-1.10.2-3.0.0-27.jar
OpenComputers-MC1.10.2-1.6.2.7.jar
OpenGlider-1.10.2-1.0.0.jar
openmodularturrets-1.10.2-3.0.0-240.jar
p455w0rdslib-1.10.2-1.0.13.jar
Pam's HarvestCraft 1.10.2j.jar
platforms-1.10.0-1.2.10.jar
pressure-1.3.1.27-mc1.10.2.jar
ProjectRed-1.10.2-4.8.4.49-Base.jar
ProjectRed-1.10.2-4.8.4.49-integration.jar
ProjectRed-1.10.2-4.8.4.49-lighting.jar
ProjectRed-1.10.2-4.8.4.49-mechanical.jar
ProjectRed-1.10.2-4.8.4.49-world.jar
Psi-r1.0-42.jar
PSIonicUpgrades-r1.15.jar
quantumflux-1.10.2-2.0.11.jar
QuantumStorage-1.10.2-3.3.4.jar
Quark-r1.1-70.jar
Railcraft_1.10.2-10.1.2.jar
rangedpumps-0.3.jar
ReAuth-3.5.0.jar
RebornCore-1.10.2-2.13.6.142-universal.jar
RedstoneArsenal-1.10.2-2.1.3.8-universal.jar
RefinedRelocation-mc1.10.2-2.1.27.jar
refinedstorage-1.2.26.jar
Reliquary-1.10.2-1.3.3.664.jar
ResourceLoader-MC1.9.4-1.5.1.jar
rftools-1.1x-6.13.jar
rftoolsctrl-1.1x-1.6.8.jar
rftoolsdim-1.1x-5.04.jar
roots-0.208.jar
Scannable-MC1.10.2-1.6.3.31.jar
ShadowMC-1.10.2-3.6.1.jar
shetiphiancore-1.10.0-3.3.9.jar
Signals-1.10.2-0.5.1-universal.jar
Simple-Void-World-1.10.2-1.1.0.4-universal.jar
simpleretrogen-1.10-4.0.1+8.jar
SimplyJetpacks2-1.10.2-2.1.3.55.jar
SleepingBag-1.10.2-1.4.0.jar
Snad-1.10.2-1.6.09.20a.jar
SolarFluxReborn_1.10.2-2.17r.jar
SonarCore-1.10.2-3.2.8.jar
StevesCarts-1.10.2-2.2.0.86.jar
StorageDrawers-1.10.2-3.7.10.jar
StorageDrawersExtras-1.10-1.1.0.jar
SuperCircuitMaker-1.0.4.jar
supercraftingframe-1.10.2-1.2.1.88.jar
TConstruct-1.10.2-2.6.5.jar
TechReborn-1.10.2-2.1.17.233-universal.jar
Thaumcraft-1.10.2-6.0.BETA8.jar
theoneprobe-1.1x-1.4.14.jar
ThermalDynamics-1.10.2-2.0.10.16-universal.jar
ThermalExpansion-1.10.2-5.1.9.23-universal.jar
ThermalFoundation-1.10.2-2.1.5.12-universal.jar
TickProfiler-1.10.2-jenkins.59.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
tinker_io-1.10.2-release+2.4.4b.jar
topaddons-1.10.2-0.15.0.jar
torchmaster_1.10.2-1.4.1.34.jar
Translocators-1.10.2-2.1.4.55-universal.jar
UniDict-1.10.2-2.9b.jar
usefulnullifiers-1.3.5.jar
valkyrielib-1.10.2-0.10.6.jar
WanionLib-1.10.2-1.3.jar
WirelessCraftingGrid-1.10.2-1.0.0.jar
WirelessCraftingTerminal-1.10.2-2.1.49.jar
woot-1.10.2-1.4.1.jar
WR-CBE-1.10.2-2.0.0.18-universal.jar
xnet-1.4.0.jar
Xtones-1.10.2-1.0.1-3.jar
YABBA-1.10.2-0.5.1.jar
zerocore-1.10.2-0.1.0.6.jar

Alternatively, it's basically FTB Beyond 1.11 (for Minecraft 1.10.2) with the following changes:

Update Baubles to 1.3.13 (for Thaumcraft beta8 dependency)
Update WirelessCraftingTerminal to 2.1.49 (to fix a crash)

Add the following mods:

> AdvancedRocketry 1.4.0
Architech 1.2.0.34
AstralSorcery 1.4.5
BiomesOPlenty 5.0.0.2290
CosmeticArmorReworked v2a
CraftingCraft 4.1.9
CraftingTweaks 6.1.16
EnderCompass 1.2.3.2
EnderZoo 1.2.3.44
Exchangers 1.8.1
ExtraBitManipulation 2.5.1
ExtraCells 2.4.4a15
FairyLights 2.1.3
FarmingForBlockheads 1.1.16
ImmersivePetroleum 1.1.3
InventoryPets 1.4.9.9b
JustEnoughDimensions 1.5.4 (that was a new add to see if I could fix this issue)
LibrarianLib 1.10.1
LibVulpes 0.2.8-8
Mekanism 9.2.4.103
MekanismGenerators 9.2.4.103
MekanismTools 9.2.4.103
NaturalPledge r1.11
omlib 3.0.0-137
ompd 3.0.0-27
OpenModularTurrets 3.0.0-240
Platforms 1.2.10
Pressure 1.3.1.27
PSIonicUpgrades r1.15
quantumflux 2.0.11
Scannable 1.6.3.31
Thaumcraft 6.0 BETA8
TickProfiler jenkins.59
TinkerIO 2.4.4b
Xtones 1.0.1-3

**Comment by UntoldForce** [comment]
I attempted to import the old overworld into a Biomes O Plenty dimension created with JustEnoughDimensions to see if it was a RFTools Dimension issue. It isn't a RFT issue at all. The same thing happens with JustEnoughDimensions. There's a block id mismatch happening at the Forge level. I apologize for taking your time with it. Here's the remains of my old city... hellish as it looks now, it was once a nice place.

https://imgur.com/a/RIBtS9f

If you're willing to help me figure out how to deal with Forge block id conflicts, I would appreciate any experience... I'm trying to learn as I go along and there's a lot to deal with here.

**Comment by josephcsible** [comment]
Unfortunately, I don't know how to change a world's block mappings
