### ISSUE TITLE
Server crash when using powered dimension in Survival

### ISSUE THREAD

**Issue by dragonmux** [McJty/RFToolsDimensions#212]
Issue description: 
Complete server crash with the player data requiring manual editing on attempting to teleport using the Matter Transmitter to any powered RFTools Dimension while in Survival mode (no other modes tested). Player data will be changed to the spawn point of the dimension but the dimension is not loaded at the time of teleportation despite dialling it, causing an invalid dimension exception to be thrown.

Steps to reproduce: 
Run the mods on a SMP+Forge server, and connect in via the 1.12.2 client running Forge and mods.
Create an empty dimension tab and use it in the Dimension Enscriber to create a random dimension, stick that in the Dimension Builder, powering it. Wait for the dimension to complete init. Dial dimension using suitably powered Dialing Device and Matter Transmitter. Step onto Transmitter and wait for the server to crash (happens on completion of the teleport count-down).

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* McJtyLib: 2.6.7
* RFTools: 7.33
* RFTools Dimensions: 1.8.1
Updated yesterday (2018/04/28).

Possibly incompatible mods: 
Unknown. OptiFine on the client, but this is a server crash, and the server doesn't have OptiFine.

Relevant logs, if any: 
https://pastebin.com/TSaiVY2f

==
I will attempt to recreate this with just RFTools Dimensions and supporting mods next, if this is not sufficient information.

**Comment by josephcsible** [comment]
This looks like it's caused by Bounding Box Outline Reloaded. See if removing it fixes the crash. If so, report it to [their tracker](https://github.com/irtimaled/BoundingBoxOutlineReloaded/issues).

**Comment by dragonmux** [comment]
Thanks for the response @josephcsible - we've now had some down time on the server and tested that hypothesis, and you're correct.. that's BBORs bug. I'll go post something on their tracker.

Rachel.
