### ISSUE TITLE
Makeing a dimension

### ISSUE THREAD

**Issue by EdTheDog** [McJty/RFToolsDimensions#218]
Ok so I don't really know where to post this but I have been running into an issue with creating Dimensions... So Here are the screenshots of the info:

![2018-05-30_18 16 08](https://user-images.githubusercontent.com/25651589/40756254-3e91a712-6437-11e8-82f9-da1ddb1085bd.png)
![2018-05-30_18 16 19](https://user-images.githubusercontent.com/25651589/40756255-3eabc638-6437-11e8-951b-91fc1c6b94ca.png)
![2018-05-30_18 16 26](https://user-images.githubusercontent.com/25651589/40756256-3ec59202-6437-11e8-8c71-6ec80d91772d.png)

And this is what I want:

5 Biomes: Roofed Forest, Mesa, Jungle, Ice Spikes, And Thaumcraft Magic Forest
No dimlet Buildings
Peaceful
(I Have CHEATER because I am making this in creative mode.)
Structure Dimlet: None
Weather: No rain or thunder
Normal Sky with a bright night and large sun and moon.
No mobs  besides wolves
Effects: haste3 and night vision
Oregen of ONLY these ores: Coal, Redstone, Diamond, Iron, Certus Quarts, And Charged Certus Quarts
I Want normal terrain made out of GRASS! and a clean environment...

But I keep getting

A bunch of biomes
Other mobs
All the ores
Stone tops of biomes
and lakes made out of other stuff!

I don't know what to do! Any help would be appreciated! ._.

**Comment by josephcsible** [comment]
Please provide the information requested in [the template](https://github.com/McJtyMods/RFToolsDimensions/blob/1.12/.github/ISSUE_TEMPLATE.md) (mainly the versions).

**Comment by EdTheDog** [comment]
Oh yes... the versions, sorry I forgot... :(
Minecraft: 1.12.2
Forge: 1.12.2-14.23.32702
McJtyLib: 2.6.7
RFTools: 7.33
RFTools Dim: 5.53

**Comment by josephcsible** [comment]
You may be putting your dimlets in the wrong order. Does the enscriber give you any warnings in its GUI?

**Comment by EdTheDog** [comment]
No There are no warnings. But I have tried 13 different orders now. (Yes I Counted it.) And I still get this. There must be a correct order I Just don't know what! :P

**Comment by EdTheDog** [comment]
Hey Josephcsible? Any Ideas or nothing? :P Becuase I still got nothing.

**Comment by josephcsible** [comment]
I have some ideas. I'll try to investigate them tomorrow.

**Comment by EdTheDog** [comment]
Ok! So After LOTS AND LOTS of testing, I found out my stupid mistake... the clean dimlet! And now it works fine! WOW! I am an idiot! You can close this issue now. I did learn a lot about how to make dimensions though! So yay!
