### ISSUE TITLE
Reciever blowen up by creeper in dimension

### ISSUE THREAD

**Issue by officerwolf** [McJty/RFToolsDimensions#221]
So i have created a new dimension and before leaving a creeper had blowen up the reciever and now unable to go,to the dimention.  I was wondering if there is a way to fix it without admin privleges and if so it would be nice for it to be explained in like a faq in the rftools book or wiki

**Comment by josephcsible** [comment]
Yes, it's called the Dimension Editor. And the book already explains it: https://github.com/McJtyMods/RFToolsDimensions/blob/15c0bea0238c30343aea47c7316e0dc01fc1d579/src/main/resources/assets/rftoolsdim/text/manual_dimension.txt#L459-L463
