### ISSUE TITLE
[1.10.x] Crash when hovering over blue dimlets

### ISSUE THREAD

**Issue by daredood** [McJty/RFToolsDimensions#222]
Issue description:  Whenever the mouse hovers over a specific dimlet, the game crashes.

Steps to reproduce: 
1: Find dimlet.
2: Hover over it.
3: Wait for crash.

Versions:
* Minecraft: 1.10.2
* Forge: 12.18.3.2511
* CompatLayer (only if on Minecraft 1.10 or 1.11): 1.10-0.3.1
* McJtyLib: 1.1x-2.5.3-SNAPSHOT
* RFTools: 1.1x-7.16
* RFTools Dimensions: 1.1x-5.05

Possibly incompatible mods: Optifine, Biomes'o'Plenty, BookshelfLoadingPlugin, SimpleCore, CoFH, PlusTiC, FMLPlugin, MalisisCorePlugin, LoadingPlugin, FarseekCoreMod, Brandon's Core, IC2Core, p455w0rds Things, CCLCorePlugin, PlayerAPIPlugin, MicdoodlePlugin, OpenModsCorePlugin, IvToolkit, CSLibraryCore, CTMCorePlugin

Relevant logs, if any: 
https://pastebin.com/hPyrZMCe

**Comment by fred21O4** [comment]
this happens to me in 1.16.5 on the version 1.16-7.0.6-beta. [log](https://paste.ee/p/NeIeC)

**Comment by McJty** [comment]
Fixed by updating McJtyLib
