### ISSUE TITLE
[1.12.2]: Game crashes when viewing the Dimlet Workbench if ProjectX 2 is installed.

### ISSUE THREAD

**Issue by SonicX8000** [McJty/RFToolsDimensions#223]
Referenced Issue:
https://github.com/KitsuneAlex/ProjectX/issues/11

Figure I report this here as well, just in case... and hopefully it's the correct place for the RFTools section.

Minecraft: 1.12.2
Forge: 14.23.4.2704

Mods:
CodeChickenLib-1.12.2-3.1.8.341-universal
mcjtylib-1.12-3.0.0
ProjectX-1.12.2-2.2.6-universal
rftools-1.12-7.51
rftoolsctrl-1.12-1.9.0
rftoolsdim-1.12-5.60
rftoolspower-1.12-1.1.0
Silverfish-1.12.2-0.0.18-universal

Crash Report:
https://pastebin.com/KerhTMpR

---
When you attempt to view the Dimlet Workbench via a Right-Click, the game will crash. If I remove the "ProjectX" mod, the crash won't occur.

**Comment by SonicX8000** [comment]
Project X & Silverfish were updated so I gave it a test to see if the crash still occurred... the game still crashes when clicking on the Dimlet Workbench Block.

I removed a few mods to narrow it down, also updated Forge.

---

Minecraft: 1.12.2
Forge: 14.23.4.2709

Mods:
CodeChickenLib-1.12.2-3.1.8.341-universal
mcjtylib-1.12-3.0.2
ProjectX-1.12.2-2.2.7-universal
rftools-1.12-7.54
rftoolsdim-1.12-5.60
Silverfish-1.12.2-0.0.19-universal

Crash Report:
https://pastebin.com/FQHFNSwy

**Comment by josephcsible** [comment]
KitsuneAlex/ProjectX#13 gives examples of these sorts of crashes without RFTools Dimensions even being installed. Until they fix those on their end, there's nothing more we can do about this.
