### ISSUE TITLE
/rftdim safedel <id> gives "Command is not allowed!"

### ISSUE THREAD

**Issue by OfficialStamper** [McJty/RFToolsDimensions#227]
Issue description: 

Players using the above command to delete their own owned dimensions get command not allowed.

Config file is configured the same on both server and clients as follows:

```
    # If this is enabled then regular players can delete their own dimensions using the /rftdim safedel <id> command
    B:playersCanDeleteDimensions=true
```

Mod pack: All The Mods 3 v5.9.7b
rftools-1.12-7.51.jar
rftoolsctrl-1.12-1.9.0.jar
rftoolsdim-1.12-5.60.jar
rftoolspower-1.12-1.1.0

Steps to reproduce: 

use the /rftdim command, get; command not allowed.

Versions:
* Minecraft: 1.12.2
* Forge:  forge-1.12.2-14.23.4.2707-universal.jar

Mod pack: All The Mods 3 v5.9.7b
rftools-1.12-7.51.jar
rftoolsctrl-1.12-1.9.0.jar
rftoolsdim-1.12-5.60.jar
rftoolspower-1.12-1.1.0

Possibly incompatible mods: 
None. Optifine not used. SpongeForge not used

Relevant logs, if any:

**Comment by josephcsible** [comment]
Can you copy and paste the exact message you get when you run the command?

**Comment by OfficialStamper** [comment]
It comes up in RED in the chat 'Command is not allowed!'
Client side log reads:
`[23:12:02] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ȣCommand is not allowed!`
No message in server log.

Edit: FYI, if OP'ed the command works fine.

**Comment by josephcsible** [comment]
Can you reproduce this with no other mods installed?

**Comment by OfficialStamper** [comment]
Sorry, it was an FTBLib permission issue, you can close this.  Thanks for your responses though, sorry to have wasted your time.
