### ISSUE TITLE
Effect Dimlet (None) is not effective

### ISSUE THREAD

**Issue by Jizanthapus** [McJty/RFToolsDimensions#230]
Issue description: 
Using the No Effects dimlet in a Dimension Enscriber has no effect on the Realized Dimension

Steps to reproduce: 
Create a dimension in the Dimension Enscriber using only an "Effect Dimlet (None)"
Visit dimension and experience slowness, hunger, poisoning, etc. 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2730
* McJtyLib: 3.0.2
* RFTools: 7.54
* RFTools Dimensions: 5.60

Possibly incompatible mods: 
[Mod List](https://pastebin.com/w7hhp54k)
I tried testing this issue with a greatly reduced set of mods (JEI, RFTools, etc.) and did not encounter the problem. So the issue is likely caused by an interaction, but I have no idea with what.

Relevant logs, if any: 
[Screenshot: In the dimension](https://i.imgur.com/D49CkZu.png)
[Screenshot: Looking at extracted dimlets](https://i.imgur.com/nGO5dZC.png)

**Comment by josephcsible** [comment]
The Effect Dimlet doesn't stop the bad effects that come from a dimension with insufficient power. Add some more power and see if they go away.

**Comment by Jizanthapus** [comment]
Thanks for the fast response.
I had over 1 million RF and climbing in the dimension when I tried it.
Also, the negative effects aren't always the same in the dimensions I've tried. Sometimes it's Hunger, Poisoning, Slowness, and Mining Fatigue, yet with others, I only get Slowness and Mining Fatigue.

**Comment by McJty** [comment]
1 million is not enough. Bad effects start at under 4 million
