### ISSUE TITLE
[1.12.2] Missing "Unknown" Dimlets and Dimlet Researcher

### ISSUE THREAD

**Issue by Retalyx** [McJty/RFToolsDimensions#234]
Issue description: 
Hi, i was about to setup my rftools dim system on my base, but i couldn't find any Unknown Dimlet and unable to craft Dimlet Researcher, also they are not displayed on JEI and not listed where i type /give *** rftoolsdim: and pressing tab to check available blocks/items. They were removed ?
![image](https://user-images.githubusercontent.com/3114980/45273536-834ff080-b4b3-11e8-999d-96239e352bf7.png)
![image](https://user-images.githubusercontent.com/3114980/45273585-aed2db00-b4b3-11e8-96f8-60207b1c2b81.png)
![image](https://user-images.githubusercontent.com/3114980/45273620-c6aa5f00-b4b3-11e8-98c6-2cb20fe339ed.png)

So i'm only able to use empty dimlets dimensions (so always the same dimension, without any structure with dimlets inside)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2759
* McJtyLib: 3.0.4
* RFTools: 7.55
* RFTools Dimensions: 5.60

**Comment by McJty** [comment]
Yes the unknown dimlets are gone. You need to use the dimlet workbench now

**Comment by Retalyx** [comment]
Ho okay :o so, sorry for the stupid issue posting..
Since what version they were removed?

**Comment by McJty** [comment]
Since Minecraft version 1.8.9

**Comment by Retalyx** [comment]
Oh okay, i jumped from 1.7.10 to 1.12.2, so the transition was brutal :) thanks for answers
