### ISSUE TITLE
No dimlets for a lot of stuff

### ISSUE THREAD

**Issue by Archilyte** [McJty/RFToolsDimensions#237]
Issue description: Some blocks from mods don't have a dimlet.

I was using a modified version of D20 modpack. I just added in snapshot 6 of nevermine mod. And none of the blocks of that mod have dimlets.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2749
* RFTools Dimensions: 5.60

I don't know what else to say. And I'm pretty sure those blocks that don't have dimlets aren't tile entities (they are just normal blocks)

**Comment by McJty** [comment]
That's normal. Dimlets don't get added automatically due to balancing reasons. You have to enable them in the config. There is documentation on that here:

https://wiki.mcjty.eu/mods/index.php?title=RFTools_Dimensions
