### ISSUE TITLE
Crashing upon entering dimension

### ISSUE THREAD

**Issue by knoxhack** [McJty/RFToolsDimensions#238]
Issue description: 
Bug Report
I was trying to create a new dimension using RF Tools Dimensions for Draconium. I had completed creating one that had only the following:

Draconium Ore
Huge Orbs
Plains biome
My dimension built fine and had power. I teleported into it only to crash. It maybe something to do with the attributes of the dimension just causing issues. I'm uncertain. However, I'm stuck there now and each time I boot up, the game loads for a few seconds, I can look down, then I crash.

From what I can tell, the dimension looked like it had red like lightning or something going on, which maybe causing serious issues.

If I can at minimum get out of the dimension, it would be great.

Steps to reproduce: 
Steps to Reproduce (for bugs)
Create an RF Tools Dimension with the above attributes.
Try entering the world.

Versions:
* Modpack: StoneBlock 1.0.20
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2768
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.0.5
* RFTools: mcjtylib-1.12-3.0.5
* RFTools Dimensions: rftoolsdim-1.12-5.61

Relevant logs, if any: 
Logs
Here is my crash report: [Link](https://pastebin.com/rJ5sHsuc)

**Comment by josephcsible** [comment]
The bug is that it's possible for this loop to drop `index` below 0 if there's just air and liquid all the way down: https://github.com/McJtyMods/RFToolsDimensions/blob/b95ac933a1c0895755a14e3f7d284341d60acbdd/src/main/java/mcjty/rftoolsdim/dimensions/world/terrain/lost/LostCitiesTerrainGenerator.java#L872-L876

**Comment by MakeLord95** [comment]
Is there any quick fix to try since 2 out of 6 new dims I created crashes with the same log?
