### ISSUE TITLE
RFtools Dimensions - time dimlets have no change on day/night cycle

### ISSUE THREAD

**Issue by pronukes** [McJty/RFToolsDimensions#245]
Issue description: 
no matter what variation of dimlets i use, even just time setting dimlets, they  have no effect on the day/night cycle inside the dimensions i create. 
Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forgelin: 1.8.0 --- ForgeMultipart?: 2.6.0.79
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:  3.0.6
* RFTools: 7.59
* RFTools Dimensions: 5.63
*optifine_1.12.2_HD_U_E2

Possibly incompatible mods: 

Relevant logs, if any: 
no crash reports.

**Comment by josephcsible** [comment]
What version of FORGE (not Forgelin or ForgeMultipart) are you on? Which dimlets exactly did you use? Are you sure the issue was actually the day/night cycle, and not that it looked dark due to not enough power? Can you reproduce this with no mods installed other than RFTools Dimensions and its dependencies?

**Comment by pronukes** [comment]
actually cant see what version of forge, cant see it on the lists.. 
exact dimlets currently in:

time dimlet - noon (have tried multiple variations of morning/midnight/noon, nothing changes the day/night cycle)
weather dim - no rain + no thunder
terrain dim - flat
biome dim - red desert

have even tried just putting time dims only in, still has a day night cycle. 
the modpack we are running on the server is " FTB Revelations "

have not tried it with just rf tool + dimensions, no, could attempt to. was going to try running same list of mods but not on the server and see if anything changed.  

also we tested an enviromental tech solar panel in a dimension we made during the day and it was not producing any power, everything was chunkloaded.

**Comment by McJty** [comment]
And does the dimension have enough power? How much power are you giving it and how much does it need?

Also is the dimension builder chunkloaded?

**Comment by pronukes** [comment]
everything is chunkloaded, the builder is full of power, have 9billion rf sitting there in a draconic core. 
builder says dimension maintenance cost is 131 rf/tick were making well over 50,000/tick

**Comment by josephcsible** [comment]
> have not tried it with just rf tool + dimensions, no, could attempt to. was going to try running same list of mods but not on the server and see if anything changed.

Both of these things are indeed worth trying.

**Comment by vmsh0** [comment]
I have the same issue. Pretty much same conditions, sufficient power, dimension builder is chunkloaded, etc.

**Comment by josephcsible** [comment]
Please try the things that I asked the original reporter to try, and let us know what happens. Also, make sure you're on the latest version of these mods and Forge.
