### ISSUE TITLE
Id not regist

### ISSUE THREAD

**Issue by Dourmouki** [McJty/RFToolsDimensions#247]
Issue description: Got new dimention tab put it in builder and the dialing device is not registing the new id to call it

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: Stoneblock newest version
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:
* RFTools Dimensions: 

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
Does the builder have enough power to create the dimension? Do you see it in the creative-only Teleport Probe? Does injecting a matter receiver with the dimension editor change anything?

**Comment by Dourmouki** [comment]
Yes the builder got enough power to support the dimention
No i do not see it at creative-only Teleport Probe
Tried to inject a receiver and i got a crash

Edit:reopen client and matter receiver is in editor at 10% and ongoing to inject but id not to be found 
and dimension is in builder, charging and saying ready

**Comment by josephcsible** [comment]
Please post the crash report. Your world may be corrupt. See if you can reproduce the problem in a fresh world.

**Comment by Dourmouki** [comment]
World was corrupt did a clean startup and its working fine
