### ISSUE TITLE
[1.12.2] Crash on server startup

### ISSUE THREAD

**Issue by Furuchiru** [McJty/RFToolsDimensions#249]
Issue description: 
Server crashes on startup. Running Enigmatica 2 Expert 1.47

Steps to reproduce: Start the server

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.7
* RFTools: 7.59
* RFTools Dimensions: 5.63

Possibly incompatible mods: Foamfix (still crashes w/o it)

Relevant logs, if any: 
Crashreport: https://pastebin.com/JvZttCfm
log: https://pastebin.com/PUVtTpVL

**Comment by josephcsible** [comment]
Your dimlets.json file is bad. Did you edit it yourself? If so, replace the file with the one that shipped with the pack. If not, then report this to the pack author, and you can temporarily work around it by deleting the file (it will be regenerated with the mod's defaults).

**Comment by Furuchiru** [comment]
I did not edit it but the file was empty. it worked fine till yesterday, idk what happened really.
I re downloaded it and replaced and it worked.
Thank you a lot!

**Comment by josephcsible** [comment]
You're welcome!
