### ISSUE TITLE
Weird lag / Crash / Charged porter issues [ rftoolsdim-1.10-4.30beta46]

### ISSUE THREAD

**Issue by drkninja64** [McJty/RFToolsDimensions#25]
I created an empty dimension, and once I entered it, it was lagging very much. Overworld was working fine, only that dimension was lagging. After a few random crashes when teleporting in and out, it started working fine. Then I couldn't enter it anymore once i restarted my world (It said destination was missing.) Also a few times when teleporting using the advanced charged porter from the nether, I get teleported to a random spot in the overworld immediately followed by a crash [ pastebin.com/724s5ant ].

http://imgur.com/a/AVfbx

**Comment by drkninja64** [comment]
Another crash happened again while teleporting out of the dimension.

http://pastebin.com/N857bTr9

**Comment by McJty** [comment]
I'll check it out soon

**Comment by McJty** [comment]
What are the features of that dimension? Can you show me the dimlets and/or a screenshot with right click of the dimension tab in your hand?

**Comment by drkninja64** [comment]
This is the dimension. http://imgur.com/a/uMqcw
It may happen because it is chunk loaded with a working quarry (when its on). I'm using persistent bits to chunk load, if that helps. Also it happens when teleporting out of the nether as well i.e crash + Spawn in the world spawn it seems.

**Comment by McJty** [comment]
Hmm if it also happens when teleporting out of the nether then it is not likely to be an rftools bug though

**Comment by drkninja64** [comment]
hmm, what could it be?
What else could lead to concurrent ticking? Also i'm going to try it on the latest versions of every mod  on my modlist now, including this one.

EDIT: Doesn't happen every time for nether, but does happen everytime for that dimension

**Comment by drkninja64** [comment]
With everything up to date, everything seems to be working fine for now. I teleported in and out of every dimension I have. Thanks for the help. I'll update you if it happens again.
