### ISSUE TITLE
[Suggestion] allow multiple dimensions with the same descriptor

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsDimensions#254]
Self explanatory. I would like to be able to create multiple of the exact same world

**Comment by josephcsible** [comment]
Currently, if you want a dimension that needs too much power for one dimension builder to provide, you power it by creating multiple tabs with the same descriptor, then putting them all in builders and supplying more power that way. With your suggestion, you'd break this not-uncommon use case. What's wrong with just using digit dimlets?

**Comment by ghost** [comment]
Oh yeah, I forgot about those. It's been a crap week for me, forgive my oversights.

And it's not because of power, I'm going to use rftools for some rpg stuff and need multiple worlds that are just a big block of whatever for carving dungeons and raids out of.
