### ISSUE TITLE
Please fix this annoying crash :'/

### ISSUE THREAD

**Issue by ReiDaTecnologia** [McJty/RFToolsDimensions#259]
Issue description: 
If u go to Multiplayer and try to go to Singleplayer it crashes your game and even the VanillaFix can't help u ;-;
u need to restart the game (and for heavy modpacks like Remix it kills my computer)
Steps to reproduce: 
1)Go to Multiplayer
2)Go to Singleplayer
3)Restart to fix it

Versions:
Note: i'm using Project Ozone 3 currently but it happens with like any modpack that i play '-'
And i tested it without no extra mods only the "responsible mods for the crash" and it didn't crash so there is a mod that is causing it and sadly the crash report don't help with it, i hope u have a way to know. Good luck and hopefully u will fix this nasty crash! :D
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.1.1
* RFTools: 1.12-7.61
* RFTools Dimensions: 1.12-5.64

Possibly incompatible mods: 
optine ofc but i think it's not the issue

Relevant logs, if any: 
https://paste.dimdev.org/iteludijed.mccrash

**Comment by McJty** [comment]
um, how do you switch between multiplayer and singleplayer? I didn't even know that was possible

**Comment by McJty** [comment]
Ah nm, I get what you mean now

**Comment by McJty** [comment]
I may have a fix for this. Will test it later and see if it works

**Comment by McJty** [comment]
Should be fixed in latest version
