### ISSUE TITLE
Incomplete oregen on a dimension

### ISSUE THREAD

**Issue by Ashendale** [McJty/RFToolsDimensions#262]
Issue description: Incomplete ore generation. Some modded ores spawn, others do not (specifically Astral Sorcery Rock Crystal ore).

Steps to reproduce:  Create a dimensions (say a flat to simplify), have stone as default terrain, Thermal Dynamics ores (tin, silver, etc) spawn normally, Astral Sorcery Rok Crystals do not (using AS Resonating Wand you can fly and find markers at night https://minecraftguides.net/AS/getting%20started/resonating%20wand )

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2831
* McJtyLib: 1.12-3.5.2
* RFTools: 1.12-7.71
* RFTools Dimensions: 1.12 - 5.71

Possibly incompatible mods: 
Surge, foamfix (don't think they qualify, but I rather mention them than not)

**Comment by McJty** [comment]
That's not RFTools Dimensions fault. It is up to the other mods to decide in what dimensions they do their oregen. I have no control over that

**Comment by Ashendale** [comment]
Thanks for the quick response. I went through AS config files and could not find a black/white list for which dimensions it spawns on. Are you saying it's hardcoded?

**Comment by McJty** [comment]
Well I don't know that mod. I think you better ask on AS issue tracker
