### ISSUE TITLE
Opening Dimlet workbench crashes client

### ISSUE THREAD

**Issue by Deckee** [McJty/RFToolsDimensions#263]
Issue description: Trying to open gui on the dimlet causes a client crash on single player and multiplayer. Could be simular to issue #87 

Steps to reproduce: place down workbench and open it 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* McJtyLib: 1.12-3.5.2
* RFTools:1.12-7.71
* RFTools Dimensions: 1.12-5.71

Relevant logs: 
https://paste.dimdev.org/gejekogufu.mccrash

**Comment by josephcsible** [comment]
The bug is in ProjectX. Uninstall that and it will work. See also #223, MoshpitSoftware/ProjectX#11, and MoshpitSoftware/ProjectX#13. (It's unrelated to #87.)
