### ISSUE TITLE
mod not "loading"

### ISSUE THREAD

**Issue by gmhude56** [McJty/RFToolsDimensions#266]
Issue description: 

Steps to reproduce: 

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:
* RFTools Dimensions: 

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
You need to fill out the template properly.
