### ISSUE TITLE
request: 1.7.10 version

### ISSUE THREAD

**Issue by smeegle5000** [McJty/RFToolsDimensions#267]
i love what this mod is trying to do, but all of my modpacks are 1.7.10 and a couple mods i can't get on higher versions, i know that rftools is 1.7.10 and i would like to request that rftools: dimensions is also compiled for 1.7.10.

**Comment by McJty** [comment]
On 1.7.10 rftools dimensions is already included with rftools so this is not needed

**Comment by smeegle5000** [comment]
ah, alright, i thought that it just didn't have the proper side mod when i kept loading into dimensions that had nothing in them but black "sludge" blocks
