### ISSUE TITLE
Deaktivating VoidOnly is not working

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [McJty/RFToolsDimensions#269]
Issue description: 

I disabled the VoidOnly option in the serverconfig and after restarting the server made sure it stayed changed because i had already problems with configs resetting, but it worked fine. While starting the dimlets.json got edited by the game, but i was unable to find any changes, after joining the server it didn´t change anything, i was still only able to create void worlds and dimlets!

Steps to reproduce: 

Just run the Modpack Official Skyworld + Server in the Technic launcher (basically skyfactory 3), then change the config in the way that you disable void only, restart the pack and you should see that nothing changed.

Versions:
* Minecraft: 1.10.2
* Forge: 1.10.2-12.18.3.2511-universal
* CompatLayer: [1.10]-0.3.0
* McJtyLib: [1.10.2]-2.5.1
* RFTools: [1.10.2.x]-7.16
* RFTools Dimensions: [1.1x]-5.05

Optifine is installed clientside, but the problem occures on the server

Possibly incompatible mods: 
   no idea

Relevant logs, if any: 

No Logs, because of not crashing the game

**Comment by josephcsible** [comment]
Can you reproduce the issue on a server with no other mods installed, or in single player? If not, then the problem is likely with the pack/server setup and not with this mod.

**Comment by DeinAlbtraumTV** [comment]
I will try that

**Comment by DeinAlbtraumTV** [comment]
For some reason, after changing my own config it seems to Work, maybe it applied the Changes wrong or whatever, it works now, that is what counts

**Comment by josephcsible** [comment]
Good to hear.
