### ISSUE TITLE
Registering RF Tools Dimensions hangs for some time

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsDimensions#275]
Issue description: 
While booting the server, after Server_Start Event, the "Registering RfTools Dimensions: " Log message appears and won't be finished for several minutes by now. 

This is the Log output at the end: 

[22:27:49] [Server thread/INFO] [mcjtylib_ng]: RFTools: server is starting
**[22:27:49]** [Server thread/INFO] [mcjtylib_ng]: Registering RFTools dimensions:

 // This is 6 minutes of 100% CPU Usage and no output

**[22:33:40]** [Server thread/INFO] [Astral Sorcery]: Load CachedWorldData 'lightnetwork' for world 0
[22:33:40] [Server thread/INFO] [Astral Sorcery]: Loading of 'lightnetwork' for world 0 finished.
[22:33:41] [Server thread/INFO] [Astral Sorcery]: Load CachedWorldData 'structurematcher' for world 0
[22:33:41] [Server thread/INFO] [Astral Sorcery]: Loading of 'structurematcher' for world 0 finished.
[22:33:42] [Server thread/INFO] [FML]: Unloading dimension 1
[22:33:42] [Server thread/INFO] [FML]: Unloading dimension 28885
[22:33:42] [Server thread/INFO] [FML]: Unloading dimension -11325
[22:33:42] [Server thread/INFO] [FML]: Unloading dimension 4598
[22:33:42] [Server thread/INFO] [FML]: Unloading dimension -1

These 6 minutes had been < 60s only a week earlier. I had to change the max-tick rate to -1 already so that the server won't crash at that point. It finishes, but it takes a long time. 

We never ever have done anything with RfDim itself, the mod is just part of the complete pack. So no dims have been created or entered yet, besides all Vanilla Dims ( OW, nether, End) and the Twilight Forest, checking the world folder also shows the dims, for storages etc. /rfdim list shows only NON RF Dimensions.

Steps to reproduce: 
* Install the Server pack of DDSS 6.3 and play a world for some weeks. Overworld is fairly explored. 
* Not sure if it's reproducable at all ... 

Specs of the V-Server aren't the greatest but should be enough:
* CPU: 2 Cores of an Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
* RAM: 12 Gigabytes (now reduced to 10Gig, since we got some hs_err_pid)
* Diskpace: 10Gig space left (no problem here, checked IO speeds etc.)

Versions:
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2836
* McJtyLib: mcjtylib-1.12-3.5.4
* RFTools: rftools-1.12-7.72
* RFTools Dimensions: rftoolsdim-1.12-5.71
* Dungeons, Dragons and Spaceshuttles Modpack: v6.3

Possibly incompatible mods: 
* We added BetterRecords to the Pack, but the problem already appeared before. Further testing will be done on the weekend.

I'll reference Issue #152  here, since I posted some information there as well.

**Comment by ghost** [comment]
Is there Debug Logging in the code that could be activated to see what's happening in the 6 minutes ?

**Comment by McJty** [comment]
This is probably not caused by rftools dimensions. It is not because RFTools Dimensions happens to be the last thing that said something in the log that other mods are not doing stuff in the mean time. Register dimensions almost doesn't do anything. That's very light

**Comment by ghost** [comment]
But nothing prints to log besides RF Tools and After that Astral Sourcery, which has correct log for starting their work and ending their work. 

Any tip on how I could find the culprit ? Without binary swapping 200+ mods that are all webbed together for the pack ? :D 

I'm a Java Developer myself, so I know the stuff, never debugged Minecraft Mods before though, especially not a whole pack.

**Comment by McJty** [comment]
Well the other mods that do work between those could just be silent. My mods have often been accused of causing slowdowns or even crashes just because I'm slightly more verbose as to what I'm doing giving the impression that my mods are to blame.

Anyway, finding the real issue is not that easy though. You could perhaps try a profiler

**Comment by ghost** [comment]
Yep I thpught about using a Profiler, but i\ll do it later this weekend
probably. since profiling it will cost a lot of resources, I don't have at
hand locally. ... Also downloading the current state of the Server, could
take about 3-7hours for me :D

Am Mi., 13. Nov. 2019 um 14:44 Uhr schrieb McJty <notifications@github.com>:

**Comment by ghost** [comment]
But this might also be a time to add some logging, or at least add a "Dimeons registered" message, after the task is done.  :) 

verbosity is good, but sometimes leads to misunterstandings like this :)

**Comment by ghost** [comment]
Profiled it today, the issue has been Fluidtanks that had been stacked too high and been empty :D

Sorry for accusing you.

**Comment by Shane130798** [comment]
I too have some fluid tanks built high and more than likely empty, howe did you remove them to stop the issue?

**Comment by ghost** [comment]
@Shane130798 please don’t Post on closed issues.

The here mentioned bug, was fixed in a new version of FluidTanks.

**Comment by josephcsible** [comment]
There's nothing wrong with posting on closed issues.
