### ISSUE TITLE
Client Crash entering Dimension

### ISSUE THREAD

**Issue by exxp3** [McJty/RFToolsDimensions#277]
Issue description: When entering a dimension i get kicked after a few seconds with different error messages. After reconnecting i have only 1-3 sec to copy paste /tpx 0 in chat to escape.
Dimensions have enough power

Steps to reproduce: entering dimension

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:
* RFTools Dimensions: 

Relevant logs, if any: 
https://pastebin.com/xCs1Qg5P
https://pastebin.com/P7dQvpdi

**Comment by josephcsible** [comment]
This looks like it's actually caused by /dank/null, not by RFTools Dimensions. If you disagree, please remove /dank/null, get it to crash again, and post the new crash report you get without it.

**Comment by Exo-Net-IT** [comment]
> This looks like it's actually caused by /dank/null, not by RFTools Dimensions. If you disagree, please remove /dank/null, get it to crash again, and post the new crash report you get without it.

I removed the mod from the server but its still crashing when i enter a dimension :/

**Comment by josephcsible** [comment]
Like I said, please post the new crash report.

**Comment by Exo-Net-IT** [comment]
> Like I said, please post the new crash report.

Crash-Report:

[crash-2020-01-20_20.44.05-client.txt](https://github.com/McJtyMods/RFToolsDimensions/files/4087625/crash-2020-01-20_20.44.05-client.txt)

But now i had a weird crash screen i never had that before. 

Crash-Screen: http://prntscr.com/qqfffm

**Comment by josephcsible** [comment]
There's still no evidence that RFTools Dimensions had anything to with the crash in that report. And like your own message says, now it looks like one of Dynamic Surroundings, Farseek, or iChunUtil are at fault. Please try disabling all of them as well, and if it still crashes, then post another new report.

**Comment by Exo-Net-IT** [comment]
> There's still no evidence that RFTools Dimensions had anything to with the crash in that report. And like your own message says, now it looks like one of Dynamic Surroundings, Farseek, or iChunUtil are at fault. Please try disabling all of them as well, and if it still crashes, then post another new report.

Oke well i know that rftools is fine but i dont know what mod is causing the crash :/ ill try to disabling the mods

**Comment by Exo-Net-IT** [comment]
> There's still no evidence that RFTools Dimensions had anything to with the crash in that report. And like your own message says, now it looks like one of Dynamic Surroundings, Farseek, or iChunUtil are at fault. Please try disabling all of them as well, and if it still crashes, then post another new report.

I cant find dynamic surroundings in the mod folder and i can't disable it in mc :/ so how do i do that? In that mods Tab in mc i click on disable but nothing happens

**Comment by josephcsible** [comment]
What do you mean you can't find it in the mod folder? Please post all of the files in that folder and I'll point it out.

**Comment by Exo-Net-IT** [comment]
> What do you mean you can't find it in the mod folder? Please post all of the files in that folder and I'll point it out.

http://prntscr.com/qqfo6n

http://prntscr.com/qqfofg

http://prntscr.com/qqfomf

http://prntscr.com/qqfoqu

**Comment by josephcsible** [comment]
Hmm, did you already delete it and not realize it? Your crash report says it's called `DynamicSurroundings-1.12.2-3.6.0.2.jar`.

**Comment by Exo-Net-IT** [comment]
> Hmm, did you already delete it and not realize it? Your crash report says it's called `DynamicSurroundings-1.12.2-3.6.0.2.jar`.

No i didnt :/
