### ISSUE TITLE
RFTools always creates the same random Dimension

### ISSUE THREAD

**Issue by xXDarkNovaXx** [McJty/RFToolsDimensions#279]
Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71 
 
I created a random dimension in RFTools to farm some dimlets and then later deleted this dimension with safedel to create a new random dimension but when I delete the old random dimension and create a new random dimension it creates the same dimension over and over again that I had before 
With the same blocks the same appearance and the same structure

**Comment by josephcsible** [comment]
Working as intended. Just like deleting and recreating a game with the same seed results in the same world, deleting and recreating a dimension with the same world seed and dimlets results in the same dimension. If you want a different one, add some digit dimlets.

**Comment by xXDarkNovaXx** [comment]
But if I activate an Empty Dimension tab without Dimlet, everything should be random or not?
He only ever creates one world as siltstone coal
And according to the RFTools Wiki it should always be random when using an Empty Dimension Tab
I have now activated the random seed in the config because I found this by chance 
It now generates random seeds but still only from siltstone coal

Siltstone coal is fro Underground Biom mod

That it will always be random I got from the Wiki
https://github.com/McJtyMods/RFTools/wiki/RFTools-Dimlets

**Comment by josephcsible** [comment]
It is "random", but the randomness comes from your saved game's seed, just like the rest of the randomness in world generation. The config setting you're talking about is a misfeature; I'm surprised it hasn't been removed yet.

**Comment by xXDarkNovaXx** [comment]
So for me, random is when I use an Empty Dimension tab and the world looks different all the time and is a different material

This Function on the Pic is a misfeatures?
![Screenshot_90](https://user-images.githubusercontent.com/22129313/72670242-ab524b00-3a3b-11ea-814d-4011a52ea248.png)

**Comment by josephcsible** [comment]
Yep, that one's the misfeature.
