### ISSUE TITLE
[1.12.2] Minecraft crashed whilst initializing 

### ISSUE THREAD

**Issue by MusicMaestro123** [McJty/RFToolsDimensions#283]
Issue description: Minecraft crashed whilst initializing. NOTE: Older versions are used due to mod incompatibility with forge. 

Steps to reproduce: Use versions of the mods/mod-loaders/minecraft below.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* McJtyLib: 3.1.1
* RFTools: 7.61
* RFTools Dimensions: 5.53

Coremods/transformers: [https://paste.dimdev.org/ruduhupata.mccrash](url)
Possibly incompatible mods: Unknown

Crash log: [https://paste.dimdev.org/ruduhupata.mccrash](url)

**Comment by josephcsible** [comment]
> NOTE: Older versions are used due to mod incompatibility with forge.

Your use of older versions is the problem. You should instead upgrade everything and then file bugs against whatever mods don't work when everything else is the latest version. However, if you insist on doing this, then you'll need to keep your old versions in sync. In particular, your McJtyLib is much newer than your RFTools Dimensions (check their release dates), which is what causes this kind of problem. Either upgrade RFTools Dimensions to match McJtyLib, or downgrade McJtyLib to match RFTools Dimensions.
