### ISSUE TITLE
Dimension creation now working

### ISSUE THREAD

**Issue by Pa3kc123** [McJty/RFToolsDimensions#290]
Issue description:
Creating new dimension from same/different empty dim tab will result in same dimension as before, even after safedel / 'Nuking' of dimension
'Nuking' dimension and safedel command are working correctly (They will remove dimension from dialing device and also RFTOOLS<id> folder from disk)
On creating a new dimension everything looks, like it should be...
When I put dimension tab into builder, it will build successfully, BUT it has same ID and everything as dimension, that I just removed...
I already tried some things in config like 'randomizeSeed' but nothing worked...
Only way I can get different dimension with different stats is to put digit dimlet...

Note:
I did same thing in rftools dimension on minecraft version 1.7.10 and there everything worked as it should...

Steps to reproduce: 
- Create random dimension and enter it
- After its been generated, exit dimension
- Back in normal world save & return to main menu (otherwise dimension won't unload thus cannot be deleted)
- Return back to the world
- In escriber extract dim tab just to be sure to not have anything related to old dimension
- Use either 'Nuking' or safedel command
- Try to make new dimension from same empty dim tab with different dim stats than before

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11): None
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71

Possibly incompatible mods:
- OptiFine

Relevant logs, if any: None

**Comment by McJty** [comment]
That *is* intentional. Digit dimlets are exactly meant for this purpose

**Comment by Pa3kc123** [comment]
May I ask then what is purpose of safedel command except freeing space on disk???

**Comment by McJty** [comment]
Exactly that. Freeing space on disk and also useful on servers where people are restricted to having only a few dimensions per player

**Comment by Pa3kc123** [comment]
Ok... Thanks for answering my questions...
