### ISSUE TITLE
The Aether clashing with rftools

### ISSUE THREAD

**Issue by alexHunter854** [McJty/RFToolsDimensions#291]
Issue description: crash on entering the Aether

Versions:
* Minecraft: 1.12.2 
* Forge: 14.23.5.2854-1.12.2
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71

  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  (foamfix-0.10.10-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  optifine (OptiFine_1.12.2_HD_U_F5)

[crash report](https://pastebin.com/PDDdZX8S)

**Comment by McJty** [comment]
Was one of the mods (Aether or rftools dimensions) added later or were both mods there since the beginning?

**Comment by alexHunter854** [comment]
The aether was added later

**Comment by McJty** [comment]
That's most likely the problem. RFTools Dimension was already using a certain dimension and then aether later claimed that dimension. Best way to solve this is to reassign the aether dimension id to some other number (in the aether config)

**Comment by alexHunter854** [comment]
Thanks, that worked
