### ISSUE TITLE
Time Absorber Waila Integration Not Working

### ISSUE THREAD

**Issue by whitebear60** [McJty/RFToolsDimensions#295]
Issue description: 
When Time Absorber's progress changes, information in Hwyla not updates. You need break it and place in the world again to update information in Hwyla.

Steps to reproduce: 
1. Place Time Absorber in world
2. Provide a Redstone Signal to it
3. Hover a mouse on Time Absorber.

Video Demonstration: https://youtu.be/9NMMmslES4o

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71
* Modpack: Project Ozone 3
* Project Ozone 3 Version: 3.3.59

**Comment by McJty** [comment]
That's not The One Probe. That looks like Waila or something similar

**Comment by whitebear60** [comment]
Yes, I forgot. We have Hwyla 1.8.26-B41 with Wawla 1.12.2-2.6.275

**Comment by whitebear60** [comment]
I think that it should be reported to Hwyla's repository, right?

**Comment by McJty** [comment]
No, this is actually a bug in RFTools. Unfortunatelly I no longer work on 1.12 so it's not likely that this will get fixed
