### ISSUE TITLE
Server crashes after entering dimension in Mc.Eternal

### ISSUE THREAD

**Issue by kiangribi** [McJty/RFToolsDimensions#297]
Issue description: When I create a dimension and try to enter it, it takes a few seconds until the server crashes. the server also instantly crashes again if a player join so I assume the problem is the player being in the dimension somehow. To fix, I have to restore an older backup. I tried this multiple times now and it seems to be a consistent bug.

Steps to reproduce: Create a random dimension. Teleport using the transmitter. Wait some seconds.

Versions:
* Minecraft: 1.12.2
* Modpack: MC.Eternal 1.3.7.1
* RFTools: 1.12-7.73
* RFToolsDimension: 1.12-5.71 

Relevant logs, if any: 
[crash-2020-08-19_21.53.43-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/5099600/crash-2020-08-19_21.53.43-server.txt)

I hope we find a solution to this bug and thanks in advance :D
Kian

**Comment by McJty** [comment]
It's crashing in Nature's Aura. Please report to that mod
