### ISSUE TITLE
Server Crashes when player enters dimension, Ticking World Exception.

### ISSUE THREAD

**Issue by Keegasaur** [McJty/RFToolsDimensions#300]
Issue description: Created a baseline dimension, without dimlets. The dimension generated without a Matter Receiver, and I had to add one using the Dimension Editor. After dialing the receiver I attempted to teleport to the dimension using a Matter Transmitter, server immediately crashed.

Thinking it was possible that the dimension was corrupted somehow, I tried to generate another dimension, adding the Flat Terrain dimlet. Upon teleporting, the server immediately crashed again. 

Steps to reproduce: Create dimension, attempt to teleport to dimension.

Notes: The mod files have been untouched since a server reset, meaning that we ran a world before hand with the same files and dimensions functioned fine in that world.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* McJtyLib: 3.5.4
* RFTools: 7.73
* RFTools Dimensions: 5.71

Crash log, including mod list: https://pastebin.com/eYwHNQd9

**Comment by McJty** [comment]
Caused by:

	at com.gw.dm.util.DMGenerationHandler.generateTraps(DMGenerationHandler.java:45)
	at com.gw.dm.util.DMGenerationHandler.generate(DMGenerationHandler.java:37)

Not sure what mod that is but that's not a bug in RFTools Dimensions. Actually this is probably Dungeon Mobs. Report to them
