### ISSUE TITLE
[1.16] Dimensions must be lowercase alphanumeric names only

### ISSUE THREAD

**Issue by Demonly** [McJty/RFToolsDimensions#303]
Just an issue, trying to assist in anyway possible finding bugs in development, you may know this already.
- Create a dimension with `Test1`
- Upon energizing the dimension the game will crash.

This is due to the dimension having a capital T in the name, same goes with all other non alphanumeric/capital characters

**Comment by McJty** [comment]
Oh good find. I'll fix this. And thanks for checking this

**Comment by Demonly** [comment]
This is fixed by latest commit. Nice work!

![image](https://user-images.githubusercontent.com/5571347/106533474-3d4eb980-64c0-11eb-9914-d2cb05e3986e.png)

**Comment by 7eggert** [comment]
Also purely numerical dimension names may cause problems, Xaeros (Mini)maps display an error instead of "8".
