### ISSUE TITLE
[1.16.5] Unable to delete dimensions

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsDimensions#305]
Issue description:

I'm unable to delete dimensions created by this mod. There's no command to do it and erasing it from the 'dimensions' folder in the world save just causes the folders to reappear once minecraft reopens. (Also I know it's a beta version, so there's a high chance it's just not implemented yet)

Steps to reproduce:
1. Close Minecraft
2. Delete profile/saves/world/dimensions/rftoolsdim/dimension
3. Open Minecraft

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.14
* McJtyLib: 1.16-5.0.16
* RFTools: rftoolsbase-1.16-2.0.9
* RFTools Dimensions: commit 63242cd3004f9d3f6fe5e812af5914b33fd1cf01

Possibly incompatible mods:
* Optifine 1.16.5 HD U G6

Relevant logs, if any: 
N/A

**Comment by McJty** [comment]
This is indeed not implemented yet (and to be honest, with how dimensions work in 1.16 it's also extremely hard to implement)

**Comment by ghost** [comment]
I figured out how to delete dimensions manually by editing the world nbt and such. It's probably not the safest way to do it at all, but hey. I'll close this issue myself, but feel free to reopen it if it helps you in any way. Thanks for your hard work!
