### ISSUE TITLE
[1.16.5] Server crash on loot table queue

### ISSUE THREAD

**Issue by sudrakoder** [McJty/RFToolsDimensions#311]
Issue description: 
Server crash during dimlet loot table test.
--
java.lang.NoSuchMethodError: net.minecraft.loot.LootContext.getQueriedLootTableId()
	at mcjty.rftoolsdim.modules.dimlets.lootmodifier.LootTableCondition.test(LootTableCondition.java:29) ~[rftoolsdim:1.16-7.0.1-beta] {re:classloading}
--
Full crash log: https://pastebin.com/qcWQjUAJ
--

Versions:
* Minecraft: 1.16.5
* Forge: forge-1.16.5-36.0.10
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.15
* RFTools: rftoolsbase-1.16-2.0.9
* RFTools Dimensions: rftoolsdim-1.16-7.0.1-beta

**Comment by N0xZz** [comment]
I could fix the same issue on my server updating both mcjtylib and rftoolsbase to the newest available version.

**Comment by McJty** [comment]
Update forge
