### ISSUE TITLE
Kicks a player when a dimension is visited

### ISSUE THREAD

**Issue by NakuKoro** [McJty/RFToolsDimensions#312]
Issue description: Kicks a player when a dimension is visited (FTB University 1.1.1)

Steps to reproduce: When a player visits a dimension the player gets kicked out after 10 seconds or so 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.4
* RFTools: 7.73
* RFTools Dimensions: 5.71

Possibly incompatible mods: 

Relevant logs, if any: 
https://pastebin.com/wNNCwqWu

**Comment by McJty** [comment]
Seems to be caused by another mod:

svenhjol.charm.world.feature.SpectreHaunting

Not sure what mod that is though. Maybe report to them?

**Comment by NakuKoro** [comment]
After I deleted that mod it got fixed! Thank you so much!
