### ISSUE TITLE
Resercher does not drop

### ISSUE THREAD

**Issue by PatrickZ1** [McJty/RFToolsDimensions#314]
Issue description: When the Researcher gets destroyed (either with the Smart Wrench or any other tool) it doesn't drop the block.

Steps to reproduce: Place a researcher and destroy it (with a wrench or any other tool) -> no item drop

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.42
* McJtyLib: 1.16.5-5.0.16
* RFTools Base: 1.16-2.0.10
* RFTools Dimensions: 1.16-7.0.2-beta

I noticed it while trying it by including it into the modpack "Enigmatica 6 - E6 -1.16.5". So there may be some incompatibilities.

**Comment by McJty** [comment]
Fixed now
