### ISSUE TITLE
[1.16.5] No bedrock generating at bottom of world.

### ISSUE THREAD

**Issue by alucard87pl** [McJty/RFToolsDimensions#315]
I am having trouble creating a Dimension with the first layer being bedrock. I've experimented with a few world types and other dimlet combinations, but haven't had any luck.

Any advice? I may be doing something wrong.

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.43
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: 1.16-5.0.16
* RFTools: 1.16-2.0.10
* RFTools Dimensions: 1.16.-7.0.2-beta

**Comment by McJty** [comment]
Was not implemented yet. Will be fixed next release

**Comment by ravek162** [comment]
hello, can You tell me when You will fix it ? :D

**Comment by McJty** [comment]
It's already fixed
