### ISSUE TITLE
Crashed when looking in full compact storage barrel with a bunch of dimlets

### ISSUE THREAD

**Issue by AdnanuReeves** [McJty/RFToolsDimensions#316]
Issue description: 
MAde my enderman farm, put all the dimlets in the barrel til it got full and the game crashed.

Steps to reproduce: 

Versions:
1.16.5
latest of all your mods
latest forge

https://paste.ubuntu.com/p/BRh52fwcbf/

**Comment by AdnanuReeves** [comment]
After looking into it some more it seems it happens when I look on some specific dimlets, but I crash before I can see which ones :/

**Comment by McJty** [comment]
I'll check it out

**Comment by Bidgam** [comment]
Same for me, but unfortunately I'm not sure what icons are in the dimlet as it crashes immediately upon hovering over that dimlet.

**Comment by McJty** [comment]
Should be fixed now

**Comment by Bidgam** [comment]
Thanks. I donated to your project, great work on it.
