### ISSUE TITLE
Creating a random dim ties it to the first random I created

### ISSUE THREAD

**Issue by Bidgam** [McJty/RFToolsDimensions#319]
MC 1.16.5 on RFToolsDimensions - 1.16-7.0.1-beta.

I created a random world, let the system generate it, and then I created another and it just tied it to the first world (though interestingly the tick rate was a couple of points different, but it did say and go to the first world).

**Comment by McJty** [comment]
That's normal and how it is supposed to work. The sequence of dimlets you use to create a dimension is the exact identifier for that dimension. The same dimlets will always result in exactly the same dimension. That's why there are digit dimlets
