### ISSUE TITLE
Config setting for Beds not working

### ISSUE THREAD

**Issue by Khazadir** [McJty/RFToolsDimensions#32]
Made a random world (my first one, it works).

Put a bed down, tried to sleep, it blew up.

The config file says nothing should happen (setting 0).

I changed the config file to setting 2 (save spawn point), and tried again.

It blew up again.

This is using version rftoolsdim-1.10-4.30beta48.

**Comment by McJty** [comment]
Partially reimplemented this. Setting spawn is not yet implemented but beds no longer explode by default. For next version
