### ISSUE TITLE
Missing texture of molten osmium in dimensions

### ISSUE THREAD

**Issue by Throwtex** [McJty/RFToolsDimensions#320]
Issue description: 
We created a dimension with molten osmium lake, and the texture is missing. Causing masive FPS drop. Is there anyway to fix this, or work around it? Playing MC eternal 1.3.7.1

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2947
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71

**Comment by McJty** [comment]
Are you sure it is that texture that is causing the fps drop? That would be weird.
Anyway, seems the problem is with the molten osmium from mekanism then

**Comment by Throwtex** [comment]
> Are you sure it is that texture that is causing the fps drop? That would be weird.
> Anyway, seems the problem is with the molten osmium from mekanism then

Had similar issue with some dragon steel fluid missing texture, and when the entire world is the pink/black block it had the same massive fps drop. So we just assumed that is whats causing it. 
![image](https://user-images.githubusercontent.com/70971566/109804571-aee66880-7c22-11eb-8d9b-bbf4bc5b6c0a.png)
Found out now that it is fluid from moar tinkers thats missing the texture.
