### ISSUE TITLE
No dimlets spawning in RF Dimensions buildings/chests

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJty/RFToolsDimensions#323]
I'm playing the latest version of MC 1.16.5 and this mod. I've probably created 50 test dimensions so far, and I've only ever gotten knowledges from the chests inside the RF Dimension buildings.

I got 2 dimlets from a jungle dungeon. Is this supposed to be that way? I remember in 1.12.x I've gotten dimlets non stop when inside rf dimensions.

https://pastebin.com/4F0PeA2R

**Comment by McJty** [comment]
They do still spawn but they are more rare now as you are actually supposed to construct dimlets and not just find them

**Comment by Unrepentant-Atheist** [comment]
That's fine and dandy, but they're extremly rare now. Maybe make them a low drop chance from uncommon, rare and legendary blobs?

Can't craft the lost cities dimlet for example, since I never have seen it in my overworld... :(

**Comment by McJty** [comment]
That dimlet doesn't exist yet. Not everything has been ported so far

**Comment by McJty** [comment]
Improved dimlet generation in dimlet huts
