### ISSUE TITLE
Researcher I/O slot issue (potentially)

### ISSUE THREAD

**Issue by IamStig** [McJty/RFToolsDimensions#327]
Issue description: Researcher knowledge not able to be automated due to slots not designated correctly 

Steps to reproduce: Place a hopper, put researcher on top (power not required), knowledge passes from "input" slot to hopper. I could be wrong but shouldn't a hopper only pull from the output slot?

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.46
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.18
* RFTools: 
* RFTools Dimensions: rftoolsdim-1.16-7.0.4-beta

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by DizzyDJW** [comment]
Same issue. I've noticed that the Researcher block **_NEEDS_** an auto output, to the top or bottom, if it's going to be allowed to hold a stack of items.

It currently outputs all items inside the researcher including the stack of yet-to-be-researched items, no matter the side.

**Comment by McJty** [comment]
Will be fixed next release
