### ISSUE TITLE
Game Crash Due To Plants Being a Thing

### ISSUE THREAD

**Issue by shutdoor** [McJty/RFToolsDimensions#328]
Issue description: Game Crash On Random Dimension Generation

There seems to be a common issue where plants will spawn as the filler for a dimension and it will proceed to crash the game. I've provided an image of this happening with a Thermal Plant.

![2021-03-11_21 04 06](https://user-images.githubusercontent.com/5362239/110891038-5ceeb400-82ae-11eb-9552-b18ef690a2ee.png)

**Comment by McJty** [comment]
Version and crashlog please!

**Comment by shutdoor** [comment]
The Version is 1.16-7.0.4-beta, and for some reason, a Crash Log didn't actually generate.

**Comment by McJty** [comment]
Show me your logs then. Anything. Otherwise I can't really do much
