### ISSUE TITLE
Ticking block entity - server crash loop

### ISSUE THREAD

**Issue by Stat1c-V01D** [McJty/RFToolsDimensions#329]
Issue description: 
After generating a couple of dimensions on the server it sometimes happens that the Dimension Builder that's currently keeping this dimesion alive thows an error when trying to maintain the dimension tick.
The server then gets stuck in a crash loop where its loading until the point where the dimension should be loaded.
A solution to that for now is related to Issue #326 where when I delete the "RFToolsDimensions.dat" and restart the server everything is fine and I am getting teleported to that dimension.

Steps to reproduce: 
It happens pretty random but usually after creating and teleporting to a couple of dimensions.

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-36.0.45
* McJtyLib: 1.16-5.0.17
* RFTools: 1.16-2.0.10
* RFTools Dimensions:  1.16-7.0.4-beta

Relevant logs, if any: 
https://pastebin.com/5Ps2A739

**Comment by McJty** [comment]
Already fixed in the latest version

**Comment by Stat1c-V01D** [comment]
Thanks I'll communicate that to my players and will update the server!
