### ISSUE TITLE
[1.10.2] [Bug] Dimlets do not seem to be used

### ISSUE THREAD

**Issue by Dijkstra1-zz** [McJty/RFToolsDimensions#33]
![2016-09-07_00 37 50](https://cloud.githubusercontent.com/assets/11648771/18306423/517496c0-74db-11e6-9246-82dfeb8c5012.png)

This dim was made the time noon dimlet, and structure none also the biome checker was use and none of these seem to working the flat one is working but not all of dimlets are seeming to work.

**Comment by McJty** [comment]
Can you give me the exact sequence of dimlets that was used?

**Comment by Dijkstra1-zz** [comment]
No easily to check now, but I can remember some so of the them but not he order, checker biome extreme hills and extreme hills +, time noon, flat, feature ore gen, clean, effects none, structure none, there may have been one or two more will list them in order when can.

**Comment by McJty** [comment]
How do you know checker isn't working?

**Comment by Dijkstra1-zz** [comment]
I have flown around quite a lot with F3 up, and all the time the it the same, and in 1.7.10 on the map you could actually see it, maybe not with two biomes similar but gone in a straight for about 20 chunks with no biome change, or maybe it works different to how it did in 1.7.10, I know it works that cant be sure but i think it 2x2 chunks of biome in a check pattern with another biome

**Comment by McJty** [comment]
You can see the current biome you are in with F3. Please check with that to confirm that it is not working. Extreme Hills and Extreme Hills+ are very similar. It is very possible that it is working fine but that you cannot see the difference

**Comment by Dijkstra1-zz** [comment]
Yes I using was F3, I know journeymap can be bit slow at updating the biomes, can you confirm the checker broad size, that way I will know if gone x chunks and biome has not changed there is something wrong, then i can fly around again just to be sure but can not do that now.

**Comment by McJty** [comment]
Checker makes a checkerboard of 2x2 chunks

**Comment by Dijkstra1-zz** [comment]
Here are my dimlets in order
- Feature Clean - working if it does wath i think it does
- Terrain Flat - work
- Biome Extrem Hills+ - maybe working might be down to checker
- Biome Extrem Hills - working
- Controller Checker - not working
- Feature oregen - working if it does wath i think it does
- Structure None - not working (getting dimlet shop(with ghost dimlet prats))
- Time noon - not working 

As for checker I can confirm it is not working:
[![](http://img.youtube.com/vi/jAS72S7w3cs/0.jpg)](https://www.youtube.com/watch?v=jAS72S7w3cs)

**Comment by McJty** [comment]
Question, was this on a server?

**Comment by Dijkstra1-zz** [comment]
Yes

**Comment by McJty** [comment]
Check again with latest version

**Comment by McJty** [comment]
Just hold on. Next version will also fix the checkerboard problem
