### ISSUE TITLE
Putting Unknown Dimlets into Researcher Causes Crash

### ISSUE THREAD

**Issue by DizzyDJW** [McJty/RFToolsDimensions#330]
**Issue description:**
Shift-Clicking Unknown Dimlets into Researcher block causes a crash.

**Steps to reproduce:** 

1. Have Unknown Dimlets in Inventory
2. Open Researcher GUI
3. Shift-Click Dimlets into Researcher

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.7.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.0.17
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.4

Relevant logs, if any: https://pastebin.com/D26qyTUx

**Comment by McJty** [comment]
Fixed next release
