### ISSUE TITLE
Can't Create New Realized Dimensions, Old Name is Kept After Extracting and Storing Regardless of New Name

### ISSUE THREAD

**Issue by DizzyDJW** [McJty/RFToolsDimensions#331]
**Issue description:**
Any new "Realized Dimensions" made retain the exact same name as the first one you make regardless of what you put into the name field. I had one named "rnddim" I extracted it and tried to put in a new name but anytime I click store it puts "rnddim" back into the name field and retains the EXACT same dimension.

**Steps to reproduce:** 

1. Place Empty Dimension Tab into Enscriber
2. Name and Store Tab
3. Extract and attempt to change name and store once again
4. Name from before is kept, as well as dimension

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.7.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.0.17
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.4

Relevant logs, if any: https://pastebin.com/D26qyTUx

**Comment by McJty** [comment]
The same dimlet sequence (in your case no dimlets) ALWAYS results in exactly the same dimension. It's the unique identifier of a dimension. By doing that you can create multiple dimension tabs that point to the same dimension. Also you can't change the name of a dimension so that's why it turns back. So working as expected. Use digit dimlets to create new random dimensions

**Comment by DizzyDJW** [comment]
> The same dimlet sequence (in your case no dimlets) ALWAYS results in exactly the same dimension. It's the unique identifier of a dimension. By doing that you can create multiple dimension tabs that point to the same dimension. Also you can't change the name of a dimension so that's why it turns back. So working as expected. Use digit dimlets to create new random dimensions

Well see the issue I had with that dim was that the **ONLY** loot spawning in **EVERY** chest after checking idk how many, was **EXACTLY** the same. 1 Common Knowledge in the middle row, and 2 right under that. **NOTHING** else. I looked in at least 20 chests and that exact loot was in every one.

Can you consider making it so that Dimension Tabs without dimlets can be randomized over and over. So we don't get stuck with a broken first dimension?

**Comment by McJty** [comment]
No that's not possible. I can't change the system like that. However what's the problem? Just make digit dimlets? They are craftable without anything special using regular crafting recipes

**Comment by McJty** [comment]
BTW, not sure what's up with the dimlet loot though. I can't reproduce that

**Comment by DizzyDJW** [comment]
> BTW, not sure what's up with the dimlet loot though. I can't reproduce that

Okay so now it's **_EVERY_** dimension I have created so far has the **_EXACT_** same loot table.

Every chest in every hut inside every dimension looks like this:

![Screenshot 2021-03-13 181849](https://user-images.githubusercontent.com/26727521/111052428-af53e000-8428-11eb-9c63-4727b83a167e.png)

**Comment by McJty** [comment]
I can reproduce this problem. I will check it out now

**Comment by McJty** [comment]
Found the problem. Will be fixed next release
