### ISSUE TITLE
Only 1 random unique dimension per world??

### ISSUE THREAD

**Issue by the-creamster** [McJty/RFToolsDimensions#332]
Issue description: After seeing Direwolf20's video yesterday when he dipped his toes into the dimensions mod(he only explored 1 randomly generated unique dimension) while mentioning there was a pack update at the same time. So today i decided to dip my toes into it in SP first only to discover that in no way possible i was able to create more than 1 random unique dimension. I even tried creating them in different enscribers but the name of the first one got auto-magically pasted in place of what i put in the text box.

Versions:
* Modpack: FTB custom client Direwolf20 v1.7

**Comment by McJty** [comment]
That's normal. Use digit dimletsv to make new unique dimensions.
