### ISSUE TITLE
Game crash on returning to overworld from dimension

### ISSUE THREAD

**Issue by fille021** [McJty/RFToolsDimensions#335]
Issue description: 
Game crashes after I return from a dimension

Steps to reproduce: 
Every once in a while game crashes when returning from dimension, not going to it

Versions:
* Minecraft: 1.16
* Forge: 36.0.45
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.0.17
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.4

Possibly incompatible mods: 
optifine

Relevant logs, if any:

**Comment by McJty** [comment]
I need a crashlog. And please try if you can reproduce this without optifine. There are reports of optifine doing weird things with worldgen

**Comment by McJty** [comment]
You can give me a crashlog?
