### ISSUE TITLE
Weird chunk generation after logging off from the world

### ISSUE THREAD

**Issue by hodo1962** [McJty/RFToolsDimensions#338]
Issue description:
I generated a new dimension with the following setting:
atrribute: default
terrain: normal
feature: none
time: day
biomecontroller: default
digit: 1
I teleported into the dimension and everything was as expected. After logging off and on, the normal chunk generation stopped and produced a waterworld with a bedrock - deep ocean with parts of land floating on it.

![2021-03-18_12 59 36](https://user-images.githubusercontent.com/69686049/111624867-8185e700-87ec-11eb-8ed3-4ba80422faa6.png)

I've tested this with another world. Before logging out i moved 5000 Blocks in each direction and the chunk generation stayed 
totally normal. After logging of and on, the world became as decribed above.

Steps to reproduce: 
- Generated more worlds with the same settings (but different digits)
- same thing happened

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.16-5.0.19
* RFTools: 1.16-2.0.10
* RFTools Dimensions: 1.16-7.0.5-beta

Modlist:
  [✔️] jei-1.16.4-7.6.1.71
  [✔️] mcjtylib-1.16-5.0.19
  [✔️] Mekanism-1.16.5-10.0.21.448
  [✔️] MekanismAdditions-1.16.5-10.0.21.448
  [✔️] MekanismGenerators-1.16.5-10.0.21.448
  [✔️] MekanismTools-1.16.5-10.0.21.448
  [✔️] rftoolsbase-1.16-2.0.10
  [✔️] rftoolsbuilder-1.16-3.0.16
  [✔️] rftoolsdim-1.16-7.0.5-beta
  [✔️] rftoolsstorage-1.16-2.0.11
  [✔️] rftoolsutility-1.16-3.0.25
  [✔️] Xaeros_Minimap_21.4.2_Forge_1.16.5
  [✔️] XaerosWorldMap_1.12.2_Forge_1.16.5

I've tested it with Journeymap before - that changed nothing.

**Comment by McJty** [comment]
Hmm, you don't have the latest version of RFTools Dimensions though. Maybe something got corrupted

**Comment by hodo1962** [comment]
Will test it with the latest version an report here.

I've changed the version to 1.16-7.0.6 - nothing changed.

**Comment by McJty** [comment]
I actually managed to reproduce this. I'll try to figure out what's going on

**Comment by McJty** [comment]
Fixed in 7.0.7
