### ISSUE TITLE
Liquid Spheres & Liquid Cubes Feature Dimlets have conflicting recipes

### ISSUE THREAD

**Issue by TheDieselPunk** [McJty/RFToolsDimensions#339]
Issue description: It is impossible to craft the Liquid Spheres and Liquid Cubes feature dimlets in the Dimlet Workbench, as they have the same recipe as their Hollow counterparts.

Steps to reproduce: 
Try to craft the Liquid Spheres or Liquid Cubes feature dimlets.

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.0
* McJtyLib: mcjtylib-1.16-5.0.19.jar
* RFTools: rftoolsbase-1.16-2.0.10.jar
* RFTools Dimensions: rftoolsdim-1.16-7.0.6-beta.jar

Some footage of the issue in action: https://i.imgur.com/n8CLHjq.gif

**Comment by McJty** [comment]
Fixed next release
