### ISSUE TITLE
(Feature Request) "Old Style" Dimensions from original RF Tools?

### ISSUE THREAD

**Issue by Vaygrim** [McJty/RFToolsDimensions#34]
I'm sorry, I've tried your new and improved Dimlet workbench and it is borderline unusable. The list of dimlets on the right can't be scrolled with a mouse wheel or arrow keys, and the scroll bar for it is SO TINY that mearly breathing on it results in it scrolling 14 pages.

To make matters worse it's near impossible to actually locate dimlets that USED to exist in the old system. I can't change the sky color anymore. I can't fix the sun at eternal noon, or eternal dawn, nothing seems to work, and I'm really behind schedule. I need to be able to, in creative mode, easily grab whatever dimlet I need for a particular dimension feature / detail.

Can you please help me?

**Comment by McJty** [comment]
The fact that it cannot be scrolled with mousewheel is actually a recent bug introduced in McJtyLib and I'm aware of that. It was scrollable before.

Things like sky color and such are not implemented yet in the new RFTools Dimensions. There are still a few missing gaps that I have to reimplement/port from the old rftools.

Note that the list in the dimlet workbench can be searched.

BTW, /rftdb listdimlets shows a list of all available dimlets in the console

Also to make dimlets you could also try: /rftdb createdimlet

For example, to make the 'eternal noon' dimlet you can do:

/rftdb createdimlet Time Noon

I can help you giving commands for all dimlets you want to help you further here. Ok?

**Comment by Vaygrim** [comment]
A comprehensive list of commands (and formatting) would be immensely useful yes, as the existing slash commands just don't provide enough detail of explanation regarding syntax.

**Comment by McJty** [comment]
https://github.com/McJty/RFTools/wiki/RFTools-Commands-1.10.2
