### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by Shyzle** [McJty/RFToolsDimensions#343]
Issue description: 
Server crashes after load.

Steps to reproduce: 
made a realized dimension tab with biome controller dimlet: default > biome dimlet: prairie > block dimlet: uranium ore > biome dimlet: mountains > block dimlet: iron block > feature dimlet: sphere > block dimlet: coal block > feature dimlet: sphere > block dimlet: redstone block > feature dimlet: sphere > digit dimlet: 6 > digit dimlet: 9

Powered the dimension and crashed on going into the dimension. Server crashes on load.

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.45
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.0.17
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.4-beta

Possibly incompatible mods: 

Relevant logs, if any: 
[crash-2021-03-29_00.23.45-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/6219501/crash-2021-03-29_00.23.45-server.txt)

**Comment by McJty** [comment]
Update. That version of RFTools Dimensions is too old
