### ISSUE TITLE
RFTools Server crash

### ISSUE THREAD

**Issue by SirEndii** [McJty/RFToolsDimensions#348]
Issue description:
Since I did not cause the error, I can only report what happened to a user of my modpack. I'm sorry if anything is unclear. 
A user built a dimension using the dimension builder and then the server crashes.

Steps to reproduce: 
1. Creating a dimension with the dimension builder
2. Use the same name(I think that he uses the same name because of the message in the crash)

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.4
* CompatLayer (only if on Minecraft 1.10 or 1.11): **N/A**
* McJtyLib: 1.16-5.0.19
* RFTools: 1.16-2.0.10
* RFTools Dimensions: 1.16-7.0.7-beta 

Relevant logs, if any: 
Crash stacktrace: https://paste.myst.rs/iyxidsjd
I could send a full log is necessary.

**Comment by McJty** [comment]
Fixed in the next release
