### ISSUE TITLE
Ticking Block Entity

### ISSUE THREAD

**Issue by disTroiT69** [McJty/RFToolsDimensions#350]
Issue description: 

Trying to create a liquid sodium dimension from Mekanism in 1.16 DW20 Pack

Dimlits used and in order :

Fluid Dimlit : Liquid Sodium (Mekanism)
Terrain Dimlit : Flat
Biome Dimlit : Ocean
BIome Controller Dimlit : Default

Steps to reproduce: 

Put those dimlits in the same order as I did

Versions:
* Minecraft:  1.16.5
* Forge: 36.1.4
* McJtyLib: 5.0.19
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.7

Relevant logs, if any: 

https://pastebin.com/KAbw8dKY

**Comment by McJty** [comment]
I'm working on a solution for this

**Comment by McJty** [comment]
Fixed in the next release
