### ISSUE TITLE
[1.16.5] RfToolsDim doesn't support Draconic Evolution blocks

### ISSUE THREAD

**Issue by Peca21** [McJty/RFToolsDimensions#352]
Issue description: 
RFTools Dimensions doesn't support draconic evolution. The mod is not out on curseforge for 1.16.5 but you can download it from Brandons discord or you can build it from github (which is what I did). Also I tried to add it myself like described in the config, but it doesn't work.

**Comment by McJty** [comment]
So how exactly did you add it? What didn't work about it?

**Comment by Peca21** [comment]
I read in the rftoolsdim-server.toml 
#This is a list of dimlet packages that will be used. Later dimlet packages can override dimlets defined in earlier packages. You can place these packages in the 'config/rftoolsdim' folder
So I added my json to config/rftoolsdim folder and added the file to a config like this
dimletPackages = ... , "biomesoplenty.json", "draconicevolution.json"]
thinking that would work but it didn't.

I wrote my JSON by copying one of already written JSONs from github (from /src/main/resources/data/rftoolsdim/dimletpackages/)

Here is a small part of the log where rftools is loading JSON files. My file is not loaded
https://pastebin.com/GTJTWXa0

I wanted to make a draconium ore dimlet but it didn't work because that dimlet doesn't exist so I tried adding them.

**Comment by exampol** [comment]
Yeah I had the same problem: https://github.com/McJtyMods/RFTools/issues/1578#issuecomment-854101107

**Comment by jebjordan** [comment]
any updates to this?

**Comment by McJty** [comment]
Sorry. Have been very busy

**Comment by McJty** [comment]
I have fixed this and will release the fix this weekend
