### ISSUE TITLE
Sky Dimlets + some terrain Dimlets missing in Direwolf20 pack for MC1.16

### ISSUE THREAD

**Issue by pionearly** [McJty/RFToolsDimensions#353]
Issue description: 
It appears to be impossible to acquire any dimlets concerning sky features and the only biome controllers available seem to be single, checker and normal. Tested in survival by running an enderman farm over several hours and analysing all the dropped knowledge pieces.

Is this expected behaviour due to the current version of the mod or a bug? The changelog.txt was not very informative for this particular issue but was checked.

Steps to reproduce: 
Play the aforementioned pack and try to acquire the dimlets mentioned above.
Versions:
* Minecraft: 1.16
* Modpack: FTB Presents Direwolf20 1.16 (ID: 79) V1.10.1
* Launcher: ATLauncher
* Forge: 36.1.23
* McJtyLib: 5.0.19
* RFTools: 2.0.10
* RFTools Dimensions: 7.0.9-beta

Possibly incompatible mods: Optifine is installed

**Comment by McJty** [comment]
They are not implemented yet

**Comment by pionearly** [comment]
Alright, suspected as much but had a hard time finding a list of implemented stuff. Thanks for the quick reply though!
