### ISSUE TITLE
Dimlet packages not working

### ISSUE THREAD

**Issue by MichelJonkman** [McJty/RFToolsDimensions#355]
Both the config setting and the overrides don't work for me.

Versions:

Minecraft: 1.16.5
Forge: 36.1.23
McJtyLib: 5.0.19
RFTools: 2.0.10
RFTools Dimensions: 7.0.9

**Comment by McJty** [comment]
Show me what you did. Without more information I can't do much

**Comment by MichelJonkman** [comment]
[rftools.zip](https://github.com/McJtyMods/RFToolsDimensions/files/6625830/rftools.zip)
These are the configs I used

**Comment by DaFuJosh** [comment]
i have the same issue with all the mods 6 Pack: 1.6.9
got server log of error when trying to find craft dimlets also crafting recipes in the workbench dont show or work when searching for ore or that and clicking for it

**Comment by DaFuJosh** [comment]
[latest.log](https://github.com/McJtyMods/RFToolsDimensions/files/6638478/latest.log)

**Comment by DaFuJosh** [comment]
towards end errors begin

**Comment by McJty** [comment]
Sorry for slow response but I found the bug and it will be released this weekend
