### ISSUE TITLE
Server crashing from randomly generated lit TNT dimension

### ISSUE THREAD

**Issue by SylphicXen** [McJty/RFToolsDimensions#358]
Issue description: A randomly generated (no dimlets aside from digit dimlets) dimension resulted in the multiplayer server I was playing on crashing. Further investigation showed me that the dimension was filled with lit TNT which exploded immediately.

Steps to reproduce: While I'm not sure how to reproduce this due to it being caused by a randomly generated dimension, I can tell you the steps that led up to this.
* Was randomly generating dimensions to explore and loot; made 2 dimensions prior with no issues at all
* Third generation was made with digit dimlets 1, 1, and 2
* Finished the dimension tab in the enscriber, no issues yet
* Put the dimension tab into the dimension builder and it crashed the moment the builder hit 100%
* After server came back up, decided to try entering the dimension to see if there was an issue with it which would need to be resolved by an admin
* After entering the dimension, the first and last thing that I saw was lit tnt everywhere around me. When the tnt exploded, the server crashed again.
* After the server came back up again, I could no longer enter the server because anytime I did, it would immediately crash the server again.
* Had to have an admin move my character back to the spawn. After that, the crashes stopped. They didn't delete that dimension until half a day later, but as far as I'm aware no other crashes occurred after I was moved back to spawn.

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.23
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.16-5.0.19
* RFTools: 1.16-2.0.1.0
* RFTools Dimensions: 1.16-7.0.9-beta

Possibly incompatible mods: 
* I did have OptiFine enabled, but the crash was server-wide and not client-sided.

Relevant logs, if any: 

* Unfortunately, since this took place on a multiplayer server that I am not a staff member for, I don't have access to the logs for this.

**Comment by McJty** [comment]
Fixed this some time ago
