### ISSUE TITLE
Can't use Thermal Foundation blocks as material for dimlets

### ISSUE THREAD

**Issue by Nearius-River** [McJty/RFToolsDimensions#359]
Issue description: It's basically what the title says, it seems that there's no way of using Thermal Foundation blocks as materials to create worlds (like copper block, tin, etc), and this is a problem, because I can't get the materials required for mods that need massive quantities of resources (like Avaritia). I tried adding manually on the mod configuration file, however, I don't know if I am doing it wrong or there's no compatibility to add other types of blocks.
Steps to reproduce: N/A

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71

Possibly incompatible mods: OptiFine

Relevant logs, if any: N/A

**Comment by McJty** [comment]
So what did you do? I can't debug your attempt if you are not showing it to me

**Comment by Nearius-River** [comment]
This is how I am doing it: https://i.imgur.com/auFUo8G.png
Since Thermal uses the same name for some stuff, I thought using block_name:id would work.

**Comment by Nearius-River** [comment]
Update: I have found a solution to this, and now I managed to add the blocks/ores manually without problems.

**Comment by ramonGonzEdu** [comment]
You should actually post the solution, but I assume its that you;re missing the modid in the list (since its only implied for vanilla items)
