### ISSUE TITLE
Dimension generation completed, but upon loading with player it (eventually) crashes

### ISSUE THREAD

**Issue by Bidgam** [McJty/RFToolsDimensions#362]
Issue description: I step into the new dimension with a player character and after it starts loading the area, it eventually crashes. Suspect some mod's building is causing a conflict. This is after updating all the RF mods to their latest version from a version prior.

* Minecraft: 1.16.5
* Forge: forge-1.16.5-36.1.32
* McJtyLib: mcjtylib-1.16-5.0.21
* RFTools: rftoolsbase-1.16-2.0.11
* RFTools Dimensions: rftoolsdim-1.16-7.0.11-beta

Crash log: https://paste.enginehub.org/Z4QCSzRW6

Note that it hasn't caused this before with dimension creation, so maybe an unlucky mix or something's wrong in the generation. I can try to create more dimensions to test if needed.

**Comment by McJty** [comment]
This may indeed be some unlucky interaction with another mod. I see this in the stacktrace:
	at vazkii.quark.content.world.block.SpeleothemBlock.func_220069_a(SpeleothemBlock.java:85) ~[quark:r2.4-314] {re:classloading}

Can you try a new world?

**Comment by Bidgam** [comment]
I tried two other worlds and they seem to work fine, so no worries. If I
can track what's happening in some future crash, I'll let you know.

Only thing that I used this time was a Flower Forest Biome dimlet.
