### ISSUE TITLE
RFTools ignores world config

### ISSUE THREAD

**Issue by glencoe2004** [McJty/RFToolsDimensions#363]
Issue description: 
RFtools will ignore the world config and keep the default one, at least when dealing with power for the Phased Field Generator and custom dimlet packages. 

Steps to reproduce: 
1. Start a new world, save and exit to title (restarting the game does nothing)
2. Go into 'rftoolsdim-server.toml' for that world
3. Change `phasedFieldMaxRF` to 5000000 and `phasedFieldRFPerTick` to 50000
4. Go back into the world and observe that the PFG is still stuck at default values. Interestingly, the sprite for the PFG displays the correct value, and even a 'fully charged' (1000000 RF) PFG displays a red low charge sprite.

As mentioned above, trying to load custom dimlet packages via the .toml also won't work - the game doesn't even list them in the latest.log file.

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.32
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.16-5.0.21
* RFTools: 1.16-2.0.11
* RFTools Dimensions: 1.16-7.0.11-beta

Possibly incompatible mods: 
N/A; no mods besides the RFTools series (Power, Utility, etc) and JEI are installed.

Relevant logs, if any: 
No crash logs, so I've uploaded my latest.log and debug.log to [this gist.](https://gist.github.com/glencoe2004/dab4e876ff5896aff198759818332161)

**Comment by jebjordan** [comment]
Any updates to this? quite sad

**Comment by McJty** [comment]
Sorry. Have been very busy. Haven't had time to look at this

**Comment by McJty** [comment]
I'm debugging the issue and found out what's wrong. I will fix this for this weekend
