### ISSUE TITLE
Netherite blocks have lower rarity than expected

### ISSUE THREAD

**Issue by BlaCoiso** [McJty/RFToolsDimensions#366]
Issue description: Netherite blocks (Lodestone, Ancient Debris, Netherite Block) have common rarity instead of rare despite being a rarer material than diamond (Diamond Ore and Diamond Block have both the "Rare" rarity)

Steps to reproduce: 

1. Place and open a Dimlet Workbench
2. Click on All to show all possible dimlets
3. Filter by "netherite", then shift hover on the results
4. Repeat step 3 for "ancient debris" and "lodestone"

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-forge-36.1.23
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.16-5.0.19
* RFTools: 1.16-2.0.10
* RFTools Dimensions: 1.16-7.0.9-beta

Possibly incompatible mods: -

**Comment by McJty** [comment]
Will fix this for next version
