### ISSUE TITLE
Config reset on server boot

### ISSUE THREAD

**Issue by Tgiguy** [McJty/RFToolsDimensions#37]
We've been trying to balance the mod for a modpack on our server, but whenever we start up the server after editing the config, the config resets to default. I'm not sure what other info I can provide for this issue, so if there is anything else I can provide just let me know and I would be glad to.

**Comment by McJty** [comment]
Did you read the line in the dimlets.json that says:

  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

You have to put your rules and modifications above this line. Are you doing that? If so please show me your dimlets.json file

**Comment by McJty** [comment]
Closing for now
