### ISSUE TITLE
Need help with adding the thermal expansions ore.

### ISSUE THREAD

**Issue by poulhp** [McJty/RFToolsDimensions#371]
I need some help adding the ores from thermal expansion to the dimlets.json file.
I have no idea why its not working. This is copper ore.

And its added above the "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that", line
{
    "filter": {
	"mod": "thermalfoundation",
	  "name": [
        "thermalfoundation:ore",      
      ],
	  "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 8000,
      "maintain": 1400,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },

I have tryed read the doc https://wiki.mcjty.eu/mods/index.php?title=RFTools_Dimensions but that dosnt provide any help on whats wrong.

So please if anyone can help.

Versions:
* Minecraft: 1.12.2
* Forge:14.23.5.2855
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.4
* RFTools: 7.73
* RFTools Dimensions: 5.71

Possibly incompatible mods:  None that i know of

**Comment by Darkere** [comment]
The name is wrong. That is the name for all of thermal expansions ores. You need to also specify the metadata. 

I'm not sure what the metadata for copper ore is, or what the exact way of specifying it is. But it should be something like:

"thermalfoundation:ore:1" or "thermalfoundation:ore@1" or similar. 

You may be able to find some examples in from other dimlet specifications or even from other modpacks.

**Comment by poulhp** [comment]
First up thanks for taking you time to answer me

Iv now tryed this
{
    "filter": {
	"mod": "thermalfoundation",
	"name": "ore",
	"type": "material",
	"meta": "0"
    },
    "settings": {
      "rarity": 3,
      "create": 8000,
      "maintain": 1400,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },

and it still dont work, I have no idea what to do, iv looked over 5-8 other mod packs that use RFdimensions but I cant find a common item to help me understand now I need to fill in the information to get it to work.

**Comment by Darkere** [comment]
Well first thing to change is this 
"meta": "0" -> "meta": 0

But yeah I've got no idea if that is not the problem...

**Comment by poulhp** [comment]
Okay - I got it to work :D. Thanks aloit
Yes one of the problems was with the meta "0" - thanks for that.

It need to look like this:
[
{
    "filter": {
	 "mod": "thermalfoundation",
	 "name": "ore",
	 "meta": 0,
	 "type": "material"
	},
    "settings": {
      "rarity": 3,
      "create": 8000,
      "maintain": 1400,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

The other problems was with the [ ] and { } being in the wrong place :D
