### ISSUE TITLE
Block Absorber absorbing air

### ISSUE THREAD

**Issue by NielsPilgaard** [McJty/RFToolsDimensions#372]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2962

Issue description: 
 No matter how many times I place one down or on what block, the block absorber only absorbs air, and it does so in an instant.

Steps to reproduce: 
- Place down Block Absorber

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-36.2.1
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: [McJtyLib - 1.16-5.0.22](https://www.curseforge.com/minecraft/mc-mods/mcjtylib/files/3402861)
* RFTools: [RFToolsBase - 1.16-2.0.11](https://www.curseforge.com/minecraft/mc-mods/rftools-base/files/3380271)
* RFTools Dimensions: [RFToolsDimensions - 1.16-7.0.11-beta](https://www.curseforge.com/minecraft/mc-mods/rftools-dimensions/files/3382163)

**Comment by McJty** [comment]
Can you show me a few screenshots describing this?

**Comment by DizzyDJW** [comment]
> Can you show me a few screenshots describing this?

The screenshots wouldn't show much of anything. The block says "n.a." on progress with no block selected, but the moment it's placed it says "Air" and "100%" progress. That's it. No matter how it is placed, even surrounded on all but one side, above or beneath a ton of blocks, it only absorbs air

**Comment by McJty** [comment]
I've seen so many reports of RFTools Dimensions doing weird things on enigmatica. I wonder if that pack is wrongly configuring the mod somehow. In any case, I cannot reproduce this

**Comment by DizzyDJW** [comment]
So what could potentially be affecting the behavior of the Block Absorber?

**Comment by NielsPilgaard** [comment]
We must have configured the jsons incorrectly or something, I guess :/ will investigate it.

**Comment by McJty** [comment]
What kind of configuration did you do? What is different from default?

**Comment by NielsPilgaard** [comment]
We modified the Powah, Quark and Thermal jsons, and added one for Emendatus Enigmatica: https://github.com/NillerMedDild/Enigmatica6/tree/develop/config/rftoolsdim

**Comment by NielsPilgaard** [comment]
It seems to happen for the Emendatus Enigmatica blocks that I've added, is it not possible to add compatibility by adding additional jsons in the `rftoolsdim` config folder?

**Comment by McJty** [comment]
That shuold work but people have reported bugs with that. I'll investigate

Note that you have to modify dimletPackages in rftoolsdim-server.toml after adding compatibility packages. But it is this part that isn't working correctly

**Comment by McJty** [comment]
I found the bug and will release a fix this weekend
