### ISSUE TITLE
Fluid Absorber sometimes counts non-source blocks as being absorbable

### ISSUE THREAD

**Issue by NielsPilgaard** [McJty/RFToolsDimensions#373]
Issue description: 
Fluid Absorber can absorbe and count non-source blocks

Steps to reproduce: 
1. Place water so it flows downwards
2. Place Fluid Absorber above it
3. Watch the % going up quite a bit

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-36.2.2
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.22
* RFTools: rftoolsbase-1.16-2.0.11
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta

Possibly incompatible mods: None

Relevant logs, if any:

**Comment by McJty** [comment]
Fixed in 7.0.14
