### ISSUE TITLE
Dimension Builder redstone control does not persist

### ISSUE THREAD

**Issue by NielsPilgaard** [McJty/RFToolsDimensions#374]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3008

Issue description: 

> RFToolsDimensions Dimension Builder Redstone control button not working.
> when clicked it will cycle between on/off etc. however the selection doesn't actually persist, as soon as the inventory is closed it reverts back to "redstone ignored."
> 
> Tested with and without dimension cards, full power, no power, and as many other variables as I can come up with.
> **Screenshots**
> ![javaw_fcPHXalCt3](https://user-images.githubusercontent.com/76798835/129492809-5c5cc4ca-36bd-4960-b93b-eaf7504b3a9d.png)

Steps to reproduce: 
1. Place Dimension Builder
2. Click Redstone setting button
3. Close GUI
4. Open Dimension Builder
5. See Redstone setting button set to default mode

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-36.2.2
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.22
* RFTools: rftoolsbase-1.16-2.0.11
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta

Possibly incompatible mods: None

Relevant logs, if any:

**Comment by McJty** [comment]
Fixed next release
