### ISSUE TITLE
Liquid Neutron Fluid [NuclearCraft] world is a death sentence to the server

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [McJty/RFToolsDimensions#375]
Issue description: 
A copy of https://github.com/al132mc/antimatter-chemistry/issues/294.
![image](https://user-images.githubusercontent.com/860874/129512975-8f5eab3f-234c-453e-a37d-7c3a2c9ec8dd.png)

NuclearCraft has "Neutron Fluid" which has a special behavior of disintegrating upon being placed into the world after a few ticks. A liquid absorber does accept Neutron Fluid, thus you can make a [Liquid: Neutron Fluid] + [Terrain: Liquid] world which, upon entry, will induce thousands of block updates and potentially crash the server.

This combination should probably specifically be disabled by default.

Steps to reproduce: 
1. Obtain "Neutron Fluid" liquid material dimlet.
2. Obtain "Terrain: Liquid" dimlet.
3. Combine
4. Build the dimension
5. Enter the world
6. The ultimate lag machine has been engaged

Versions:
NuclearCraft 1.12.2 - 2.18y
RFTools 1.12 - 7.73
RFTools Dimensions 1.12 - 5.71 

Later versions are likely also affected, needs confirmation

Possibly incompatible mods: N/A

**Comment by McJty** [comment]
Version?

**Comment by DeltaEpsilon7787** [comment]
Should be applicable to any version as I haven't found any mentions of it being fixed, but

NuclearCraft 1.12.2 - 2.18y
RFTools 1.12 - 7.73
RFTools Dimensions 1.12 - 5.71

**Comment by DeltaEpsilon7787** [comment]
It should be noted that NuclearCraft is available only for versions up to 1.12, so versions of RFTools for 1.12 should be affected.

**Comment by McJty** [comment]
Well was mostly interested in the MC version. Anyway, that liquid should be disabled by default. What pack are you playing? Perhaps that pack enables it. It's up to the config/pack maker to disable or enable dimlets. Not something that is built into the mod

**Comment by DeltaEpsilon7787** [comment]
The mod pack in question is Antimatter Chemistry.

Apparently they enabled _all_ liquids in the configs to be acceptable, even gases. Not this mods issue then.
