### ISSUE TITLE
Can't Place Empty Dimlet into Dimlet Slot in Dimlet Workbench

### ISSUE THREAD

**Issue by DizzyDJW** [McJty/RFToolsDimensions#376]
Issue description: I am unable to place empty dimlets into the dimlet slot in the dimlet workbench in order to craft a dimlet of a specific type. Empty block, feature, terrain, etc... dimlets are unable to be placed in the slot.

Steps to reproduce: 

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.2
* McJtyLib: 5.0.22
* RFTools: 2.0.11
* RFTools Dimensions: 7.0.12

![image](https://user-images.githubusercontent.com/26727521/129622560-eb116c88-c505-4b9d-a1ee-9f0c38cf907a.png)

**Comment by McJty** [comment]
You can shift-click it in there but indeed. It's weird that it will not work by dragging. I'll check it out

**Comment by DizzyDJW** [comment]
Shift clicking was placing it in the liquid drop slot for me. I can double click the recipe in the workbench but I'm sure new ppl wont know about that

**Comment by McJty** [comment]
Fixed in 7.0.14
