### ISSUE TITLE
Question: How to delete unused dimensions? (1.16.5)

### ISSUE THREAD

**Issue by ftog-thorgal** [McJty/RFToolsDimensions#378]
We are looking if players can still delete their own dimensions like it used to work via in-game (I remember something about TNT and the dimension tablet) or via the /safedel command. We are having lot's of players getting into creating dimensions and want to be able to have them delete all the ones they aren't using any longer.

I looked through all the commands, especially the /rftoolsdim forget and /rftoolsdim forgetinvalid, but they don't seem to do anything. I also looked through the configs but couldn't find any entires that used to be there along the lines of "player can safe del".

So the question is: Are there any mechanics or commands to actually remove dimensions implemented?

Enigmatica 6 modpack with rftoolsdim-1.16-7.0.11-beta.jar

**Comment by radiofox61** [comment]
I also have the same problem as you

**Comment by gdharron** [comment]
bump

**Comment by DragarX** [comment]
bump

**Comment by McJty** [comment]
This is now supported on 1.18 but on 1.16 I'm not going to implement it as it is a bit hard to do there

**Comment by DragarX** [comment]
I found a workaround in 1.16.5 but it requires deleting the dimensions from the level.dat as well using the "forget" command

**Comment by Septem151** [comment]
> This is now supported on 1.18 but on 1.16 I'm not going to implement it as it is a bit hard to do there

I'm on 1.18.2 right now and there's no option to remove or forget dimensions. Where is this option/what is the keybind supposed to be?

**Comment by McJty** [comment]
Using the dimension editor, send tnt to it

**Comment by aelfwyne** [comment]
> Using the dimension editor, send tnt to it

And what if we lost or deconstructed the DIM tab?

**Comment by McJty** [comment]
Then you can't really. You can try to construct the tab again. Of course you can delete the region files to reclaim the space but the dimension will not be gone

**Comment by MidRareSteak** [comment]
Is there a way to delete it from files everytime i delete the RFtools Dimensions folder it reappears on startup
