### ISSUE TITLE
Can't craft or see requirements of dimlet on server

### ISSUE THREAD

**Issue by rosalina-ha** [McJty/RFToolsDimensions#379]
### Issue description: 
On server, can't see dimlet cost / rarity nor craft them.
However, when loading a solo world, we can see the cost and craft them. It also solves the issues for multiplayer as long as minecraft is not restarted before connecting to the server.

On server (without going solo)
![image](https://user-images.githubusercontent.com/1713896/131256379-4f314a40-5cff-4274-909c-d6fd4bda7982.png)

Same server (after loading a solo world and going back to multiplayer)
![image](https://user-images.githubusercontent.com/1713896/131256456-42055b00-2923-4d4c-bddf-0ce82e5dfeef.png)

On server, after restarting the client (server did not restart)
![image](https://user-images.githubusercontent.com/1713896/131256524-4da41a95-d0ef-467e-883f-9f7ea14d1da0.png)

### Steps to reproduce: 
Create a server with only the mods listed (and a power generation mods), connect to it without going to a solo world before and try to craft a dimlet in a dimlet workbench.

### Versions:
* Minecraft: 1.16.5
* Forge: forge-1.16.5-36.2.0
* McJtyLib: mcjtylib-1.16-5.0.22
* RFTools: rftoolsbase-1.16-2.0.11
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta

**Comment by McJty** [comment]
I found the issue. I will fix this soon

**Comment by McJty** [comment]
Should be fixed now
