### ISSUE TITLE
[CRITICAL] Server freezes with void worlds

### ISSUE THREAD

**Issue by ShayBox** [McJty/RFToolsDimensions#38]
Found a huge bug,
If you have a void world, and light up every spot in the world, then leave the world it will lag the server trying to find a spot to spawn,
Creating a platform near the spawn chunks of the world where mobs spawn fix this, but is not a good solution,

**Comment by McJty** [comment]
What version of RFTools?
Also how to reproduce/ Many people have made void worlds with only a spawn platform that is fully lit with no problems. So I guess there is some other mod that is causing a problem with this

**Comment by ShayBox** [comment]
1.10 4.40

**Comment by plumbusfactory** [comment]
Yeah the issue happens only when the dim is un loaded, so long as a player is in the dim the server is fine, as soon as they leave the server gets crippled down to 1 tps

**Comment by plumbusfactory** [comment]
By : net.minecraft.world.WorldEntitySpawner.findChunksForSpawning()

**Comment by McJty** [comment]
About net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(): can you give me the full stacktrace of that? What is calling that function?

**Comment by plumbusfactory** [comment]
its not a exception I got that by profiling

**Comment by McJty** [comment]
My guess is some mod is calling this excessively because vanilla handles this properly (and as I said, void worlds are commonly used with rftools dimensions with no problems). The problem is finding out what mod...

**Comment by ShayBox** [comment]
Is there a dimlet that disables mob spawn attempting?

**Comment by McJty** [comment]
yes the peaceful dimlet but this will not help. It doesn't prevent calling of the above function. It just prevents the spawn right before it actually happens

**Comment by McJty** [comment]
BTW, this bug is very weird and also seems somewhat unrelated to RFTools Dimensions because if you would make another dimension where nothing could spawn (like fully lit) you would essentially get the same problem. BTW, what are the characteristics of that dimension? Can you do /rftdim info and show me what it says? (or right click with dimension tab)

**Comment by ShayBox** [comment]
http://prntscr.com/cp56nj

**Comment by McJty** [comment]
Well not sure what I can do about this. I don't think this is rftools dimension causing it. Otherwise many more people would have had issues. BTW, one other test. Can you see if this also happens with another void dimension?

**Comment by ShayBox** [comment]
Sorry, it seems that its having issues with cap banks in rf dims or the fact that i have so many in a flat layer and not in a cube

**Comment by ShayBox** [comment]
You wouldnt happen to know how to edit .mca files because your dims DONT HAVE LEVEL.DATS

**Comment by McJty** [comment]
Level.dat is the players inventory. That's normal that they are not for my dimensions. I think mcedit can edit dimensions but not sure how. Never used it for that
