### ISSUE TITLE
Lost Knowledge only have broken/unusable attributes. Dimlet Workbench not displaying recipes.

### ISSUE THREAD

**Issue by snowzielol** [McJty/RFToolsDimensions#380]
Issue description: 
1. Researcher only produces lost knowledge for blocks/attributes that either don't exist or cannot be used. I tested this for a while and ended up with ONLY a stack of the same Legendary Lost Knowledge "dragon_immune" or "atomic_disassembler_ore" (which does not actually exist. the atomic disassembler is a tool from mekanism) 
![Screenshot_1](https://user-images.githubusercontent.com/89761771/131284038-a8afaf5b-bfde-4f82-90d7-6d8e5a958092.jpg)

2. Dimlet workbench breaks entirely and does not show anything within the search bar when one of these broken knowledge tablets are within the knowledge holder.
![Screenshot_3](https://user-images.githubusercontent.com/89761771/131284053-a6fa78d5-59bb-44f2-9d3a-e412e3f19700.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/89761771/131284084-fc3ff2b9-7f6a-40c2-90bd-6a7e730d0e64.jpg)

3. The problem persists past the Legendary tier and exists within almost every tier. However common is the least broken as I am able to obtain a vanilla attribute 1/100 times. When I put these into the Dimlet workbench BY ITSELF it works just fine and as intended. It breaks immediately when one of the broken Lost Knowledge tablets are added.
![Screenshot_5](https://user-images.githubusercontent.com/89761771/131284375-8abbdc93-cb1a-433c-b7df-089c399a44eb.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/89761771/131284395-80c03a20-1fa8-4124-af12-94be42eb9f8a.jpg)

Then I add a broken legendary knowledge and it stops working:
![Screenshot_8](https://user-images.githubusercontent.com/89761771/131284484-d39aa60a-bca8-4e47-805f-ac84fa11c8d5.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/89761771/131284494-8b6b8481-62a9-4391-ae82-dc4ea0e2b801.jpg)

Steps to reproduce: as described above

Versions:
* Minecraft: 1.16.5 VALHELSIA 3 3.3.3
* Forge:  36.1.25
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.16
* RFTools: rftoolsbase-1.16-2.0.10
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta

Possibly incompatible mods: 

Relevant logs, if any: https://pastebin.com/X79ERrVV

**Comment by McJty** [comment]
Outdated mcjtylib and rftoolsbase
