### ISSUE TITLE
Dimlets not showing recipes in the Dimlet Workbench

### ISSUE THREAD

**Issue by AlexHailstone** [McJty/RFToolsDimensions#381]
Issue description: The recipes for crafting custom dimensions using the Dimlet workbench doesn't show the recipes

Steps to reproduce: 
(This is version 1.16.5 and ATM6 version 1.7.11)

1. Crafting a dimlet workbench
2. Have some knowledge discovered
3. Review the available knowledge from the workbench (hover over the icon for recipe)
4. No recipe showing in the tooltip

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.2
* McJtyLib:
* RFTools: rftoolsbase-1.16-2.0.11, rftoolsbuilder-1.16-3.1.2, rftoolscontrol-1.16-4.0.11, rftoolspower-1.16-3.0.9, rftoolsstorage-1.16-2.0.13, rftoolsutility-1.16-3.1.2
* RFTools Dimensions: rftoolsdim-1.16-7.0.12-beta

Possibly incompatible mods:  (none that I'm aware of)

Relevant logs, if any: 

Screenshots:
Watching [this YT video](https://www.youtube.com/watch?v=Su6gciTU1vo&ab_channel=EpiDadMeGames) and shows this: 
![image](https://user-images.githubusercontent.com/76534423/131936308-a3badf3f-195f-40b3-b2ca-5afcbed3dda2.png)

Meanwhile in my game I show this:
![image](https://user-images.githubusercontent.com/76534423/131936379-48bc04f3-3c73-4eb2-bd6d-30c9e82b82ff.png)
Block Dimlet for direct comparison:
![image](https://user-images.githubusercontent.com/76534423/131936454-b2f733b6-6380-484a-aafe-c45a31b06343.png)

**Comment by McJty** [comment]
Already fixed in the latest version of rftools dimensions
