### ISSUE TITLE
Block Absorber breaking bedrock

### ISSUE THREAD

**Issue by NielsPilgaard** [McJty/RFToolsDimensions#383]
Issue description: Block Absorber "absorbs" bedrock

Steps to reproduce: Place a Block Absorber directly above bedrock

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5-36.2.2
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.22
* RFTools: rftoolsbase-1.16-2.0.11
* RFTools Dimensions: rftoolsdim-1.16-7.0.14-beta

**Comment by McJty** [comment]
Fixed next release
