### ISSUE TITLE
can t use block absorber with unbreakable blocks by hands

### ISSUE THREAD

**Issue by bagou4502** [McJty/RFToolsDimensions#384]
Issue description: I can t use block absorber with unbreakable blocks by hands (like stone diamond block iron ore ect...)

Steps to reproduce: Place unbreakable blocks by hand under an absorber

Versions:
* Minecraft: 1.16.5
* Forge: 1.16.5 - 36.2.8
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:  5.0.23
* RFTools: 2.0.11
* RFTools Dimensions : 7.0.15

**Comment by McJty** [comment]
Fixed next release
