### ISSUE TITLE
Block Absorber doesn't work

### ISSUE THREAD

**Issue by Crida117** [McJty/RFToolsDimensions#385]
Issue description: the block absorber doesn't work

Steps to reproduce: put the block absorber ontop of a block and it doesn't work it says block<not select> and it is at 100%

Versions:
* Minecraft: 1.16.5
* Forge: the last recomended
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: the last
* RFTools: the last
* RFTools Dimensions: the last 

 optiforge
Possibly incompatible mods: 

Relevant logs, if any:

**Comment by bagou4502** [comment]
try with a dirt block i think i have same problem as you

**Comment by Crida117** [comment]
> try with a dirt block i think i have same problem as you

i tried place it on the grass and it works but doesn't work with others

**Comment by bagou4502** [comment]
> > try with a dirt block i think i have same problem as you
> 
> i tried place it on the grass and it works but doesn't work with others

Okey same problem as me you can t use block obsorber on unbreakable blocks by hands

**Comment by bagou4502** [comment]
Its work with the 7.0.14 version of rftools dim

**Comment by McJty** [comment]
Fixed next release

**Comment by Kayru20** [comment]
i am currently having the same problem. though i am using a modpack if that affects anything. the modpack is FTB presents Direwolf20 1.19 and the version is 1.7.0
