### ISSUE TITLE
No terrain dimlet crafting recipes in JEI or knowledge table

### ISSUE THREAD

**Issue by andrew103** [McJty/RFToolsDimensions#386]
Issue description: 
Crafting recipes for flat or void terrain don't exist or show up when checking both in JEI and the built-in minecraft recipe search utility. Terrain dimlets also don't show up as options in the knowledge table. Only void terrain dimlets spawn in the dimension huts. There is also no `voidOnly` option in `serverconfig/rftoolsdim-server.toml`. Would adding the parameter and setting it to `False` resolve the issue? If so, which section of the file would I add the parameter?

Steps to reproduce: 
Not sure other than installing the mod into an existing single player modded world.

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.0
* McJtyLib: 5.0.23
* RFTools: 2.0.11
* RFTools Dimensions: 7.0.15-beta

Optifine installed client-side

Possibly incompatible mods: 
None that I know of. I can post the mod list if it'd be helpful.

Relevant logs, if any: 
Can supply on request.

**Comment by McJty** [comment]
Dimlets don't show up in JEI. They show up in the dimlet workbench (if you press 'all') Check there first

**Comment by andrew103** [comment]
Ah yep they do show up in the workbench. I suppose I've just been really unlucky with knowledge pages then. Although from googling around I remember seeing mentions of void and flat terrain dimlets being craftable. Is this no longer the case?

**Comment by makifinner** [comment]
how about Feature Oregen dimlet. are they gone too :(

**Comment by McJty** [comment]
For now yes. Things like these will be added later though
