### ISSUE TITLE
Can't craft block dimlet

### ISSUE THREAD

**Issue by Smokeboy-ya** [McJty/RFToolsDimensions#387]
Issue description: I cannot craft block of gold dimlet

Steps to reproduce: 
i put all the correct items (as far as the dimlet says ) at dimlet workbench and i press create and nothing happens

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.19
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.1.0.jar
* RFTools: rftoolsbase-1.16-2.1.0.jar
* RFTools Dimensions:  rftoolsdim-1.16-7.0.16-beta.jar

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by McJty** [comment]
Show me screenshots and exact descriptions of what you're trying to add

**Comment by Smokeboy-ya** [comment]
![2021-12-01_22 58 54](https://user-images.githubusercontent.com/71586945/144313331-ffd57e04-b10c-4d8b-bb27-06d7d51de4da.png)
![2021-12-01_22 58 45](https://user-images.githubusercontent.com/71586945/144313345-c2aac021-2bd6-45eb-b0ae-36f37f42e98c.png)
![2021-12-01_22 58 46](https://user-images.githubusercontent.com/71586945/144313240-4c3bd2ae-8e34-480c-bc17-717ff03ebc12.png)
![2021-12-01_22 58 50](https://user-images.githubusercontent.com/71586945/144313280-755e42d1-9c73-4d6d-9566-952adc35b125.png)
![2021-12-01_22 58 51](https://user-images.githubusercontent.com/71586945/144313300-468bc22c-bf53-42ec-887e-213a60e1312c.png)
![2021-12-01_22 58 53](https://user-images.githubusercontent.com/71586945/144313312-5f1bad0d-c5a4-4efd-8cc1-2bdcdf2f80db.png)

**Comment by drakray** [comment]
I have the same problem
<details><summary>Screenshots</summary>

![2021-12-05_16 45 20](https://user-images.githubusercontent.com/4303126/144765186-dfdeb731-4c24-4256-a1dd-37fd7d28e1b3.png)
![2021-12-05_16 45 32](https://user-images.githubusercontent.com/4303126/144765187-e2e500bc-8ac8-4ded-ae95-980aac97c6e1.png)
![2021-12-05_16 45 48](https://user-images.githubusercontent.com/4303126/144765188-fde538f3-3712-4b7f-a9c5-da76fa0fe923.png)
![2021-12-05_16 46 03](https://user-images.githubusercontent.com/4303126/144765189-37e982d0-8727-4343-8b21-08b72a851c51.png)

</details>

**Comment by McJty** [comment]
Fixed in next release
