### ISSUE TITLE
spawning dimlets in creative doesn't work

### ISSUE THREAD

**Issue by drakkillen** [McJty/RFToolsDimensions#388]
Issue description: cant spawn in dimlets from workbech when in creative

Steps to reproduce:  go into creative, place dimlet workbench down, enter it and select any dimlet, shift+double click. nothing happens

Versions: 
* Minecraft: 1.16.5
* Forge: 36.2.19
* CompatLayer (only if on Minecraft 1.10 or 1.11): 0
* McJtyLib: 5.1.0
* RFTools:2.1.0
* RFTools Dimensions: 7.0.16-beta

Possibly incompatible mods: optifine 1.16.5_HUD_G8

Relevant logs, if any: none

**Comment by drakkillen** [comment]
any response?

**Comment by McJty** [comment]
Sorry, have been busy. I'll check this later

**Comment by McJty** [comment]
Actually I just did and I found the bug. Is fixed in git. Will release a fix later today
