### ISSUE TITLE
EnderDragon dimlet spawns inactive dragons

### ISSUE THREAD

**Issue by oceth** [McJty/RFToolsDimensions#39]
When creating an ender dragon mob dimlet, the resulting ender dragons only hover in place and are not attackable. According to the Minecraft wiki, this is probably caused by the missing nbt tag "DragonPhase" (http://minecraft.gamepedia.com/Ender_Dragon#Commands).

Minecraft 1.10.2
RfToolsDimension 4.40
Forge 12.18.1.2089

**Comment by McJty** [comment]
Fixed

**Comment by callmebackdraft** [comment]
@McJty  , in which version ?

Kind of indescriptive this way,

**Comment by McJty** [comment]
Well I only fix problems in the latest version of RFTools Dimensions

**Comment by haddow777** [comment]
Okay, so I know this is supposed to be fixed and I even saw the code that is supposed to reset the ender dragons activity phase when spawned, but ...

Mine is not working and is acting just like this issue. I have rebuilt my dimension several times and even got another syringe and rebuilt the dimlet. The only thing I might think is an issue is the workbench selected a rarity 5 card when the config says the enderdragon is a rarity 6. Direwolf20, in his vid ([Lets Play S9 E83](https://www.youtube.com/watch?v=_sgO8b-pD4U&index=83&list=PLaiPn4ewcbkGuWjVS_GS-LzWwOehCjRg6)) used a rarity 5 card without issue, so I'm not thinking it's a problem.

I am using the 1.8.0 of the Direwolf20 1.12.2 pack. It has the 5.51 version, which I'm pretty sure is the latest version of the rftools dimension mod.

Any ideas why this might not be working or more information you might need would great.

![2018-02-11_13 53 55](https://user-images.githubusercontent.com/2130853/36079858-9c7e57bc-0f3c-11e8-9ef3-7d813d089566.png)

**Comment by haddow777** [comment]
Thanks. Any help you need from me to help fix this, just let me know.

**Comment by josephcsible** [comment]
This works fine when I try it in the development environment. Can you make a fresh instance that only has RFTools Dimensions and its dependencies, and try it there? If it works fine there, then try to narrow down which other mod from the pack is breaking it. If it doesn't work there, then post the result of "/rftdim info" inside of the dimension.

**Comment by haddow777** [comment]
A weird thing is, DIrewolf20, in the previously mentioned video was able to get it to work in his game. I'm running the same exact pack and instance as him. So I'm not thinking it's a mod pack.

**Comment by haddow777** [comment]
Okay, quick update. I did create a bearbones edition with nothing but rftools dimensions. The dragons worked there. Super frustrating. So I rechecked my mods. The only non-pack mods I do have (remembered after looking) is Optifine_1.12.2_HD_U_C8 and LagGoggles-1.12.2-2.1.

I will be doing further testing, but I have to admit, I'm running on a surface pro 3, so with load times, trying to troubleshoot by removing mods from a pack with something like 140 could take me approxamately 27000 years. Just a guess.

**Comment by haddow777** [comment]
okay, tested a bit and it seem somehow optifine is affecting it. I removed both LagGoggles and Optifine and tested a test world I made and some of the dragons came out of the brainless phase and started attacking me.

I reloaded with optifine and the dragons already out of the dumb phase continued, but the others who hadn't changed phases stayed as they were. I tried resetting my video settings to see if that changed anything, but the dragons were still stationary.

Not sure how a video optimization mod could affect it, but there you are. For me, I will have to live without a dragon dimension as I couldn't run minecraft without optimizations.

**Comment by josephcsible** [comment]
Unfortunately, OptiFine is both a highly invasive coremod and closed-source, so it's not really feasible for us to fix any bugs that it causes. All I can suggest is turning off its optimizations one by one until you find the buggy one, then turn them all back on except for it.

If you'd like this to be actually fixed, report it to their issue tracker.

**Comment by josephcsible** [comment]
@haddow777 One thing to try: if you're using Forge 2596 or later, try downgrading to Forge 2595. If that solves your problem, then sp614x/optifine#1212 is the cause. (Why OptiFine messes with server-side mob logic I have no idea, but I'm not surprised, since they've [broke opening chests](http://www.minecraftforge.net/forum/topic/62078-cant-open-chests-with-forge-1122-142312569-and-higher/) in the past.)
