### ISSUE TITLE
Crash server when im open the matter transmitter

### ISSUE THREAD

**Issue by LeRoiLambda** [McJty/RFToolsDimensions#391]
Im on the latest version of ragnamod 6, modpack

When im clicking on the matter transmitter the server crash

setup:
kpp
xco

k=flux point
p= ultimate cable of mekanism
x=dimension inscriber
c=matter transmitter
o=matter receiver

 
logs crash server

https://pastebin.com/fTWd66jd

 
on my client there is a message:
Internal Exception: java.lang.StackOverflowError

		mcjtylib-1.16-5.1.0.jar   
		rftoolsbase-1.16-2.1.0.jar           
		xnet-1.16-3.0.14.jar                      
		rftoolsdim-1.16-7.0.16-beta.jar        
		rftoolspower-1.16-3.0.10.jar        
		rftoolsbuilder-1.16-3.1.3.jar      
		rftoolsstorage-1.16-2.0.14.jar
		rftoolscontrol-1.16-4.0.12.jar   

I already reported the crash on the curseforge of ragnamod
https://www.curseforge.com/minecraft/modpacks/ragnamod-vi/issues/943

**Comment by McJty** [comment]
Update my mods

**Comment by LeRoiLambda** [comment]
Thank you, it works.
