### ISSUE TITLE
Cannot add materials that have multiple IDs

### ISSUE THREAD

**Issue by Auhrus** [McJty/RFToolsDimensions#393]
Issue description: Server/game crashed when I try to add custom dimlets. If I use for example Osmium from Mekanism it works. But when I try to add a block with an ID at the end it crashes.

**Example with osmium:**

 _{
    "filter": {
      "mod": "mekanism",
      "name": "oreblock",
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 200,
      "maintain": 100,
      "ticks": 200,
      "worldgen": true,
      "dimlet": true
    }
  },_

**Example with an ID at the end:**
 
_{
    "filter": {
		"mod": "nuclearcraft",
		"name": 
		"ore:3",
		"ore:4",
		"ore:5",
		"ore:7"
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 200,
      "maintain": 150,
      "ticks": 150,
      "worldgen": true,
      "dimlet": true
    }
  },_

Unfortunately the wiki is from 2015 and therefore no longer usable. 😔
I have now already tried various combinations with the IDs. Sometimes with or without , or "" the "property" flag or the "key" flag.
Also like in the picture it does not work
_by @Nearius-River in https://github.com/McJtyMods/RFToolsDimensions/issues/359#issuecomment-873435572_

---

Steps to reproduce:
Try to set a dimlet of a block that has the same name but additionally different IDs.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* McJtyLib: 3.5.4
* RFTools: 7.73
* RFTools Dimensions: 5.71

Possibly incompatible mods: OptiFine_1.12.2_HD_U_G5_MOD, BetterFPS 1.4.8

Relevant logs, if any: Log there was entliche depends on how one has entered the blocks depending on the changed also the log.

**Comment by McJty** [comment]
Did you check this wiki?

https://wiki.mcjty.eu/mods/index.php?title=RFTools_Dimensions

**Comment by Auhrus** [comment]
Thank you for the link. The "meta" I was missing now it runs perfectly. 👌


Just one more addition could you then this ([https://github.com/McJtyMods/RFTools/wiki/Adding-a-Dimlet](https://github.com/McJtyMods/RFTools/wiki/Adding-a-Dimlet)) old wiki either refer to it or update this has confused me very much in this case.😕

For others who still have this problem this is how it works for me with several items with the same name only with a different metadata:

```
{
    "filter": {
      "mod": "nuclearcraft",
      "name": "ore",
      "meta": [
        3,
        4,
        5,
        7
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 200,
      "maintain": 150,
      "ticks": 150,
      "worldgen": true,
      "dimlet": true
    }
},
```
