### ISSUE TITLE
[1.12.2] Crash after going into a server and then singleplayer

### ISSUE THREAD

**Issue by sofiaeris** [McJty/RFToolsDimensions#395]
Issue description: 
After I join my server, everything is fine, but if then, i log off and start a singleplayer world, it crashes.
Steps to reproduce: 
On my modpack (https://www.technicpack.net/modpack/autismo-the-grand-collection.1914643), join a server, leave and try starting/creating a singleplayer world.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2859
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
* RFTools Dimensions: 1.12-5.71

Possibly incompatible mods: Optifine, FoamFix, Surge, VanillaFix, Phosphor

Relevant logs, if any: 
[crash-2022-04-07_03.53.21-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8439050/crash-2022-04-07_03.53.21-server.txt)

**Comment by Sander470** [comment]
Probably the wrong thread, CUSTOMNPC's is what causes the crash, as removing it fixed the issue.

**Comment by sofiaeris** [comment]
i have confirmed the crashes happen because of the file in a world/data/RFToolsDimensionManager.dat
If I delete said file from the server, the issue disappears, but then when I create a dimension again, causing the file to re-generate, the crash comes back.

**Comment by McJty** [comment]
Can't do much about this as I no longer develop on 1.12. My guess is there is probably some mod conflict but I can't see where

**Comment by sofiaeris** [comment]
After more testing, I can confirm it is NOT a mod conflict; solely having:
-mcjtylib-1.12.3.5.4.jar
-rftools-1.12.7.73.jar
-rftoolsctrl-1.12.2.0.2.jar
-rftoolsdim-1.12-5.71.jar
-rftoolspower-1.12-1.2.0.jar
causes the game to crash when: the server contains the file RFToolsDimensionManager.dat, you leave said server, try going to singleplayer.
This is a pretty weird issue that I'd have expected not to exist for a version as old. 
The issue resolves when removing RFTools dimensions, but I'd like to use it; effectively blocking singleplayer until restarting the game if I've joined a server.

Edit: I'm not an expert or anything close, I'm simply trying to troubleshoot my modpack as an intermediary modpack dev, but my guess would be that file gets cached and that breaks things?

**Comment by McJty** [comment]
Weird that other people have never reported this. In any case, I no longer develop on 1.12 so I can't do anything about this anymore
