### ISSUE TITLE
No Tool Tag on Researcher 

### ISSUE THREAD

**Issue by manmaed** [McJty/RFToolsDimensions#397]
**The Infos**
Minecraft: 1.18.2
Forge: 40.1.16
RFToolsBase: 3.0.7
RFToolsDim: 8.0.4

**Describe the bug**
Researcher has no tool tag attacted

**Steps to reproduce**
look at tool needed for researcher

**Expected behavior**
to be minable with pickaxe

**Screenshots**

**Comment by McJty** [comment]
Sorry for slow reply. Will be fixed next version
