### ISSUE TITLE
Concrete Powder Dimension

### ISSUE THREAD

**Issue by BNexS** [McJty/RFToolsDimensions#399]
Issue description: Game freezes after joining randomly generated dimension. 

Steps to reproduce: Generating a dimension with concrete powder material type and nether terrain.

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.25
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.18-6.0.13
* RFTools: 1.18-3.0.7
* RFTools Dimensions: 1.18-8.0.4

**Comment by BNexS** [comment]
Also happens when it is trying to generate a dimension using any kind of a crop. Maybe a good idea to blacklist non-solid and gravity affected blocks somehow.

**Comment by McJty** [comment]
Hmm, I'll remove concrete powder from the dimlets but what crops are dimlets? There shouldn't be any

**Comment by BNexS** [comment]
Sadly, I don't remember. For all I know, I was playing DW20 1.18.2 pack; I will try to find out what it has been tomorrow. 

That said, is there any way to check dimension properties (such as block type) without joining it and experiencing a complete freeze? A quick search with NBTExplorer was not successful, might have missed it.

**Comment by McJty** [comment]
You can sneak right click the dimension tab in your hand

**Comment by McJty** [comment]
This has been fixed some time ago
