### ISSUE TITLE
Kicked from server when dimension is fully charged in the builder.

### ISSUE THREAD

**Issue by mathiasDJ** [McJty/RFToolsDimensions#4]
When a dimension tab is placed in the dimension builder and gets to 100% all players on the server get kicked with a fatal exception.
The server stays up but needs a restart before players are able to rejoin. All connected players get kicked. Afterwards it is possible to travel to the dimension without any further issues.

Client log: http://pastebin.com/cGBTAQtf (line 505 onwards)
Server log just says the players disconnect.

RFToolsDimension version: 1.8.9-4.22beta26.jar
Forge version: 11.15.1.1756

Modpack: http://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-8-9

EDIT: this happened twice, but we can't reproduce it anymore. We think it had something to do with using the rftdim safe delete command and a new dimension then taking over the ID of the one that was deleted.

**Comment by McJty** [comment]
I will check it out

**Comment by mathiasDJ** [comment]
It happened again but the rftdim command wasn't used, the only other thing the dimensions that kick have in common is that they all were made up of 1 material dimlet and 1 terrain dimlet.

The server outputted this aswel: http://pastebin.com/mKwkKmH3

**Comment by McJty** [comment]
I know what's wrong. Will fix right away. New release coming in a few minutes
