### ISSUE TITLE
Dimensions cause server to crash when reaching 99% in Dimension Builder

### ISSUE THREAD

**Issue by Bancheis** [McJty/RFToolsDimensions#400]
Issue description: 
Dimensions cause server to crash when reaching 99% power in the Dimension Builder. This happens with multiple dimlet combinations. We have made roughly 10 worlds and 7 of them crashed the server. Multiple Dimension Tabs we made ended up showing a total power value of -1. I am unsure if all of them looked like this, but as soon as I knew to look for it, I took note. All since then did show this.

I believe you mentioned fixing this in a previous issue. https://github.com/McJtyMods/RFToolsDimensions/issues/361

Steps to reproduce: 
Reproduction can be done in either servers or single player. Simply attempt to power a Dimension tab. The combination of dimlets does seem to affect this somewhat, but I am unable to test large scale with multiple combinations. This is easily reproducible by not using any dimlets at all and creating a "blank" random Dimension. 

Versions: FTB Presents Direwolf20 1.18
* Minecraft: 1.18.2
* Forge: 40.1.25
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.18-6.0.13.jar
* RFTools: rftoolsbase-1.18-3.0.7.jar
* RFTools Dimensions: rftoolsdim-1.18-8.0.4.jar

Possibly incompatible mods: Unknown. We are running the official Direwolf20 pack with no changes.

Relevant logs, if any: I am still attempting to get the logs from the server admin. Here is an image of the dimension I tried to create. Ended up with "Current power: -1 (-1)"
![image](https://user-images.githubusercontent.com/57774238/171302748-509afd3c-8f9b-4bc6-acff-98d1c1d49fe6.png)

I was able to reproduce this easily in single player creative. In this one I simply generated a Dimension tab with only the flat terrain dimlet. I did this twice. First one worked fine. Second one caused a crash at 99% powered. Here are my logs.
[crash-2022-05-31_16.53.24-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8810055/crash-2022-05-31_16.53.24-server.txt)

Another test right after logging back in, blank Dimension tab with no dimlets crashed at 99% on the first try.
[crash-2022-05-31_17.10.29-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8810097/crash-2022-05-31_17.10.29-server.txt)

**Comment by McJty** [comment]
The second crash I'll already fixed. I will release later this evening. Investigating the first

**Comment by McJty** [comment]
Fixed. Will release this evening

**Comment by Bancheis** [comment]
Amazing! Thanks so much!
