### ISSUE TITLE
Crashing when powering up a randomly generated dimension to 'ready' status

### ISSUE THREAD

**Issue by Glitch-v0** [McJty/RFToolsDimensions#401]
Issue description: 
Game crash.

Steps to reproduce: 
Create a random dimension. This was my 4th one. Every 4th one I create and stick in the charger to power it up, it will crash (once hitting 100% and waiting a moment). This error has popped up several times now. On 1.18.2.

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.30
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.18-6.0.13
* RFTools: 1.18-3.0.7
* RFTools Dimensions: 1.18-8.0.5

Related files:

Possibly incompatible mods: 

Relevant logs, if any: 

"The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.m_203334_()" because "this.biome2" is null
Exit Code: 255"

Here's a different error I get:

"The game crashed whilst ticking block entity
Error: java.lang.NoClassDefFoundError: mcjty/lostcities/api/ILostCities
Exit Code: 255"

**Comment by McJty** [comment]
Update. This has just been fixed


Op wo 1 jun. 2022 20:45 schreef Glitch-v0 ***@***.***>:

**Comment by Glitch-v0** [comment]
Thanks! Sorry to be that guy.
