### ISSUE TITLE
[1.18] Crash after I mouse over a specific dimlet

### ISSUE THREAD

**Issue by Peca21** [McJty/RFToolsDimensions#403]
Issue description: 
Placing a cursor over a specific dimlet in a chest causes a crash
Video: https://streamable.com/kwn933

Steps to reproduce: 
1. Open a chest with a problematic dimlet
2. Place a cursor over it
3. Crash

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.41
* McJtyLib: mcjtylib-1.18-6.0.15
* RFTools: rftoolsbase-1.18-3.0.9
* RFTools Dimensions: rftoolsdim-1.18-8.0.6

Relevant logs, if any: 
https://paste.ee/p/vWPw1

**Comment by Peca21** [comment]
I downloaded the code from github, recompiled rftoolsdim and now it works fine. I may be wrong but it looks like you need to do the same, it's like compiler compiled the code expecting getModName to accept any IForgeRegistryEntry (which it did in the previous versions of McJtyLib) but now it doesn't so it crashes. Just recompiling a mod with a new vision of McJtyLib fixes it.

**Comment by Peca21** [comment]
https://github.com/McJtyMods/McJtyLib/commit/56a1cf6de528467bdf531a7853332a9c9b9763a8#

**Comment by McJty** [comment]
Oops indeed. I need to release a new version of rftools dimensions. I will
do that tomorrow

Op za 11 jun. 2022 19:23 schreef Peca21 ***@***.***>:

**Comment by McJty** [comment]
Version 8.0.7 should fix this
