### ISSUE TITLE
Server crash while building new dimension with Lost Cities structures.

### ISSUE THREAD

**Issue by obnys** [McJty/RFToolsDimensions#406]
Issue description: Server crash while attempting to build a dimension containing Lost Cities structure "java.lang.NoClassDefFoundError: mcjty/lostcities/api/ILostCities"

Steps to reproduce: Not sure, I had this the first time since I just started creating dimensions. I sent TNT to an odd dimension, took the dimension tab into a enscriber to extract it and create a new empty dimension without dimlets. the server crashed while I put the dimension tab into the builder. I'm not sure how many percent it loaded before the crash. It was loading pretty fast.

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.25
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 6.0.13
* RFTools: 3.0.7
* RFTools Dimensions: 8.0.5

Possibly incompatible mods: 

Relevant logs, if any: 
https://pastebin.com/cRk20Csv

**Comment by McJty** [comment]
You need to update. Those mods are outdated. Also to be able to do the Lost Cities dimension you need to have Lost Cities installed

**Comment by obnys** [comment]
Woah, that was fast! Thanks so much for the swift reply. I'll give it a try. But I'm wondering, shouldn't Lost Cities be blacklistet when creating an empty dimension when I didn't have the mod installed?

**Comment by McJty** [comment]
yes, that's why you need to update :-)

**Comment by obnys** [comment]
Allright, got it. Again thx a lot. Much appreciated and pls keep up this awesome mod! =)
