### ISSUE TITLE
Dimletpackage appliedenergistics2.json outdated

### ISSUE THREAD

**Issue by obnys** [McJty/RFToolsDimensions#409]
Issue description: 
Having RFToolsdim and Applied Energistics 2 installed there are no AE2 dimlets available by default.

Steps to reproduce: 
Install both, start the server and check the logs:
[Server thread/INFO] [mcjty.lib.setup.DefaultModSetup/]: Reading dimlet package: appliedenergistics2.json, 0 valid dimlets found

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.27
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 6.0.15
* RFTools: 3.0.9
* RFTools Dimensions: 8.0.7

Possibly incompatible mods: 

Relevant logs, if any: 
--> "[Server thread/INFO] [mcjty.lib.setup.DefaultModSetup/]: Reading dimlet package: appliedenergistics2.json, 0 valid dimlets found"

I created a modified "ae2.json" to config\rftoolsdim\ and added it to world\serverconfig\rftoolsdim-server.toml 
--> "[Server thread/INFO] [mcjty.lib.setup.DefaultModSetup/]: Reading dimlet package: ae2.json, 12 valid dimlets found"

This is the content of the modified ae2.json (deleted appliedenergistics2:charged_quartz_ore since it's not available with AE2 11.1.1):
`[
  {
    "type": "block",
    "key": "ae2:chiseled_quartz_block",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:fluix_block",
    "rarity": "rare",
    "create": 400,
    "maintain": 400,
    "ticks": 200,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_block",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_fixture",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_glass",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_ore",
    "rarity": "uncommon",
    "create": 100,
    "maintain": 100,
    "ticks": 100,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_pillar",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:quartz_vibrant_glass",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:sky_stone_block",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:sky_stone_brick",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:sky_stone_small_brick",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  },
  {
    "type": "block",
    "key": "ae2:smooth_sky_stone_block",
    "rarity": "common",
    "create": 10,
    "maintain": 10,
    "ticks": 10,
    "worldgen": true,
    "dimlet": true
  }
]`

**Comment by McJty** [comment]
Will be fixed next release. Thanks!
