### ISSUE TITLE
1.18.2 dimlet obtainning question

### ISSUE THREAD

**Issue by edotenseilove** [McJty/RFToolsDimensions#410]
Hello

I am really sorry to bother you but I would like to know what is the percentage chance of obtaining a random dimlet and if it is affected by looting enchantment.

Have a great day.

**Comment by McJty** [comment]
Yes it should be affected

Here are the chances:

  "commonKnowledgeChance": 0.1,
  "uncommonKnowledgeChance": 0.02,
  "rareKnowledgeChance": 0.002,
  "legendaryKnowledgeChance": 0,
  "commonDimletChance": 0.02,
  "uncommonDimletChance": 0.005,
  "rareDimletChance": 0.0001,
  "legendaryDimletChance": 0.00001
}

**Comment by edotenseilove** [comment]
Thank you very much.
