### ISSUE TITLE
Effects in dimensions making it impossible to use them

### ISSUE THREAD

**Issue by Wdrussell1** [McJty/RFToolsDimensions#412]
Issue description: When you make a dimension there is a HIGH chance to spawn with multiple negative effects. It makes it impossible to break any blocks. Sometimes the effects go away but my last few dimensions they have not gone away. Poison 3 is a drag. It looks like the 1.18 version has taken away the EFFECT dimlets so there is NO way to counteract this. 

Steps to reproduce: Creating basically any dimension. Its especially prevalent when i make the iron block dimension. I get it that its a powerful dimension but really...there should be a dimlet to circumvent effects. 

Versions:
* Minecraft: 1.18
* Forge: 40.1.69
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.18-6.0.15
* RFTools: rftoolscontrol-1.18-5.0.6
* RFTools Dimensions: rftoolsdim-1.18-8.0.7

**Comment by McJty** [comment]
Did you let the dimension power up fully? You get bad effects if there is not enough power in the dimension

**Comment by Wdrussell1** [comment]
After reviewing some things it looks like there might be a bug. The dimensions that I was powering were fully powered per the Dim Tab. They read the full power. However, they were giving these bad effects. However it seems that if you do not supply a certain (unknown) amount of power you still get the bad effects. 

My case, I was using Flux Points paired with cyclic's power pipes. It was enough power to power up the Dimension Tablet is full power though. Which should be all that is required to remove this effect. But for some reason its reading the power output of the pipes instead of relying on the power in the tablet. 

I may not have this exactly right but thats what I can see on the front end. You can replicate this using Direwolf20's 1.18 pack. Put any power source into a flux network, connect with Cyclic's power pipes and then power up basically any dimension but the ones in the 200+ RF/T seem to be the most egregious.

**Comment by McJty** [comment]
That's because power is not stored in the tablet. The tablet is just an item that represents the dimension. It is not the container of the power. The power is stored in the dimension. You cannot power up the dimension through the tablet. It can only be done through the dimension builder if it contains the tablet.

**Comment by McJty** [comment]
You can even have multiple tablets pointing to the same dimension.

**Comment by McJty** [comment]
Is this issue resolved for you now?
