### ISSUE TITLE
RFTools Dimension ERROR

### ISSUE THREAD

**Issue by Oh-Im** [McJty/RFToolsDimensions#413]
Issue description: Whenever I try to launch Divine Journey 2 I get an error msg. stating: An error during startup prevented Minecraft from starting the following mod(s) have been identified as potential causes: RFTools Dimensions

Steps to reproduce: 

Versions:
* Minecraft: 2.12
* Forge: 0.205.1.5800
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools: 7.73
* RFTools Dimensions: 5.71

Possibly incompatible mods: 
[crash-2022-08-12_23.47.25-client.txt](https://github.com/McJtyMods/RFToolsDimensions/files/9331923/crash-2022-08-12_23.47.25-client.txt)

Thank you!

**Comment by Oh-Im** [comment]
Sorry forge versions is: 14.23.5.2860

**Comment by McJty** [comment]
There is a configuration error in the dimlets json file

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools Dimensions (rftoolsdim)
Caused by: java.lang.IllegalStateException: This is not a JSON Array.
