### ISSUE TITLE
[1.18.2] Incompatible with Create 0.5.0d

### ISSUE THREAD

**Issue by matrix07012** [McJty/RFToolsDimensions#415]
Issue description: Crashes on world creation when Create 0.5.0d is installed with error `Can't find dimlet package: create.json`

Steps to reproduce: Install Create 0.5.0d and Flywheel 0.6.5 and create or open a world

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.73
* McJtyLib: 6.0.16
* RFTools: 3.0.10
* RFTools Dimensions: 8.0.8

Relevant logs, if any: 
[crash-2022-08-28_17.00.51-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/9439915/crash-2022-08-28_17.00.51-server.txt)

**Comment by matrix07012** [comment]
Issue remains with Forge 40.1.80 McJtyLib: 6.0.17 and RFTools Dimensions: 8.0.9

**Comment by McJty** [comment]
That's not something RFTools Dimensions does. It doesn't have or try to use create.json. So probably something added that to your configs. Edit rftoolsdim-server.toml and remove create.json there
