### ISSUE TITLE
how to get block's block dimlet with /give command?

### ISSUE THREAD

**Issue by onenok** [McJty/RFToolsDimensions#417]
how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?how to get block's block dimlet with /give command?

**Comment by McJty** [comment]
Please make proper bug reports
