### ISSUE TITLE
Block absorber stuck at 100% no block set

### ISSUE THREAD

**Issue by Xplodin** [McJty/RFToolsDimensions#419]
Issue description: 
cant use block absorber on thermals machine frames 
Steps to reproduce: 

Versions:
* Minecraft: 1,16,5
* Forge: 36.2.34
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.1.8
* RFTools: 2.1.5
* RFTools Dimensions: 7.0.19 

Possibly incompatible mods:  optifine, immersive engineering
modpack: latest of ragnamod vi

Relevant logs, if any: 
https://gist.github.com/Xplodin/83c62686ff318e436ad9870c5ecab2d1

**Comment by McJty** [comment]
Why would you even want to use the block absorber on that? Of course it doesn't work. That's not a block you can place down so it cannot be used to make dimensions. Also why???

**Comment by Xplodin** [comment]
> Why would you even want to use the block absorber on that? Of course it doesn't work. That's not a block you can place down so it cannot be used to make dimensions. Also why???

it is a block you can place down...
same thing with steel chassis from mekanism...
You might want to look further into issues rather than assuming that my issue isnt valid.
In modpacks, some things can be insanely difficult to make, such as these frames, so why not is the answer?

**Comment by McJty** [comment]
Well if it can be placed down then it's a matter of configuring it to be useful as a dimlet. Dimlet materials are whitelisted. If there is no config to enable it as a dimlet then it will not be a dimlet

**Comment by Xplodin** [comment]
Thats the odd part. it does have a dimlet.
I checked with both materials. Both can be made and absorbed, but the absorber block wont take it

**Comment by McJty** [comment]
hmm ok. Show a screenshot of how you are doing it then

**Comment by Xplodin** [comment]
I place down the blocks normally or with a building wand, and put the absorber on top of the block. I make sure it touches no other blocks besides the block beneath it. but there is an alternate fix for this if this is too much trouble. A recipe to convert the absorber to default state when it doesnt work with this or other blocks. I mean I could do this manually with kubejs but I think itd be dope to convert a absorber back to default. Sorry for the delay

**Comment by McJty** [comment]
Can you show me a screenshot of the tooltip of the block absorber? Also did you absorb 256 blocks?

**Comment by McJty** [comment]
Also actually what is the problem? Stuck at 100% is normal. 100% is the maximum. I mean 100% literally means full

**Comment by Xplodin** [comment]
It just says 100%, doesnt absorb, and renders the absorber useless afterwards with a <not set> tag Ill grab a screenshot in a bit when my game decides to load.

**Comment by McJty** [comment]
Well after 100% it will of course stop absorbing. When the absorber is at 100% you can use it to make a dimlet

**Comment by Xplodin** [comment]
![image](https://user-images.githubusercontent.com/13007677/195968082-4de33243-783c-4b4d-8be6-4609c9e1ad3b.png)


![2022-10-15_00 08 17](https://user-images.githubusercontent.com/13007677/195968127-f9a5e5e9-c6b5-4eba-825b-bf46aee2fb5c.png)


It says 100% instantly after placing it on a single or multiple steel casing blocks

**Comment by Xplodin** [comment]
![image](https://user-images.githubusercontent.com/13007677/195968173-920c70e1-e83c-41a9-bfff-acaf99fcd5de.png)

also heres the image for the dimlet creation

**Comment by McJty** [comment]
Hmm not sure then

**Comment by McJty** [comment]
Can you show how you are actually trying to create the dimlet?
