### ISSUE TITLE
Shutting down internal server...

### ISSUE THREAD

**Issue by Klausthorn** [McJty/RFToolsDimensions#42]
Made my first dimension (random), traveled there, after a few seconds (less than 20, likely less than 10) I get:

"Shutting down internal server..."

"Connection Lost."

If I restart Minecraft then I start at the new dimension and after a few seconds the symptoms repeat.

From the Log:

> [14:48:08] [Client thread/WARN]: Failed to load texture: rftoolsdim:textures/sky/stars2.png
> java.io.FileNotFoundException: rftoolsdim:textures/sky/stars2.png
> 
> ...
> 
> [14:48:18] [Server thread/WARN]: Tried to over-fill a container
> 
> [14:48:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 9104ms behind, skipping 182 tick(s)
> 
> [14:48:22] [Server thread/INFO]: klausthorn lost connection: TextComponent{text='A fatal error has occurred, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
> 
> [14:48:22] [Server thread/INFO]: klausthorn left the game

Details:

Single Player.
rftoolsdim-1.10-4.41.jar
rftools-1.10-5.51.jar
mcjtylib-1.10-2.1.4.jar
Minecraft 1.10.2
Windows 7 SP1 64 Bit
6 GB RAM

**Comment by McJty** [comment]
I need the complete log

**Comment by Klausthorn** [comment]
[latest.txt](https://github.com/McJty/RFToolsDimensions/files/519642/latest.txt)

**Comment by McJty** [comment]
There is indeed a bug in rftools dimensions with the missing texture but that's not what is causing the crash. Another mod is causing a crash and the reason has to do with:

[14:48:18] [Server thread/WARN]: Tried to over-fill a container

Not sure what would cause that though

**Comment by Klausthorn** [comment]
Thanks for the quick reply!

**Comment by McJty** [comment]
Ok, seems there is a mod in your pack that does something wrong with loot. This message is generated when chests are filled with loot

**Comment by Klausthorn** [comment]
This does not happen in the overworld, the nether or in the dimension form "NomadicTents".

So there could be some interaction between another mod and the way that RFToolsDImensions create dimensions.

Mods I also have: 
- Futurepack (fills a lot of chests with a lot of items).   <<< LIKELY
- biomes'O'Plenty, 
- WAWLA, 
- JEI, 
- Crankerer's Odyssey (fills a few chests with a few items), 
- FinderCompass, 
- JourneyMap, 
- myBiomes (not chosen during world gen), 
- placemod (does not do anything, maybe has to be chosen during world gen)

**Comment by Klausthorn** [comment]
created new world without futurepack mod.

still happens :-(
[latest.log.txt](https://github.com/McJty/RFToolsDimensions/files/528251/latest.log.txt)

**Comment by Klausthorn** [comment]
Note: no error about overfilling a container, no exception, no (logged) error at all

**Comment by Klausthorn** [comment]
removing mod "FinderCompass" helped.

Found clues (exceptions,errors) in the fml-client-latest.log
