### ISSUE TITLE
Ticking Entity and Crash

### ISSUE THREAD

**Issue by kizeren** [McJty/RFToolsDimensions#421]
Issue description:  Ticking entity and crash

Steps to reproduce: 
Not even sure how it happened.

Versions:
* Minecraft: 1.19.2
* Forge: 1.19.2-43.1.57
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:mcjtylib-1.19-7.0.5
* RFTools:
* RFTools Dimensions: 

RF* 
rftoolsbase-1.19.1-4.0.3
rftoolsbuilder-1.19.1-5.0.4
rftoolscontrol-1.19-6.0.1
rftoolspower-1.19-5.0.1
rftoolsstorage-1.19-4.0.3
rftoolsutility-1.19-5.0.3

Complete MODS List; 
![modslist](https://user-images.githubusercontent.com/2472534/206919578-03ec2e8e-c022-4510-b780-4857b43ca8df.PNG)

Possibly incompatible mods: 

Relevant logs, if any:  https://paste.debian.net/1263687/   ---- Line 516

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed next version
