### ISSUE TITLE
1.19.2 [ Researcher crashes game ]

### ISSUE THREAD

**Issue by Mrwimz** [McJty/RFToolsDimensions#423]
**Issue description:** 
When i put in uncommon lost knowledge (common worked) in the researcher, the game crashes at the end.
 I added the mod to ATM 8, may be the reason why?

**Steps to reproduce:** 
Create a new world, add a uncommon lost knowledge to a researcher, wait for it to finish, Then you should experience the crash!

Versions:
* Minecraft: 1.19.2
* Forge: 43.1.45 (All The Mods 8 1.0.5 )
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.19-7.0.6
* RFTools: 1.19.1-4.0.3
* RFTools Dimensions: 1.19-9.0.0

Possibly incompatible mods: 

Relevant logs, if any: 
[crash-2022-12-13_12.31.26-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/10217476/crash-2022-12-13_12.31.26-server.txt)

**Comment by McJty** [comment]
I'll check it out soon

**Comment by McJty** [comment]
Fixed next version
