### ISSUE TITLE
1.19 dimlets.json not created during startup

### ISSUE THREAD

**Issue by MxMueller99** [McJty/RFToolsDimensions#427]
Issue description: 

I recently started playing the ATM 8 Modpack which comes with the base rftools already installed. So I also installed rftools dimensions and wanted to create custom dimlets. I looked up the config files under "config\rftoolsdim\" but couldn't find any file there.
I also tried creating a "dimlets.json" in this directory with my dimlets, which also didn't work. 

Steps to reproduce: 

Versions:
* Minecraft: 1.19.2
* Forge: 43.1.55
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.0.6
* RFTools: 4.0.3
* RFTools Dimensions: 9.0.3

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by McJty** [comment]
dimlets.json is outdated. It no longer works like that. It's now a datapack. Like this:

https://github.com/McJtyMods/RFToolsDimensions/tree/1.19/src/main/resources/data/rftoolsdim/dimletpackages

**Comment by MxMueller99** [comment]
> dimlets.json is outdated. It no longer works like that. It's now a datapack. Like this:
> 
> https://github.com/McJtyMods/RFToolsDimensions/tree/1.19/src/main/resources/data/rftoolsdim/dimletpackages

Is there any tutorial on how to change these files? Because as fas as I understand they are part of the source code.

**Comment by McJty** [comment]
yes, you don't modify these files. Instead you create your own package similar to those and then modify the configs to point to those. Check out the server configs in your world folder. There they are listed:

```
#Dimlets settings
[dimlets]
	#This is a list of dimlet packages that will be used. Later dimlet packages can override dimlets defined in earlier packages. You can place these packages in the 'config/rftoolsdim' folder
	dimletPackages = ["base.json", "vanilla_blocks.json", "vanilla_tags.json", "vanilla_fluids.json", "vanilla_biomes.json", "vanilla_structures.json", "rftools.json", "appliedenergistics2.json", "biggerreactors.json", "bigreactors.json", "botania.json", "immersiveengineering.json", "mekanism.json", "powah.json", "quark.json", "tconstruct.json", "thermal.json", "biomesoplenty.json", "emendatusenigmatica.json"]
```

**Comment by MxMueller99** [comment]
> yes, you don't modify these files. Instead you create your own package similar to those and then modify the configs to point to those. Check out the server configs in your world folder. There they are listed:
> 
> ```
> #Dimlets settings
> [dimlets]
> 	#This is a list of dimlet packages that will be used. Later dimlet packages can override dimlets defined in earlier packages. You can place these packages in the 'config/rftoolsdim' folder
> 	dimletPackages = ["base.json", "vanilla_blocks.json", "vanilla_tags.json", "vanilla_fluids.json", "vanilla_biomes.json", "vanilla_structures.json", "rftools.json", "appliedenergistics2.json", "biggerreactors.json", "bigreactors.json", "botania.json", "immersiveengineering.json", "mekanism.json", "powah.json", "quark.json", "tconstruct.json", "thermal.json", "biomesoplenty.json", "emendatusenigmatica.json"]
> ```

Thank you alot
