### ISSUE TITLE
Error in one of the Rf tools dimentions dependencies 

### ISSUE THREAD

**Issue by Mr-Mushasha** [McJty/RFToolsDimensions#428]
![image](https://user-images.githubusercontent.com/114179768/214078105-abf97865-bf06-4ea7-9fcb-fe24719b7c3a.png)

**Comment by McJty** [comment]
More details please. What version of forge and which McJtyLib did you install?

**Comment by McJty** [comment]
And version of Minecraft

**Comment by McJty** [comment]
Wrong version of McJtyLib
