### ISSUE TITLE
(1.19.2) Researcher crashes the game when inserting knowledge

### ISSUE THREAD

**Issue by LvsrsRedDragon** [McJty/RFToolsDimensions#430]
Issue description: 
As stated in title.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.3
* McJtyLib: 1.19-7.1.4
* RFTools: 1.19.1-4.1.3
* RFTools Dimensions: 1.19.3-9.0.4

Possibly incompatible mods: 
Rubidium (maybe? The log states something about it)
Oculus

Relevant logs, if any: 
https://pastebin.com/GyzY2PkN

**Comment by McJty** [comment]
You are using the 1.19.3 version of RFTools Dimensions. Go back to the 1.19.2 version
