### ISSUE TITLE
Crash when deleting dimension in 1.19.2

### ISSUE THREAD

**Issue by ShinQdan** [McJty/RFToolsDimensions#435]
Issue description: 
When deleting any dimension using TNT in editor the server crashes. Log in the attached files. I assume this is probably due to the fact that receivers have not been implemented yet in 1.19.2 and thus there is no receiver to be deleted in the dimension and null pointer exception thrown. I also assume this will be fixed when the receivers are implemented but I want to make sure and point out this error.

Steps to reproduce: 
1. Create any dimension.
2. Optionally go to the dimension (via tp command because I can't see teleports yet in 1.19.2) and back.
3. Delete by sending TNT in dimension editor.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.4
* McJtyLib: 7.1.5
* RFTools: 4.1.4
* RFTools Dimensions: 9.1.1

Relevant logs, if any: 
[crash-2023-02-21_23.34.21-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/10798412/crash-2023-02-21_23.34.21-server.txt)

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Oh you don't mave RFTools Utility. The teleportation system is part of that mod so you need that

**Comment by ShinQdan** [comment]
Oh, I didn't realize they are in a different mod. Also didn't bother looking there for them because Rftools Utilities isn't mentioned anywhere that it contains the teleportation devices. Maybe you should consider adding it as an optional dependency to note the fact they are there. Or even as required dependency because not having it causes this error. Or maybe change the Dimensions so that Utilities are not obligatory for it to work properly.
