### ISSUE TITLE
Can't add new dimlets for another mod

### ISSUE THREAD

**Issue by Shortymus** [McJty/RFToolsDimensions#436]
Issue description: Added new mod to a dimlet json - however they aren't showing in game for The Vault mod (https://vault-hunters.fandom.com/wiki/Vault_Gem_Ore )

Steps to reproduce: 
- Install modpack
- Add userdimlet.json to rftoolsdim config folder
- Run
- Server calls userdimlet.json but doesn't load the new ore block into the dimlet table

Versions:
* Minecraft: 1.18.2
* Forge: 40.2.1 - Server
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.18-6.0.20
* RFTools: 1.18-3.0.11
* RFTools Dimensions: 1.18-8.0.9

Possibly incompatible mods: 

Relevant logs, if any: Curseforge modpack attached as well to enable replication.
[Files.zip](https://github.com/McJtyMods/RFToolsDimensions/files/10802538/Files.zip)
[Vault_Hunters_3rd_Edition-Update-6Hf.zip](https://github.com/McJtyMods/RFToolsDimensions/files/10802539/Vault_Hunters_3rd_Edition-Update-6Hf.zip)

**Comment by McJty** [comment]
Fixed I assume?
