### ISSUE TITLE
Cannot remove dimensions with /rftoolsdim forget

### ISSUE THREAD

**Issue by sharkck** [McJty/RFToolsDimensions#437]
Issue description: 
Cannot remove a dimension
Steps to reproduce: 

I used /rftoolsdim forget (dim name) and it says the dimension is removed but upon server restart, it still loads it.  I even removed the dimensions, stopped the server and then deleted the dimension folders from the world/dimensions folder and the server regenerated them after it started up.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.4
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.1.5
* RFTools: 4.1.4
* RFTools Dimensions: 9.1.1

Possibly incompatible mods: 

Relevant logs, if any:

**Comment by McJty** [comment]
The forget command only makes rftoolsdim forget about it. It doesn't remove the dimension. You can remove it manually by removing the dimension folder

**Comment by sharkck** [comment]
The command does not work properly though.  When the server is restarted, the dimension is reloaded even if you delete the folder while the server is shut down.
