### ISSUE TITLE
Fluid Absorber counts non-source blocks as being absorbable

### ISSUE THREAD

**Issue by luan122** [McJty/RFToolsDimensions#438]
same problem as #373

Versions:
* Minecraft:  1.19.2
* Forge:  43.2.0
* McJtyLib: 1.19-7.1.5
* RFTools: 1.19.1-4.1.4
* RFTools Dimensions: 1.19.3-9.1.1

Possibly incompatible mods: none

Relevant logs, if any: none
block information: https://prnt.sc/y8uxqIEvE5RN

**Comment by McJty** [comment]
Checking it out

**Comment by McJty** [comment]
Hmm I cannot reproduce this. Can you show me how you did it?

**Comment by luan122** [comment]
Just put it on the ground and pickup will display 100%;
Tried the same in ocean and pickup will display 100%;
Put side the fluid and pickup will display 100%;

all of them with fluid not set

**Comment by McJty** [comment]
Can you show screenshots? I can't reproduce it at all

**Comment by luan122** [comment]
I made a record to reproduce what I'm trying to do:
https://1drv.ms/v/s!AuIzNte0aX8Ng8xsh4u5z9-axNfWTA?e=ZyoVgX

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Ok. I tried it. It does give a weird tooltip but it actually still works. If you later put that over a valid fluid block it will continue absorbing it

**Comment by McJty** [comment]
I will improve it a bit though

**Comment by McJty** [comment]
Tooltip fixed next release

**Comment by luan122** [comment]
I tried to use it and didnt worked... i forgot the block there with the liquid over it for more than 3h
https://prnt.sc/tkyYF5NZPPEW
https://prnt.sc/ZrBQH6Iihdp6

**Comment by luan122** [comment]
just ignore my last reply, the liquid need to be below the block, not above....
