### ISSUE TITLE
Blacklisted Dimlet

### ISSUE THREAD

**Issue by MrAmericanMike** [McJty/RFToolsDimensions#44]
I get a "Blacklisted Dimlet" but from what I see on the configs, I don't know where it is getting blacklisted.

What could be happening?

http://imgur.com/a/MDKtW

And the configs

http://pastebin.com/p1BEgaXz

Using rftoolsdim-1.10-4.40

**Comment by McJty** [comment]
How did you obtain that dimlet? If you did it with createdimlet then remember that it is createdimlet Sky normal and not Normal (i.e. lowercase 'n')

**Comment by MrAmericanMike** [comment]
On the recipes, when you hoover on them, they show as blacklisted http://imgur.com/a/DwOZC

**Comment by McJty** [comment]
Will check it out soon

**Comment by McJty** [comment]
They are not blacklisted for me.  First try upgrading rftools dimensions. Also do you have a custom dimlets.json?

**Comment by McJty** [comment]
Closing due to lack of response

**Comment by MrAmericanMike** [comment]
Sorry I guess I didn't check GitHub on the last days. Gonna try updating, but I believe I was up to date when I reported the issue. 

I do have a custom dimlets.json file, it's the one on the pastebin on the OP. Here the link, maybe something I modified there, messed those dimlets, dunno. http://pastebin.com/p1BEgaXz

Gonna update the mod and do more testing tomorrow also and come back with the update and see if it still happening ;)

**Comment by MrAmericanMike** [comment]
Ok updated to 4.43 and yes the dimlet still shows as Blacklisted.

All I see on the configs related with Sky Dimlets is:

>   {
>     "filter": {
>       "type": "sky"
>     },
>     "settings": {
>       "rarity": 0,
>       "create": 100,
>       "maintain": 1,
>       "ticks": 1,
>       "worldgen": true,
>       "dimlet": true
>     }
>   },
> 
>   {
>     "filter": {
>       "name": "minecraft:sky",
>       "type": "biome"
>     },
>     "settings": {
>       "rarity": 5,
>       "create": 5000,
>       "maintain": 10000,
>       "ticks": 100,
>       "worldgen": false,
>       "dimlet": true
>     }
>   },

Not sure what I have wrong here to have those dimlets as blacklisted, maybe some category above it that is blaklisting them?

**Comment by flobernd** [comment]
Same for me. It seems like your crafting recipe creates the dimlet with uppercase letter.

**Comment by 7eggert** [comment]
FYI and because I found this thread: While crafting, I'm seeing a blacklisted dimlet, too, on a local client using default rftools config. It would be craftable (but I didn't).

(I don't actually care about these dimlets.)
