### ISSUE TITLE
No trees generating in rftools dimensions

### ISSUE THREAD

**Issue by Onlyintexas** [McJty/RFToolsDimensions#441]
Issue description: 
Trees aren't generating in created rftools dimensions
Steps to reproduce: 
any dimension created will not have trees

Versions:
* Minecraft: 1.18.2
* Forge: 40.2.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 6.0.20
* RFTools: 3.0.12
* RFTools Dimensions: 8.0.9

Possibly incompatible mods: I am using oculus instead of optifine due to the incompatibilities optifine has with most mods.

Relevant logs, if any:

**Comment by McJty** [comment]
Fixed in next release
