### ISSUE TITLE
[1.19.2] Worldgen is broken when Biomes o' Plenty is installed

### ISSUE THREAD

**Issue by ShinQdan** [McJty/RFToolsDimensions#442]
Issue description: 
I fond that when Biomes o' Plenty is installed world generation in RFT dimensions is broken - no trees, no ores, no structures. Nothing, only terrain generates properly. Also all dimlets like spheres and tendrils have no effect.

Steps to reproduce: 
Install RFTools and Biomes o' Plenty.
Create new world and any normal dimension.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.4
* McJtyLib: 7.1.5
* RFTools: 4.1.5
* RFTools Dimensions: 9.1.2

Possibly incompatible mods: 
Biomes o' Plenty

Relevant logs, if any: 
[debug.log](https://github.com/McJtyMods/RFToolsDimensions/files/11022947/debug.log)
[latest.log](https://github.com/McJtyMods/RFToolsDimensions/files/11022948/latest.log)

**Comment by McJty** [comment]
What version of TerraBlender? Is that the latest one?

**Comment by ShinQdan** [comment]
> What version of TerraBlender? Is that the latest one?

2.0.1.136 (latest for 1.19.2)
I also tried on the newer version of Forge (43.2.7) today and the bug remains.

**Comment by ingrac42** [comment]
I also have seen this problem.  Server has:

- TerraBlender 1.19.25-2.0.1.128
- McJtylib 1.19-7.1.5
- RFBase 4.1.5
- RFDim 9.1.2
- Forge 43.2.4
- BiomesOPlenty 1.19.2-17.1.1.162

Here's a "Forest"

https://cdn.discordapp.com/attachments/1069849121915154483/1089303018261987388/2023-03-25_15.41.03.png

Sea Grass, Kelp also absent.  The Broken Portals dimlet works, but I can't get any features or other structures.

**Comment by ShinQdan** [comment]
I also found the world generates correctly sometimes, I think when there are no biomes from Biomes o' Plenty involved. I mean I experimented with some random worlds and some of them were fine but I think they all were single biome from vanilla.

**Comment by McJty** [comment]
To be honest. I have no idea what more I can do here. I don't understand the problem. So if the people from TerraBlender can tell me how I can fix this then that would be ideal

**Comment by McJty** [comment]
I think I know what's wrong but not sure what the best solution is here. I'll talk to the BoP authors about this

**Comment by McJty** [comment]
I made a small modpack with all rftools mods, TerraBlender and RFToolsDimensions on 1.19.4 and so far everything seems to work fine. 1.18.2 and 1.19.2 and 1.19.3 will have the same fix but I'll do some more testing to be sure

**Comment by McJty** [comment]
So far tests are doing well but in testing I found out the biome dimlets are missing so I need to fix that as well

**Comment by McJty** [comment]
Fixed in the next release (hopefully)
