### ISSUE TITLE
[1.19.2] Crash when building first dimension on a new game

### ISSUE THREAD

**Issue by ShinQdan** [McJty/RFToolsDimensions#443]
Issue description: 
After I create a new world and use Dimension Builder for the first time in this world it stops on 99% for a few seconds and the game crashes. After launching the game again and loading the world the dimension is not created and the tab has weird values like maintenance -20 RF/tick. But every next dimension builds fine even the first one created again on a different tab.

Steps to reproduce: 
1. Create new world.
2. Create new dimension tab with any dimmlets or just random/empty.
3. Build the tab with dimension builder.
4. Crash on 99%.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.4 or 43.2.7
* McJtyLib: 7.1.5
* RFTools: 4.1.5
* RFTools Dimensions: 9.1.2

Possibly incompatible mods: 
When it first occured I had Immersive Engineering 9.2.0-162 and JEI 11.6.0.1013 installed.

Relevant logs, if any: 
[crash-2023-03-21_18.05.16-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/11032024/crash-2023-03-21_18.05.16-server.txt)
[debug.log](https://github.com/McJtyMods/RFToolsDimensions/files/11032025/debug.log)
[latest.log](https://github.com/McJtyMods/RFToolsDimensions/files/11032026/latest.log)

**Comment by CValentine2325** [comment]
Had the same issue as above, using version 9.1.2 - had to use that version as trying to add to ATM8 1.0.15 and all other versions crashed on start-up

**Comment by n0t49a1n** [comment]
Replicatable on direwolf20 mod pack

Versions:
Minecraft: 1.19.2
Forge: 43.2.6
McJtyLib: 7.2.3
RFToolsBase: 4.1.7
RFTools Dimensions: 9.1.5

nearly 100% time with a flat world and using vanilla blocks
`[16Apr2023 23:25:44.430] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for rftoolsdim:coalblk
net.minecraft.ReportedException: Exception generating new chunk`
using coal block or deepslate iron ore, and flat dimlet only

**Comment by McJty** [comment]
I'll check it out soon once I have a chance

**Comment by McJty** [comment]
I just released RFTools Dimensions 9.1.6 for 1.19.2 which should fix this issue. I'm not closing this issue until you can confirm it works now. If it still crashes please give me a new crash report. Thanks

**Comment by n0t49a1n** [comment]
i have been able to create 3 worlds now  on direwolf20 pack 1.8.0 with just rfdim mod updated to 9.1.6
tested lunite, ironblock, coalblock 3 that caused me to crash before

**Comment by McJty** [comment]
Thanks for testing!
