### ISSUE TITLE
Game Crashes 1.19.2 when looting Biome Dimlets from endermen

### ISSUE THREAD

**Issue by Saereth** [McJty/RFToolsDimensions#445]
Issue description: 

Steps to reproduce: 
While in the nether, killing Endermen, received loot. When I moused over it to see what it was, game crash. Based on the icon, I was able to determine that it is a 'Biome Dimlet'. This is now stuck in my inventory. Any help would be appreciated.

Versions:
* Minecraft: 1.19.2 
* Forge: 43.2.6
* McJtyLib: mcjtylib-1.19-7.2.2
* RFTools: rftoolsbase-1.19-4.1.7
* RFTools Dimensions: rftoolsdim-1.19.2-9.1.4

Possibly incompatible mods: 
This is with the FTB Skies pack on the ftbapp.

Relevant logs, if any: 
https://github.com/FTBTeam/FTB-Modpack-Issues/files/11179672/crash-2023-04-07_07.50.39-client.txt

Also several other players and partners reporting this in the original issues here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2982

**Comment by McJty** [comment]
Fixed in 1.19.2, 1.19.3, and 1.19.4
