### ISSUE TITLE
[1.19.2] rftoolsdim dimlet tooltip render crashes client 1.19.2

### ISSUE THREAD

**Issue by BradiiBrad** [McJty/RFToolsDimensions#446]
Issue description: 
So mouseing over a certain dimlet from killing enderman crashes client. Not all dimlets do this just a certain one but cant tell as he never renders the tooltip

Steps to reproduce: 
Random Dimlet, can not tell which one.

Versions:
Modpack : FTB Skies

* Minecraft: 1.19.2
* RFTools: 1.19.2
* RFTools Dimensions: 1.19.2

Relevant logs, if any: https://pastebin.com/YggAJhph

**Comment by McJty** [comment]
In the future please add the version of the mod and not only the Minecraft version. In any case this is already fixed
