### ISSUE TITLE
Creating a New Dimension Causes Crash on Server

### ISSUE THREAD

**Issue by kraken5567** [McJty/RFToolsDimensions#451]
Issue description: Loading an RFTools Dimension for the first time causes inevitable server crash

Steps to reproduce: 

Run Forge Server
Make any sort of dimension at all
go in with transmitter (and get kicked)
rejoin (server crash)

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.39
* CompatLayer (only if on Minecraft 1.10 or 1.11): 
* McJtyLib: mcjtylib-1.16-5.1.8.jar
* RFTools: rftoolsbase-1.16-2.1.5.jar
* RFTools Dimensions: rftoolsdim-1.16-7.0.21.jar

Possibly incompatible mods: Immersive Portals (set to not adaptive)

Relevant logs, if any: https://pastebin.com/1pxu43Rj (crash log & system info)

**Comment by McJty** [comment]
Yes, Immersive Portals is not compatible with RFTools Dimensions. You'll have to choose one
