### ISSUE TITLE
Total game crash when using researcher to research lost knowledge

### ISSUE THREAD

**Issue by Atroskelis** [McJty/RFToolsDimensions#453]
Issue description: The game crashed when the researcher reached 100% on researching. Can't load savefile anymore

Steps to reproduce:  Build researcher, power using immersive power, insert ancient knowledge, wait till 100% -> crash

Versions:
* Minecraft: 1.19.3
* Forge: 44.1.23
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.2.5
* RFTools: 4.1.7
* RFTools Dimensions: 10.0.2

Possibly incompatible mods:  I don't use any of those

Relevant logs, if any: MultiMC pastebin - https://paste.ee/p/l6weA

**Comment by McJty** [comment]
Update. That bug has been fixed some time ago
