### ISSUE TITLE
Mod crashes with Waytones mod.

### ISSUE THREAD

**Issue by kogisa** [McJty/RFToolsDimensions#454]
Issue description: 

Steps to reproduce: 

Versions:
* Minecraft: 1.19.2
* Forge: NO
* Fabric: Yes 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:
* RFTools Dimensions: 

Possibly incompatible mods: 

Relevant logs, if any: 
[crash-2023-05-21_20.28.51-client.txt](https://github.com/McJtyMods/RFToolsDimensions/files/11537037/crash-2023-05-21_20.28.51-client.txt)

**Comment by kogisa** [comment]
Running ALL of FABRIC 6. version 1.5.4

**Comment by McJty** [comment]
My mod doesn't work on fabric. It's a forge mod
