### ISSUE TITLE
Abrupt crash when renaming Realized Dimension Tab (from creative inventory)

### ISSUE THREAD

**Issue by brisingraerowing** [McJty/RFToolsDimensions#46]
I pulled a realized dimension tab from the creative inventory to act as the item in an item frame on a storage system for RFTools Dimensions items, and tried to rename it to RFTools Dimensions, and promptly got a crash.

[Crash Report](https://gist.github.com/BrisingrAerowing/05c8c687341d59d52af7a2b4bece61fd)

**Comment by McJty** [comment]
Well you're not supposed to do that. Not much that I can do against this really
