### ISSUE TITLE
1.20.1 game crash on teleport

### ISSUE THREAD

**Issue by hallool** [McJty/RFToolsDimensions#460]
Issue description: 
hello on version 1.20.1 (BETA) the game crashes when im trying to teleport to the dimension so now im stuck if i load my world i spawn at the teleporter and it crashes over and over

Steps to reproduce: 
i just created a random dimension and teleported energy was full on all system

Versions:
* Minecraft: 1.20.1
* Forge: 1.20.1  47.1.37
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.20.1-8.0.0 (BETA)
* RFTools: rftoolsbase-1.20.1-5.0.0 (BETA)
* RFTools Dimensions: 1.20.1-11.0.0 (BETA)

Possibly incompatible mods: 
ars-nouveau

Relevant logs, if any: 
https://drive.google.com/drive/folders/1-6WU6DHANaUxVAZu9Sp7jWFPFiiPQOQs?usp=sharing

**Comment by McJty** [comment]
It's crashing in EnderTank. Nothing to do with this mod

**Comment by hallool** [comment]
The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Cannot invoke "mcjty.rftoolsdim.modules.dimlets.data.DimletRarity.ordinal()" because "this.rarity" is null

so i loaded up a backup deleted ender tanks and all its relations created a new random dimension traveled the that dimension i saw the dimension for idknow 2 secs then the game crashed and this error code spawned

**Comment by McJty** [comment]
Please go back to Forge 47.1.3. Due to the current problems with Forge and NeoForge my mod is only compatible up to forge 47.1.3
