### ISSUE TITLE
1.20.1 game (still) crash on dimesnion teleport (sry for re opening but still need help..)

### ISSUE THREAD

**Issue by hallool** [McJty/RFToolsDimensions#461]
It's crashing in EnderTank. Nothing to do with this mod

_Originally posted by @McJty in https://github.com/McJtyMods/RFToolsDimensions/issues/460#issuecomment-1643179974_  .
            
The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Cannot invoke "mcjty.rftoolsdim.modules.dimlets.data.DimletRarity.ordinal()" because "this.rarity" is null

so i loaded up a backup deleted ender tanks and all its relations created a new random dimension traveled to that dimension i saw the dimension for idknow 2 secs then the game crashed and this error code spawned

[latest.log](https://github.com/McJtyMods/RFToolsDimensions/files/12112601/latest.log)

[debug.log](https://github.com/McJtyMods/RFToolsDimensions/files/12112604/debug.log)

[crash-2023-07-20_19.29.18-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/12112650/crash-2023-07-20_19.29.18-server.txt)

**Comment by McJty** [comment]
Ok. I'll check it out later. Now on holiday so it will have to wait

**Comment by hallool** [comment]
found it out only works on forge 1.20.1 - 47.1.3

**Comment by McJty** [comment]
Ah, what version of forge were  you using before?

**Comment by hallool** [comment]
i was using the newest ones

**Comment by McJty** [comment]
yes, there is a bug in forge. Stay at 47.1.3 for now

**Comment by hallool** [comment]
btw how do i delete the dimesnions? like completely? didnt find anything about it on the internet just the /rftools forget command but it dosnt delte it..

**Comment by McJty** [comment]
Send a TNT block to the dimension using the dimension editor

**Comment by hallool** [comment]
they still are in the dialing device..

**Comment by McJty** [comment]
Yes, that's separate. The dialer doesn't know about dimensions. It only knows about matter receivers and it doesn't know it's gone. There is a command to clean those up. Check /rftoolsutility

**Comment by hallool** [comment]
thx
