### ISSUE TITLE
RFTools Dimensions crashing server

### ISSUE THREAD

**Issue by Peter192547** [McJty/RFToolsDimensions#462]
Issue description: I generated a world that had 2 dimlets. Forge:ores and as feature dimlet Tendrils

Steps to reproduce: Make a server with Rftools Dimensions and generate a world with forge:ores and Tendrils

Versions:
* Minecraft: 1.20.1
* Forge: 47.1.3
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 8.0.0
* RFTools: 5.0.0
* RFTools Dimensions: 11.0.0

Possibly incompatible mods: 

Relevant logs, if any: 
[crash-2023-07-23_17.05.46-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/12138995/crash-2023-07-23_17.05.46-server.txt)

**Comment by McJty** [comment]
Can you please actually fill in the template? Like version and so on

**Comment by Peter192547** [comment]
i filled it in

**Comment by andyrosu12** [comment]
Will this ever be fixed? I really enjoy this mod but I can't use it with any other mod which adds biomes or features to biomes. Always getting the same error message as in the above log.

**Comment by McJty** [comment]
This seems to be an incompatibility with Twilight Forest. I don't know what mod is doing things wrong but best to also report to them so they can help investigate

**Comment by McJty** [comment]
Fixed in 11.0.2
