### ISSUE TITLE
Workbench graphical error and cant build dimlets

### ISSUE THREAD

**Issue by rpgpro1** [McJty/RFToolsDimensions#463]
Issue description: When using the workbench and loading a recipe, the graphics are shifted to the right and will not create dimlet even if correct ingredients are added.

Steps to reproduce: I created a clean install with only your RFTools mods and Waystones installed. I added an adjacent knowledge holder and installed researched knowledge to unlock the recipes. When opening the workbench, you can see the graphic glitch. I will attach a screenshot if possible.

Versions:
* Minecraft: 1.20.1
* Forge: 47.1  (have tried with newer ones as well)
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.20-8.0.1   (tried with 8.0.0 as well)
* RFTools: 1.20-5.0.0
* RFTools Dimensions: 1.20-11.0.0

Possibly incompatible mods: Clean install, nothing but your mods and Waystones mod.

Relevant logs, if any: 
![DimensionsWorkbenchGlitch](https://github.com/McJtyMods/RFToolsDimensions/assets/79297803/6b3b0777-7b26-4817-beab-abcb5f86e0e3)

**Comment by joleme81** [comment]
I'm having the same issue as well. Can search, can double click a dimlet and it will pull things into the slots but hitting 'create' does nothing.

**Comment by McJty** [comment]
@joleme81 is create doesn't do anything that means you are missing some ingredient. Did you fill ALL the slots on the top with the correct thinig? (all four slots)

@rpgpro1 so without waystones it works correctly? Was this reported to the waystones mod? Because I'm not sure what I can do about this from my side

**Comment by manmaed** [comment]
I can confirm this is not waystones
Minecraft: 1.20.1
Neo: 47.1.76
Mods:
mcjtylib-1.20-8.0.3
rftoolsbase-1.20-5.0.2
rftoolsbuilder-1.20-6.0.1
rftoolscontrol-1.20-7.0.1
rftoolsdim-1.20-11.0.2
rftoolspower-1.20-6.0.1
rftoolsstorage-1.20-5.0.1
rftoolsutility-1.20-6.0.3

**Comment by manmaed** [comment]
@McJty any word on a fix

**Comment by McJty** [comment]
Not from my side. It works fine for me in vanilla. It is up to the mods causing this to fix this. I can't do it. Wouldn't have a clue how to start on it

**Comment by manmaed** [comment]
So Clean Install only mods listed are in:
Minecraft: 1.20.1
Neo: 47.1.76
Mods:
mcjtylib-1.20-8.0.3
rftoolsbase-1.20-5.0.2
rftoolsdim-1.20-11.0.2

Same Happens With a Forge install
Minecraft: 1.20.1
Froge: 47.2.4
Mods:
mcjtylib-1.20-8.0.3
rftoolsbase-1.20-5.0.2
rftoolsdim-1.20-11.0.2

so I feel this maybe your issue there are no other mods in this env to cause that issue unless I'm missing something

**Comment by McJty** [comment]
Hmm I'll try again. Last time I wasn't able to reproduce it

**Comment by manmaed** [comment]
i can also produce the isssue in https://github.com/McJtyMods/RFToolsDimensions/commit/643a710def0789687c300b014b32d1549efad46a (1.20 branch) running in IntelliJ

**Comment by McJty** [comment]
Ah I did manage to reproduce it. I'll check it out soon

**Comment by McJty** [comment]
Fixed
