### ISSUE TITLE
Error generating chunk

### ISSUE THREAD

**Issue by SikiciBebek** [McJty/RFToolsDimensions#465]
Issue description: Every time i try to access any dimension, my server crashes. 

Steps to reproduce: Create any dimension and teleport to it

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.14
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.19 - 7.2.5
* RFTools: rftoolsbase-1.19-4.1.7
* RFTools Dimensions: rftoolsdim-1.19.2-9.1.7

Possibly incompatible mods: Iam not sure if theres any carmods inside but no optifine or spongeforge etc. (modpack name "KOTD")

Relevant logs, if any: 

-Crash Report: https://pastebin.com/8VjGmfjE
- Logs: https://pastebin.com/NXPfpDiK
Was not able to upload the whole logs file, it was to big
thats the part from where it begings

**Comment by McJty** [comment]
Fixed in 9.1.8
