### ISSUE TITLE
Crash when creating a dimension

### ISSUE THREAD

**Issue by waddon1** [McJty/RFToolsDimensions#471]
Issue description: Server Crash when dimension reaches 100%, only happens on this specific dimension though.

Steps to reproduce: Create a dimension

Versions:
* Minecraft: 1.20.1
* NeoForge: 47.1.79 
* McJtyLib: 8.0.3
* RFTools: 5.0.2
* RFTools Dimensions: 11.0.1

Possibly incompatible mods: 

Relevant logs, if any: 
[crash-2023-10-27_14.32.13-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/13190167/crash-2023-10-27_14.32.13-server.txt)

**Comment by McJty** [comment]
This has been reported before. I currently don't know what's causing it

**Comment by ageuxo** [comment]
Edit: Wait it totally just says in the crash log, ignore me...

Hi Waddon, could you tell me what version of Tropicraft you have installed?

**Comment by McJty** [comment]
I'm currently investigating this

**Comment by McJty** [comment]
@waddon1 can you tell me the specifics of this dimension? Show me the contents of the tab (sneak right click)

**Comment by McJty** [comment]
nm, could reproduce it

**Comment by McJty** [comment]
Fixed in 11.0.2
