### ISSUE TITLE
game crash on dimension creation 1.20.1

### ISSUE THREAD

**Issue by hallool** [McJty/RFToolsDimensions#472]
Issue description:  game crashes when creating dimensin is on 99%

Steps to reproduce: 

make a dimensien

Versions:
* Minecraft: 1.20.1
* Forge: 47.2.4
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.20  8.0.3
* RFTools: 1.20  5.0.2
* RFTools Dimensions: 1.20   11.0.2

[crash-2023-11-03_16.14.07-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/13251926/crash-2023-11-03_16.14.07-server.txt)

**Comment by McJty** [comment]
Checking it out

**Comment by McJty** [comment]
Fixed

**Comment by hallool** [comment]
ty
