### ISSUE TITLE
Patchouli book format needs to be updated for 1.20

### ISSUE THREAD

**Issue by Danatr0nika** [McJty/RFToolsDimensions#476]
Issue description: Patchouli book "rftoolsdim:manual" fails to load when launching the game.

Steps to reproduce: Launch the game and read the RFTools Patchouli manual. No "Dimensions" section will be present.

Versions:
* Minecraft: 1.20.1
* Forge: NeoForge 47.1.83
* McJtyLib: 1.20-8.0.3
* RFTools: 1.20-5.0.2
* RFTools Dimensions: 1.20-11.0.4

Possibly incompatible mods: 
I don't think I have anything installed that could affect this. It's one flag in a json file inside the RFTools Dimensions jar.

Relevant logs, if any: 
[22:22:34] [Worker-ResourceReload-1/ERROR] [patchouli/]:  Failed to load book rftoolsdim:manual defined by mod rftoolsdim, skipping
java.lang.IllegalArgumentException: Book rftoolsdim:manual has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.

**Comment by McJty** [comment]
I'll check this out soon

**Comment by McJty** [comment]
Fixed next release
