### ISSUE TITLE
RfToolsDim 11.0.5 crash on start up

### ISSUE THREAD

**Issue by dangolon** [McJty/RFToolsDimensions#480]
Issue description: Crash on start up
When I start Minecraft Forge with only the rftools mods and jei it crashes saying rftools dimensions failed to load.
Also tested w/o jei and with only mcjtylib, rftoolsbase and rftoolsdim

Steps to reproduce: 
just dropping the jar files (versions below) into the mods folder and start forge. ~at least on my machine ..

Versions:
* Minecraft: 1.20.2
* Forge: 48.1.0
* CompatLayer (only if on Minecraft 1.10 or 1.11): ---
* McJtyLib: 8.0.3
* RFTools: rftoolsbase I assume 5.0.2
* RFTools Dimensions: 11.0.4 and 11.0.5

Possibly incompatible mods: 

Relevant logs, if any: 

Forge Log: https://pastebin.com/BbWde6tw
Crash Log: https://pastebin.com/ZLwBPNxH

**Comment by McJty** [comment]
RFTools Dimensions is not compatible with 1.20.2

**Comment by dangolon** [comment]
woops didn't thought about that bc it's a patch

anyways top mod and thx for the fast reply \o
