### ISSUE TITLE
Don't know how to create custom Tag dimlets.

### ISSUE THREAD

**Issue by thecommandman0** [McJty/RFToolsDimensions#482]
I wouldn't count this one as an "issue" (unless you allow skill issues), but it is still worth bringing up.

Is it possible to create custom Tag dimlets? If so, how would you define what to use as the identifier? (ex. white wool for #minecraft:wool) If I wanted to create a dimlet for #minecraft:planks through the config, how would the code look?

**Comment by McJty** [comment]
Check the tag dimlets that are already in RFTools Dimensions. They are located in 'vanilla_tags.json'

**Comment by thecommandman0** [comment]
Where would I find that file? If it's in the mod itself, I'm screwed, because I have no idea how to get to it.

**Comment by McJty** [comment]
https://github.com/McJtyMods/RFToolsDimensions/tree/1.20/src/main/resources/data/rftoolsdim/dimletpackages

**Comment by thecommandman0** [comment]
Thank you, that also answers a few other questions.
