### ISSUE TITLE
1.20.1 Error Loading : Ljava.lang.NoSuchMethodError: 'void mcjty.lib.modules.modules.initconfig()'

### ISSUE THREAD

**Issue by Doctor9256** [McJty/RFToolsDimensions#484]
Issue description: 
Error loading mods. 1 error has occurred during loading. I am playing chosen's Modded Adventure modpack and i added RFToolsDimensions to the modpack which is forge and has McJtyLib installed at lastest version. It aslo has RFToolsBase, Builder, power, storage, and utility

Steps to reproduce: 
Load the modpack. 

Versions:
* Minecraft: 1.20.1
* Forge: 47.2.30

* McJtyLib: 1.20-8.0.4
* RFTools:1.20-5.0.3
* RFTools Dimensions:  1.20-11.0.0

Possibly incompatible mods: I did not attempt to eliminate mods. will try in the future and update. But I working with chosen's modded adventure modpack

Relevant logs, if any: 
Log - https://pastebin.com/4KRXyZ6C
Crash Report - https://pastebin.com/J27xuVb1

**Comment by McJty** [comment]
Your RFTools Dimensions is outdated. Use the latest version please
