### ISSUE TITLE
Dimlet Workbench contains disabled block dimlets

### ISSUE THREAD

**Issue by Gerdathlete** [McJty/RFToolsDimensions#502]
Issue description: 

Block dimlets that are disabled through config files and cannot be absorbed by block absorbers are still visible in the dimlet workbench. 

## In dimlet workbench:
![image](https://github.com/user-attachments/assets/9779cff1-7d8b-48ac-b881-f177c184c894)

## In config
![image](https://github.com/user-attachments/assets/dc34793f-3d4c-47f6-8c4d-3f1c5a3bdbf5)

Steps to reproduce:
I am running the Project Architect 2 pack version 3.6. This modpack has a configuration that resulted in this issue.

Versions:
* Minecraft: 1.20.1
* Forge: 47.3.7
* McJtyLib: 1.20-8.0.6
* RFTools: 1.20-5.0.5
* RFTools Dimensions: 1.20-11.0.9

Possibly incompatible mods: 
Embeddium
Oculus (shaders are disabled)

**Comment by McJty** [comment]
Yes that's normal. If you really want the dimlet gone then just remove it from the json completely
