### ISSUE TITLE
[1.20.1] Missing critical blocks

### ISSUE THREAD

**Issue by JohnVonDrashek** [McJty/RFToolsDimensions#506]
Issue description: 
Missing the following blocks and items:
Dialing Devices
Matter Transmitters
Matter Receivers
RFTools Manual

![Screenshot 2024-10-02 210139](https://github.com/user-attachments/assets/9f11e2d9-83bb-4c98-9860-55c9a814e7ed)

Steps to reproduce: 
Using CurseForge client. Creating a fresh install of just Forge, McJtyLib, RFTools, RFTools Dimensions, and patchouli (optional)

Versions: 
* Minecraft: 1.20.1
* Forge: 47.3.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.20-8.0.6
* RFTools: 1.20-5.0.5
* RFTools Dimensions: 1.20-11.0.9

Possibly incompatible mods: None. I did it with only the minimum mods needed for dimensions

Relevant logs, if any: 
No issues show up in the log

**Comment by peachmarblesoda** [comment]
Did you ever figure this out? I am having the same exact issue.

**Comment by JohnVonDrashek** [comment]
> Did you ever figure this out? I am having the same exact issue.

You need the RFTools Utility mod
