### ISSUE TITLE
[1.10.2] Energy Extractor does nothing

### ISSUE THREAD

**Issue by chaNcharge** [McJty/RFToolsDimensions#52]
Exactly as the title says, I try to right click the energy extractor to open the gui, yet nothing happens. An energy conduit does connect to it, however no power goes in or out

**Comment by McJty** [comment]
It has no GUI so that's normal.

You are using it in an RFTools Dimension right?

**Comment by chaNcharge** [comment]
Oh sorry, didn't know that you put it in a rftools dimension. The manual should be updated to where it says that though.
