### ISSUE TITLE
Time absorber not working

### ISSUE THREAD

**Issue by jpeaglesandkatz** [McJty/RFToolsDimensions#58]
1.10.2
rftoolsdim-1.10-4.44.jar
mcjtylib-1.10-2.2.0.jar
Latest forge, all mods updated

Time absorber in the overworld totally not working.. Applying redstone signal nothing happens or not the way it is intended. I keep flipping the switch at around noon trying to capture it.. Highest in 500 attempts I've seen it get over 3 weeks of ingame time is 10%. Since the explanation on how this is supposed to work is vage at best it could be that I'm missing something.

**Comment by McJty** [comment]
It is indeed a bit hard to use and also it handles redstone a bit weird. It doesn't work with a lever on it but you have to put a redstone dust next to it and then a lever. Also there is a timeout so you have to wait a bit before you can apply a new redstone signal. But it is working. Direwolf has been using it in his forgecraft series.

I'll work on a better system at some point

**Comment by jpeaglesandkatz** [comment]
Thank you for the clarification! :)

**Comment by Apocryphai** [comment]
I also can't get the Time Absorber to work at all. I've tried connecting it to a Bibliocraft clock, set to emit a redstone pulse at noon. Whether it's directly adjacent to the clock, connected by EnderIO Insulated Redstone Conduit or connect with vanilla redstone it doesn't react to the pulse at all.

I've also tried using a button and a lever, with the same variety of connections, and none of them do anything either.

**Comment by McJty** [comment]
Don't put the lever on the block. Put the lever a few blocks away and place a few redstone dots to connect it to the absorber: so absorber, redstone dust, lever
That setup works

**Comment by Apocryphai** [comment]
Aha, yes, that works, thank you! I was sure I'd tried that, sorry :)

**Comment by Cal26lum** [comment]
I am able to get to 20% quite easily, but cannot get anything after that point. I have tried varying lengths of redstone as well as directly from repeaters, buttons and command blocks. Any advice?

**Comment by McJty** [comment]
How are you feeding the redstone? A lever adjacent to it doesn't work. Has to be with a redstone dust on the floor

**Comment by Cal26lum** [comment]
Never mind, I wasn't leaving enough time between my attempts to absorb the time. It's working now
