### ISSUE TITLE
[1.11] Dimensions have no lighting level during the daytime

### ISSUE THREAD

**Issue by Nullga** [McJty/RFToolsDimensions#60]
Forge 13.19.0.2176
CompatLayer 0.0.39beta
McJtylib 2.2.0beta
RFTools 5.62beta1
RFTools Dimensions 4.45beta1

Creating some dimensions and they have no lighting level even during the daytime. I've tried with different combinations of dimlets but all got the same results as of now. All config files aren't changed, dimension tabs have max RF stored.

Log (load the world -> create a dimension)
http://pastebin.com/dAA9GLk7
Screenshots
http://imgur.com/a/RbXSB

**Comment by McJty** [comment]
Fixed next release (tomorrow)
