### ISSUE TITLE
Dimension in use when trying to delete demension

### ISSUE THREAD

**Issue by DigitalSketch** [McJty/RFToolsDimensions#63]
We're trying to delete some dimensions that are no longer used, and we get a "Dimension in use" error when we try to do it.  The dimensions have no one in them, and have no power.  The dimension tabs have all been extracted and are no longer valid as well.

**Comment by McJty** [comment]
Are there chunkloaders? Perhaps with FTB Utilities? That would prevent deletion as well

**Comment by DigitalSketch** [comment]
no those were removed, as well as the matter receivers, just to make sure nothing was in the world

**Comment by McJty** [comment]
What version?

**Comment by DigitalSketch** [comment]
we're on the 1.4 hermitpack running 1.10-4.45 of the RFTools Dimensions,

**Comment by McJty** [comment]
I have also noticed that on 1.10 something is keeping dimensions loaded longer then they should. Haven't found a solution for that yet

**Comment by DigitalSketch** [comment]
if we delete the files on the server for the server folder, would that make the dimension invalid and able to delete?

**Comment by McJty** [comment]
No, it would still be known to rftools dimensions. I would recommend just leaving it there for now until I come up with a solution. That dimension should not be harmful to anyone.

**Comment by DigitalSketch** [comment]
is there a limit on dimensions?  When I create my new one, it doesn't show up in the dialer, and if we try ti TP to it, it doesn't let us.  We thought maybe there was a limit and thats why we tried to delete the old ones.

**Comment by McJty** [comment]
There is no limit. Is it only that dimension that is not working or can't you make any new dimension?

**Comment by DigitalSketch** [comment]
looks like we can't make any new ones.  when we create the Dimension tab, it says everything is OK, and the aren't anything crazy.  The latest one is just a flat world with gold blocks, peaceful, with an efficiency dim in it.  We tried just a plain void world as well and it wouldn't show up, or let us TP.

**Comment by McJty** [comment]
So the new dimensions don't show up in the dialer?

Anything special in the logs? Can you show those?

**Comment by DigitalSketch** [comment]
I'll have to get those from the owner this evening.  I did restart the server, and it managed to make the new one.  It shows up in the dialer now, but says the receiver is invalid.

**Comment by McJty** [comment]
I think logs will be useful to debug what is going on because that is really weird

**Comment by DigitalSketch** [comment]
These were the logs from yesterday while we were trying to create/teleport to the dimensiosn:

http://familycraftmc.com/logs/2016-12-04-4.log
http://familycraftmc.com/logs/2016-12-05-2.log
http://familycraftmc.com/logs/2016-12-05-1.log
http://familycraftmc.com/logs/2016-12-04-3.log

**Comment by McJty** [comment]
Hmm, I see sponge. Were you always using sponge?

**Comment by McJty** [comment]
I see a crash in your logs related to sponge. I don't really understand it so possibly someone from sponge might want to take a look at this and see what's going on

**Comment by DigitalSketch** [comment]
Yea we've had sponge for a long time and other dimensions were created while we had it going.

**Comment by McJty** [comment]
Could you report this to sponge too? Especially with those logs. Not saying it is their bug but it is crashing partially in their code so there could be some conflict going on

**Comment by DigitalSketch** [comment]
Will do :)

**Comment by bloodmc** [comment]
@DigitalSketch This is sponge issue for sure as we do not handle RFTools dimension deletions properly. I'll fix it soon.

**Comment by bloodmc** [comment]
@McJty Please close this ticket as it has been resolved in latest SpongeForge.

**Comment by McJty** [comment]
Thanks!
