### ISSUE TITLE
Lost dimlets on server crash, how do I spawn them in?

### ISSUE THREAD

**Issue by DigitalSketch** [McJty/RFToolsDimensions#65]
I was in the middle of crafting a new dimension when the server crashed, and I lost all the dimlets I had in the enscriber. I had extras or crafted everything but the village structure and fortress structure dimlets. how do I spawn these in?

**Comment by McJty** [comment]
Go to creative and use the dimlet workbench to cheat them in (see the tooltip for info when hovering over dimlets in the workbench)
