### ISSUE TITLE
Unable to create new dim after deleting a dim

### ISSUE THREAD

**Issue by Mohron** [McJty/RFToolsDimensions#68]
## Mod Versions
- forge-1.10.2-12.18.3.2185-universal
- mcjtylib-1.1x-2.3.1
- rftools-1.1x-5.71
- rftoolsdim-1.1x-4.51

## Config Changes
dimensionBuilderNeedsOwner=true
dimensionFolderIsDeletedWithSafeDel=true
maxDimensionsPerPlayer=1
playersCanDeleteDimensions=true

## Issue
In order to keep dimensions under control I have limited players to 1 dimension at a time. This works as intended. The issue we are facing is when a player uses `/rftdim safedel <dimid>` and their unwanted dim is deleted, they can't make a new dim until after a server restart. If they attempt to make a new dim before a server restart, it assigns the dim the same dim ID but no dim is ever created. It is not listed on the dialer or the Teleporter Probe. If a player deletes their dim and disassembles the tab before a restart and waits until after a restart before assembling a new tab a working dimension is created.

**Comment by bloodmc** [comment]
@Mohron This is a SpongeForge bug. I'll work on a fix soon.

**Comment by bloodmc** [comment]
@McJty This has been resolved in latest SpongeForge. Please close ticket.

**Comment by McJty** [comment]
Thanks
