### ISSUE TITLE
Entity Drops don't work with SpongeForge

### ISSUE THREAD

**Issue by Mohron** [McJty/RFToolsDimensions#69]
This is a simple fix that would be much appreciated by every server running sponge and RFTools Dims. Instead of directly adding the drop directly it needs to be added to the LivingDropsEvent. I can fix this with a simple patch on the server side but I'd much rather see a permanent fix. I'll follow this up with a PR.

Problem Code: https://github.com/McJty/RFToolsDimensions/blob/master/src/main/java/mcjty/rftoolsdim/ForgeEventHandlers.java#L162

**Comment by McJty** [comment]
Merged
