### ISSUE TITLE
[question][feature request] Is there a way to blacklist liquids from being used in dimensions server wise?

### ISSUE THREAD

**Issue by winsrp** [McJty/RFToolsDimensions#71]
Hi, 

As the title says, I would like to ban some liquids from being used in the generated dimensions, there are 2 types of liquids from Biomes o plenty that just destroy the server.. total freeze, even the console gets stuck so alt+f4 is the only solution.

Mainly the problem we are having is with quicksand.. I really just want to remove this liquid from dimensions, the first one we had issue with, created huge orbs and that nearly killed the server, and the last one spawned with huge oceans of quicksand.. and that was game over.

thanks.

**Comment by McJty** [comment]
You can easily blacklist dimlets in the dimlets.json config file

**Comment by winsrp** [comment]
and does blacklisting a dimlet prevents that material/liquid to ever show up on dimensions? including a random component?

**Comment by winsrp** [comment]
also, I'm almost 90% sure the quicksand dimlet (which is a liquied but really does not exist as liquid dimlet) shows up as a material dimlet with the question mark sign.

search for ? dimlet on the workbench.

**Comment by McJty** [comment]
yes, blacklisting prevents it from happening. For quicksand you might want to disable the material dimlet but unfortunatelly there is no solution if the quicksand occurs with biome generation

**Comment by winsrp** [comment]
well I don't mind quicksand if its like normal small lakes of quicksand that does not move. But an ocean or terrain made entirely out of quicksand that is a bit too much

**Comment by winsrp** [comment]
OK I seem to not be able to remove the quicksand from the dimlets, maybe I'm doing it wrong or maybe I'm doing it just very wrong lol... a little guidance here would be much welcome.

I add the following line

  {
    "filter": {
      "mod": "biomesoplenty",
      "name": [
        "sand",
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 30,
      "ticks": 10,
      "worldgen": false,
      "dimlet": false
    }
  },

and also there is a similar one that has BOP sand in it, where I remove sand from there, and also I remove the line that says that everything under it will be regenerated everytime if that line is there.

When start the server the file is regenerated again so my config is gone =/ I'm 100% that I might be doing something wrong here.

Help plz!

**Comment by McJty** [comment]
Did you see the line in that config that says to place your rules above that line?

**Comment by winsrp** [comment]
I only see this line

"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

And I though it said to remove the line to prevent regeneration, not to put thing over it???

**Comment by McJty** [comment]
It is best to leave that line there and put your rules above that line. The things below that line will be regenerated when rftools dimensions is updated. The things above that line are your rules

**Comment by winsrp** [comment]
So on that, If I put the sand removal on top of that line but on the middle of the file there is a line that adds  a bunch of BOP stuff including the sand I want to remove, will it stay removed, or will it be added due to the second line?

**Comment by winsrp** [comment]
I just gave it a try and it is still there... checked the file, and it was back to default it deleted everything I put over that line. =/

**Comment by winsrp** [comment]
> [
  {
    "filter": {
      "mod": "biomesoplenty",
      "name": [
        "sand",
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 30,
      "ticks": 10,
      "worldgen": false,
      "dimlet": false
    }
  },
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
  {
    "filter": {
      "name": "owner",
      "type": "special"
    },

this what I put, and it gets wiped on server restart

**Comment by winsrp** [comment]
not sure if the fact that it is technically a liquid, but it is registered as a solid material, and shows up with the question mark "?" as the name of the dimlet has something to do with it.
