### ISSUE TITLE
Ocelot is incorrectly spelled "Ozelot"

### ISSUE THREAD

**Issue by Ricket** [McJty/RFToolsDimensions#72]
![image](https://cloud.githubusercontent.com/assets/196978/21596138/ef21d402-d104-11e6-8a95-1d583ccfcf1c.png)

I see there are two places in the repository where the word "Ozelot" shows up:

https://github.com/McJty/RFToolsDimensions/search?utf8=%E2%9C%93&q=Ozelot

**Comment by McJty** [comment]
This is actually how it is called in Minecraft internally. I cannot fix that
