### ISSUE TITLE
Crash when clicking the "Compass" tab in Creative menu.

### ISSUE THREAD

**Issue by CMCarlsen** [McJty/RFToolsDimensions#74]
MC version: 1.10.2
Forge version: 12.18.3.2221

When clicking through the Creative tabs, I clicked the "Compass" tab, and my client just straight crashed. At first I thought it was because I have too many mods (which it might still be?), but the error report makes me think maybe not.

Crash report:
http://pastebin.com/czDxJrCj

**Comment by Ampflower** [comment]
A simple null check will do.
