### ISSUE TITLE
Creative Dimension Builder [Feature Request]

### ISSUE THREAD

**Issue by Quizer9O8** [McJty/RFToolsDimensions#75]
Creating experimental dimensions with a load of dimlets in them causeses the dimension builder to create it for several minutes which is too slow for me. I want a dimension builder for creative mode that can create this dimensions instantly.

**Comment by McJty** [comment]
Insert a 'cheater' dimlet that you can obtain in creative from the dimlet workbench. Add that to your dimension for instant creation

**Comment by Quizer9O8** [comment]
Thank you so much for telling that. I've spent countless hours to create a dimension before. This will help for sure.
