### ISSUE TITLE
[1.10.2] Server crash while loading world

### ISSUE THREAD

**Issue by rmnaderdev** [McJty/RFToolsDimensions#79]
I'm not really sure what's happening here but this just happened all of the sudden this morning. Everything works fine when I take out this mod but if I leave the mod in and change the world the crash still happens on startup. I am using sponge but I don't believe that is the problem.
[Pastebin](http://pastebin.com/9iienLcA)

**Comment by McJty** [comment]
Are you using latest version of sponge because this does look like a sponge problem. They were investigating dimension related issues

**Comment by rmnaderdev** [comment]
Alright, I'll roll back the sponge version to confirm.

**Comment by rmnaderdev** [comment]
It was sponge. Sorry about that and thanks for the help! Hopefully this will get resolved soon. SpongePowered/SpongeForge#1046
