### ISSUE TITLE
1.9-Ticking block entity and NoClassDefFoundError when dimension fully realized

### ISSUE THREAD

**Issue by RealGrep** [McJty/RFToolsDimensions#8]
Unable to create a dimension, or access previously created one.

This is with rftoolsdim-1.9.0-4.23beta35.jar, rftools-1.9.0-4.41.jar, and mcjtylib-1.9.0-1.8.2.jar. Should be the latest ones as of this bug report.

Steps taken:

1. In dimension enscriber, add empty dimension tab, and in this case the digit 8 dimlet, but others including none have done the same thing. Store.
2. Put realized dimension tab in dimension builder. It starts generating it, and when the percent indicator hits 100%, I get the error. I assume it would crash the client normally, but I have forge set to remove erroring entities at the moment. It does so and destroys the realized dimension tab.

Also no longer able to teleport to previously created dimension. Dialer refuses to lock onto the receiver. Using safedel seems to remove the dimension with no logged errors, but says: "An unknown error occurred while attempting to perform this command".

The log: http://pastebin.com/5W325edc

Relevant extract from the log, for quick reference:

Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:188)

Note that this worked in the previous version, for me, so something changed that broke this between then and now, I think.

Thanks! And P.S. Deep Resonance seems to work nicely now. Having much fun with it. :)

**Comment by McJty** [comment]
Just published a new release of RFTools Dimensions which should fix this bug.

**Comment by RealGrep** [comment]
Thanks! You are very efficient, good sir. :)
