### ISSUE TITLE
Crash when creating dimension

### ISSUE THREAD

**Issue by bdew** [McJty/RFToolsDimensions#80]
Crashed as dimension building was completed. After restarting the dimension wasn't usable (missing dimension data). I've deleted the bugged dimension and re-created it without crashing, but it didn't get the extra random mob entries the second time, which might be related.

Crash report: https://gist.github.com/bdew/5699271fc07dbe7927b3b0f0df1610ce

Info of the dimension being created: https://gist.github.com/bdew/7c402e884ca87fa81cfe1eca01a3a1f6 (this was taken after the restart)

**Comment by McJty** [comment]
I'm checking it out. Thanks for the report

**Comment by McJty** [comment]
This is very weird. The code for Biome.SpawnListEntry has nothing to 'null-pointer-except' on. I don't understand how this can even happen. Suggestions are welcome

**Comment by McJty** [comment]
I found out the cause. Will be fixed next release

**Comment by bdew** [comment]
Out of curiosity... what was it? Because looking at SpawnListEntry i don't see it either.

**Comment by McJty** [comment]
Apparently entityClass was null and if you update forge in the dev env there is apparently some new forge added code that does something with that class. I missed that because my forge was older
