### ISSUE TITLE
Blacklisted dimlets with default configs.

### ISSUE THREAD

**Issue by Apocryphai** [McJty/RFToolsDimensions#83]
I know there's already an issue for this ([Issue #44 ](https://github.com/McJty/RFToolsDimensions/issues/44) ) but it's been closed when it appears to be still unresolved. Please close this one if this is superfluous, thanks.

Minecraft 1.10.2
CompatLayer 1.10-0.2.1
McJtyLib 1.1x-2.3.6
RFTools 1.1x-5.82
RFTools Dimensions 1.1x-4.54
Forge 2185

Several dimlets are listed as blacklisted which I'd expect to be able to craft. The dimlets.json file exists on both server and client and hasn't been modified from default. Checking in that file I can't find anything that should be blacklisting these dimlets. The dimlets in question are:

Mob Dimlet (Default)
Sky Dimlet (Normal night)
Liquid Dimlet (Water)
Material Dimlet (Stone)
Time Dimlet (Normal)
Weather Dimlet (Default)
Sky Dimlet (Normal)
Sky Dimlet (Normal day)

Am I just misunderstanding something about these dimlets or is it a bug? I've tried creating, for example, a void dimension without these dimlets and things like time, weather and sky are then created randomly.

Edit: Forgot to add that almost all material, liquid, sky and time dimlets that are looted from packages, chests, etc, are also blacklisted.

**Comment by Apocryphai** [comment]
Update to this: I've just discovered that the dimlets are only blacklisted on my server. When I launch a singleplayer creative game the dimlets are available as normal.

**Comment by McJty** [comment]
I'll check it out soon

**Comment by Apocryphai** [comment]
OK, seeing that the dimlets were only blacklisted on the server I thought I'd just try using them, and they work fine. So it's just a display issue with the blacklisted tag.

**Comment by McJty** [comment]
You need the same configs on both server and client
