### ISSUE TITLE
"Feature Absorber" not showing contained feature

### ISSUE THREAD

**Issue by asleire** [McJty/RFToolsDimensions#84]
According to the changelog for "4.20beta15" the "Feature Absorber" is supposed to show the feature it extracted once extraction reaches 100%. However, the WAILA tooltip displays "Unknown feature" even at 100%.

**Comment by sandalle** [comment]
Same with [The One Probe](https://github.com/McJty/TheOneProbe), leaving the block alone for about 10 minutes _after_ it reached 100%. Also picked up the block and still unknown, along with trying to put it in a Crafting Table to see if that helps and a Dimlet Workbench, but no dice there.

![feature absorber 100 unknown](https://cloud.githubusercontent.com/assets/2447608/23680243/5cc8cf1c-033f-11e7-8043-8a1789cabffb.png)

Dimension information:
`Description string @eFlight,eSaturation1,eResistance3,XEfficiency,XEfficiency,XEfficiency,#mjurassicraft:amber_ore@0,#mdraconicevolution:draconium_ore@0,#mrftools:dimensional_shard_ore@0,fOregen`
![dimension 25 information](https://cloud.githubusercontent.com/assets/2447608/23680385/e62358d6-033f-11e7-99e7-d166a0f2e070.png)

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
RFTools: 1.1x-5.87
RFTools Dimensions: 1.1x-4.54

**Comment by McJty** [comment]
Fixed next version
