### ISSUE TITLE
[1.1x-4.54] crash while exploring SSP

### ISSUE THREAD

**Issue by kreezxil** [McJty/RFToolsDimensions#86]
With mod installed, in SSP, went exploring and was killing villagers, then it crashed.

http://pastebin.com/PeZtSzLC

Not sure if it is Blood Magic, so posting there at https://github.com/WayofTime/BloodMagic/issues/1057.

**Comment by VT-14** [comment]
Blood Magic has tagged their issue as code complete, so looks like it was on their side.
