### ISSUE TITLE
Creative Mode Crash When Searching

### ISSUE THREAD

**Issue by eractnod** [McJty/RFToolsDimensions#89]
Creative Mode crash when trying to search

In a creative world, press 'e' to open inventory.  Click on the search button and get this crash for Index out of bound error.  I can use JEI search window without crashing.  I removed Blood Magic and was able to use the search button.  Loaded version 72 of Blood Magic.  Same crash, except not 16, but 32767 for the index out of bound error.  Created a pack with just Blood Magic and all worked fine.  Added RFTools and RFTools Dimensions and get the crash.  Not sure if RFTools or Blood Magic is causing the crash.  Have created the issue on both sites.

1.  In creative world and creative mode, open inventory
2.  Click on Minecraft creative tab search button
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.4-73
- Minecraft: 1.11.2
- Forge: 2252
- rftoolsdim: 1.1x-4.54
[crash-2017-02-25_16.50.48-client.txt](https://github.com/McJty/RFToolsDimensions/files/801545/crash-2017-02-25_16.50.48-client.txt)

**Comment by McJty** [comment]
I will add protection to rftools dimensions to not crash but it does appear to be a bug in Blood Magic though. @WayOfTime can you have a look at this?

**Comment by WayofTime** [comment]
This was already fixed here: https://github.com/WayofTime/BloodMagic/issues/1057

**Comment by McJty** [comment]
Aha thanks
