### ISSUE TITLE
client cant join server (1.11.2) after updating to rftoolsdim-1.1x-4.55

### ISSUE THREAD

**Issue by SDUBZ** [McJty/RFToolsDimensions#93]
forge:1.11.2-2259
rftools: rftools-1.1x-5.88
rftools dim: rftoolsdim-1.1x-4.55

client log: http://puu.sh/uLm2e/be22917ab3.log

**Comment by McJty** [comment]
That's really weird. Client is updated too? Does rolling back to previous version fix this?

**Comment by SDUBZ** [comment]
yes both same versions

**Comment by SDUBZ** [comment]
i will test with 54 and see if it still happens

**Comment by SDUBZ** [comment]
aswell it seems to happen with 54 too

**Comment by McJty** [comment]
Well then I don't think this has anything to do with rftools dimensions even though it triggers in that mod. I would have no clue how that kind of error is even possible. Anything else that changed/got updated besides rftools dimensions?

**Comment by SDUBZ** [comment]
umm yes heres a list of mod changes 
[print.txt](https://github.com/McJty/RFToolsDimensions/files/847482/print.txt)

**Comment by McJty** [comment]
I don't immediatelly see anything suspicious. Maybe you should try from a working sitatuation first (i.e. I hope you got a backup from before the update) and add/update mods one by one?

**Comment by SDUBZ** [comment]
but could cause this trigger to happen Caused by: java.lang.NullPointerException: Undefined message for discriminator 82 in channel rftoolsdim

**Comment by McJty** [comment]
I have no idea. Never seen that message before

**Comment by SDUBZ** [comment]
do you think a refresh of rftools configs might help at all?

**Comment by McJty** [comment]
No. That's doubtful

**Comment by SDUBZ** [comment]
this is kinda weird just dont what could be the cause is the issue to tackle here

**Comment by SDUBZ** [comment]
oh well a long night ahead of me i suppose

**Comment by SDUBZ** [comment]
weird even after rolling back chnages it still gives me the same error odd O_O

**Comment by SDUBZ** [comment]
got it going dude it was a corrupted jar thanks for your help anyways @McJty :D
