### ISSUE TITLE
NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by joelaw9** [McJty/RFToolsDimensions#97]
Minecraft: 1.10.2
RFTools: 1.1x-5.87
RFTools Dimensions: 1.1x-4.54
Sky Factory: 3.0.8

[crash-2017-03-22_20.37.59-server.txt](https://github.com/McJty/RFToolsDimensions/files/863413/crash-2017-03-22_20.37.59-server.txt)
[crash-2017-03-22_20.46.46-server.txt](https://github.com/McJty/RFToolsDimensions/files/863420/crash-2017-03-22_20.46.46-server.txt)

The dimension exists on my local creative test world and only has an Ender Dragon dimlet specified, everything else is auto selected. The first crash occurred while building an obsidian platform to stand on, the second while I was just standing on said platform writing this Issue. Dragons were spawned and flying around.

**Comment by McJty** [comment]
Work around this issue for next release
